-- Migration: Insert Adelboden Giant Slalom Preview Article
-- Run with: psql -d neve26 -f migrations/002_adelboden_preview.sql
-- Or copy and run in any PostgreSQL client

INSERT INTO articles (
    slug,
    title,
    excerpt,
    content,
    category,
    sport_code,
    athlete_slugs,
    venue,
    venue_city,
    meta_description,
    structured_data,
    status,
    published_at,
    source_type
) VALUES (
    'adelboden-giant-slalom-preview-2026',

    -- TITLE (11 languages)
    '{
        "en": "Adelboden Giant Slalom Preview: Odermatt Eyes Fourth Consecutive Victory",
        "de": "Adelboden Riesenslalom Vorschau: Odermatt peilt vierten Sieg in Folge an",
        "fr": "Aperçu du Slalom Géant d''Adelboden : Odermatt vise une quatrième victoire consécutive",
        "it": "Anteprima Slalom Gigante Adelboden: Odermatt punta alla quarta vittoria consecutiva",
        "es": "Vista previa del Slalom Gigante de Adelboden: Odermatt busca su cuarta victoria consecutiva",
        "pt": "Prévia do Slalom Gigante de Adelboden: Odermatt mira quarta vitória consecutiva",
        "nl": "Vooruitblik Adelboden Reuzenslalom: Odermatt mikt op vierde opeenvolgende zege",
        "ar": "معاينة سباق التزلج العملاق في أدلبودن: أوديرمات يسعى للفوز الرابع على التوالي",
        "ja": "アーデルボーデン大回転プレビュー：オーデルマットが4連勝を目指す",
        "zh": "阿德尔博登大回转预告：奥德马特瞄准四连胜",
        "ko": "아델보덴 대회전 프리뷰: 오더마트, 4연승 노린다"
    }'::jsonb,

    -- EXCERPT (11 languages)
    '{
        "en": "The FIS World Cup returns to the legendary Chuenisbärgli for one of alpine skiing''s most demanding Giant Slalom races. Can anyone stop Marco Odermatt on his home snow?",
        "de": "Der FIS Weltcup kehrt zum legendären Chuenisbärgli zurück für einen der anspruchsvollsten Riesenslaloms im alpinen Skisport. Kann jemand Marco Odermatt auf heimischem Schnee stoppen?",
        "fr": "La Coupe du Monde FIS revient sur le légendaire Chuenisbärgli pour l''une des courses de Slalom Géant les plus exigeantes du ski alpin. Quelqu''un peut-il arrêter Marco Odermatt sur sa neige natale?",
        "it": "La Coppa del Mondo FIS torna al leggendario Chuenisbärgli per una delle gare di Slalom Gigante più impegnative dello sci alpino. Qualcuno può fermare Marco Odermatt sulla sua neve di casa?",
        "es": "La Copa del Mundo FIS regresa al legendario Chuenisbärgli para una de las carreras de Slalom Gigante más exigentes del esquí alpino. ¿Alguien puede detener a Marco Odermatt en su nieve local?",
        "pt": "A Copa do Mundo FIS retorna ao lendário Chuenisbärgli para uma das provas de Slalom Gigante mais exigentes do esqui alpino. Alguém pode parar Marco Odermatt em sua neve natal?",
        "nl": "De FIS Wereldbeker keert terug naar de legendarische Chuenisbärgli voor een van de meest veeleisende Reuzenslalom wedstrijden in het alpineskiën. Kan iemand Marco Odermatt stoppen op eigen sneeuw?",
        "ar": "يعود كأس العالم للاتحاد الدولي للتزلج إلى منحدر شوينيسبيرجلي الأسطوري لواحد من أصعب سباقات التزلج العملاق. هل يستطيع أحد إيقاف أوديرمات على ثلوجه المحلية؟",
        "ja": "FISワールドカップが伝説のチュエニスベルグリに戻り、アルペンスキー最難関の大回転レースの一つが開催される。地元の雪上でオーデルマットを止められる者はいるのか？",
        "zh": "国际滑雪联合会世界杯重返传奇的楚尼斯贝格利赛道，迎来高山滑雪最具挑战性的大回转赛事之一。有人能在奥德马特的主场阻止他吗？",
        "ko": "FIS 월드컵이 전설적인 추에니스베르글리로 돌아와 알파인 스키 최고 난이도의 대회전 레이스를 펼친다. 홈 슬로프에서 오더마트를 막을 수 있는 선수가 있을까?"
    }'::jsonb,

    -- CONTENT (11 languages - HTML)
    '{
        "en": "<p>This Saturday, January 11th, the world''s best giant slalom skiers descend upon the Swiss village of Adelboden for the 68th edition of the legendary Chuenisbärgli race. The steep, demanding course has become synonymous with technical excellence and dramatic racing.</p><h2>Odermatt''s Dominance</h2><p>Swiss sensation <strong>Marco Odermatt</strong> arrives in Adelboden as the overwhelming favorite. The reigning overall World Cup champion has won the last three editions here, establishing himself as the undisputed king of the Chuenisbärgli. His combination of raw power and technical precision makes him nearly unbeatable on this terrain.</p><p>\"Adelboden is special,\" Odermatt said earlier this season. \"The atmosphere, the fans, the course itself - everything comes together. It gives me extra energy.\"</p><h2>The Challengers</h2><p>Norway''s <strong>Henrik Kristoffersen</strong> remains the most likely to challenge Odermatt. The veteran technician has been in excellent form this season, with multiple podiums already secured. His aggressive, attacking style suits the steep pitches of the Chuenisbärgli.</p><p>Watch also for <strong>Loic Meillard</strong>, Odermatt''s Swiss teammate who has shown flashes of brilliance this season, and Austria''s <strong>Manuel Feller</strong>, always dangerous in technical events.</p><p>An intriguing storyline surrounds <strong>Lucas Pinheiro Braathen</strong>, now racing under the Brazilian flag. The former Norwegian star made waves with his return to competition and could be a factor if conditions suit his aggressive approach.</p><h2>The Course</h2><p>The Chuenisbärgli is notorious for its steep opening section, followed by a series of demanding turns that require both courage and precision. The course drops 420 meters over its 1,510-meter length, with an average gradient that tests even the best skiers'' legs.</p><p>Thousands of fans are expected to line the course, creating the famous \"Adelboden atmosphere\" that makes this one of the most anticipated stops on the World Cup calendar.</p><h2>Race Schedule</h2><ul><li><strong>Saturday, January 11</strong>: Giant Slalom - Run 1 at 10:30 CET, Run 2 at 13:30 CET</li><li><strong>Sunday, January 12</strong>: Slalom - Run 1 at 10:30 CET, Run 2 at 13:30 CET</li></ul><p>Follow all the action live on Neve26 with real-time updates and notifications.</p>",

        "de": "<p>Am Samstag, 11. Januar, treffen sich die besten Riesenslalom-Fahrer der Welt im Schweizer Dorf Adelboden zur 68. Ausgabe des legendären Chuenisbärgli-Rennens. Die steile, anspruchsvolle Piste ist zum Synonym für technische Exzellenz und dramatische Rennen geworden.</p><h2>Odermatts Dominanz</h2><p>Das Schweizer Ausnahmetalent <strong>Marco Odermatt</strong> kommt als haushoher Favorit nach Adelboden. Der amtierende Gesamtweltcup-Sieger hat die letzten drei Ausgaben hier gewonnen und sich als unbestrittener König des Chuenisbärgli etabliert. Seine Kombination aus roher Kraft und technischer Präzision macht ihn auf diesem Gelände nahezu unschlagbar.</p><p>\"Adelboden ist speziell\", sagte Odermatt zu Beginn dieser Saison. \"Die Atmosphäre, die Fans, die Strecke selbst - alles kommt zusammen. Das gibt mir zusätzliche Energie.\"</p><h2>Die Herausforderer</h2><p>Der Norweger <strong>Henrik Kristoffersen</strong> bleibt der wahrscheinlichste Herausforderer für Odermatt. Der erfahrene Techniker ist diese Saison in ausgezeichneter Form und hat bereits mehrere Podiumsplätze gesichert. Sein aggressiver, angriffslustiger Stil passt zu den steilen Passagen des Chuenisbärgli.</p><p>Achten Sie auch auf <strong>Loic Meillard</strong>, Odermatts Schweizer Teamkollegen, der diese Saison Glanzmomente gezeigt hat, und den Österreicher <strong>Manuel Feller</strong>, der bei technischen Rennen immer gefährlich ist.</p><p>Eine interessante Geschichte umgibt <strong>Lucas Pinheiro Braathen</strong>, der jetzt unter brasilianischer Flagge fährt. Der ehemalige norwegische Star sorgte mit seiner Rückkehr in den Wettkampf für Aufsehen und könnte ein Faktor sein, wenn die Bedingungen seinem aggressiven Ansatz entsprechen.</p><h2>Die Strecke</h2><p>Das Chuenisbärgli ist berüchtigt für seinen steilen Einstieg, gefolgt von einer Serie anspruchsvoller Kurven, die sowohl Mut als auch Präzision erfordern. Die Strecke überwindet 420 Höhenmeter auf 1.510 Metern Länge mit einem durchschnittlichen Gefälle, das selbst die Beine der besten Skifahrer auf die Probe stellt.</p><p>Tausende von Fans werden die Strecke säumen und die berühmte \"Adelboden-Atmosphäre\" schaffen, die diesen Halt zu einem der meisterwarteten im Weltcup-Kalender macht.</p><h2>Rennprogramm</h2><ul><li><strong>Samstag, 11. Januar</strong>: Riesenslalom - 1. Lauf um 10:30 MEZ, 2. Lauf um 13:30 MEZ</li><li><strong>Sonntag, 12. Januar</strong>: Slalom - 1. Lauf um 10:30 MEZ, 2. Lauf um 13:30 MEZ</li></ul><p>Verfolgen Sie alle Action live auf Neve26 mit Echtzeit-Updates und Benachrichtigungen.</p>",

        "fr": "<p>Ce samedi 11 janvier, les meilleurs slalomeurs géants du monde convergent vers le village suisse d''Adelboden pour la 68e édition de la légendaire course du Chuenisbärgli. Cette piste raide et exigeante est devenue synonyme d''excellence technique et de courses dramatiques.</p><h2>La Domination d''Odermatt</h2><p>La sensation suisse <strong>Marco Odermatt</strong> arrive à Adelboden en grand favori. Le champion du monde en titre du classement général a remporté les trois dernières éditions ici, s''établissant comme le roi incontesté du Chuenisbärgli. Sa combinaison de puissance brute et de précision technique le rend presque imbattable sur ce terrain.</p><p>\"Adelboden est spécial\", a déclaré Odermatt en début de saison. \"L''atmosphère, les fans, le parcours lui-même - tout se combine. Ça me donne une énergie supplémentaire.\"</p><h2>Les Challengers</h2><p>Le Norvégien <strong>Henrik Kristoffersen</strong> reste le plus susceptible de défier Odermatt. Le technicien vétéran est en excellente forme cette saison, avec plusieurs podiums déjà assurés. Son style agressif et offensif convient aux pentes raides du Chuenisbärgli.</p><p>Surveillez également <strong>Loic Meillard</strong>, le coéquipier suisse d''Odermatt qui a montré des éclairs de génie cette saison, et l''Autrichien <strong>Manuel Feller</strong>, toujours dangereux dans les épreuves techniques.</p><p>Une intrigue entoure <strong>Lucas Pinheiro Braathen</strong>, qui court maintenant sous le drapeau brésilien. L''ancienne star norvégienne a fait sensation avec son retour en compétition et pourrait être un facteur si les conditions conviennent à son approche agressive.</p><h2>Le Parcours</h2><p>Le Chuenisbärgli est réputé pour sa section d''ouverture raide, suivie d''une série de virages exigeants qui nécessitent à la fois courage et précision. Le parcours descend de 420 mètres sur ses 1 510 mètres de longueur, avec une pente moyenne qui met à l''épreuve même les jambes des meilleurs skieurs.</p><p>Des milliers de fans devraient border le parcours, créant la fameuse \"atmosphère d''Adelboden\" qui fait de cette étape l''une des plus attendues du calendrier de la Coupe du Monde.</p><h2>Programme des Courses</h2><ul><li><strong>Samedi 11 janvier</strong>: Slalom Géant - Manche 1 à 10h30 CET, Manche 2 à 13h30 CET</li><li><strong>Dimanche 12 janvier</strong>: Slalom - Manche 1 à 10h30 CET, Manche 2 à 13h30 CET</li></ul><p>Suivez toute l''action en direct sur Neve26 avec des mises à jour et notifications en temps réel.</p>",

        "it": "<p>Sabato 11 gennaio, i migliori slalomisti giganti del mondo si ritrovano nel villaggio svizzero di Adelboden per la 68ª edizione della leggendaria gara del Chuenisbärgli. La pista ripida ed esigente è diventata sinonimo di eccellenza tecnica e gare emozionanti.</p><h2>Il Dominio di Odermatt</h2><p>La sensazione svizzera <strong>Marco Odermatt</strong> arriva ad Adelboden come grande favorito. Il campione del mondo in carica della classifica generale ha vinto le ultime tre edizioni qui, affermandosi come re indiscusso del Chuenisbärgli. La sua combinazione di potenza pura e precisione tecnica lo rende quasi imbattibile su questo terreno.</p><p>\"Adelboden è speciale\", ha detto Odermatt all''inizio di questa stagione. \"L''atmosfera, i tifosi, il percorso stesso - tutto si combina. Mi dà energia extra.\"</p><h2>Gli Sfidanti</h2><p>Il norvegese <strong>Henrik Kristoffersen</strong> rimane il più probabile sfidante di Odermatt. Il tecnico veterano è in ottima forma questa stagione, con diversi podi già conquistati. Il suo stile aggressivo e d''attacco si adatta alle ripide pendenze del Chuenisbärgli.</p><p>Da tenere d''occhio anche <strong>Loic Meillard</strong>, il compagno di squadra svizzero di Odermatt che ha mostrato lampi di genialità questa stagione, e l''austriaco <strong>Manuel Feller</strong>, sempre pericoloso nelle prove tecniche.</p><p>Una storia intrigante circonda <strong>Lucas Pinheiro Braathen</strong>, che ora gareggia sotto la bandiera brasiliana. L''ex stella norvegese ha fatto scalpore con il suo ritorno alle competizioni e potrebbe essere un fattore se le condizioni si adattano al suo approccio aggressivo.</p><h2>Il Percorso</h2><p>Il Chuenisbärgli è famoso per la sua sezione d''apertura ripida, seguita da una serie di curve impegnative che richiedono sia coraggio che precisione. Il percorso scende di 420 metri sui suoi 1.510 metri di lunghezza, con una pendenza media che mette alla prova le gambe anche dei migliori sciatori.</p><p>Migliaia di tifosi sono attesi lungo il percorso, creando la famosa \"atmosfera di Adelboden\" che rende questa una delle tappe più attese del calendario della Coppa del Mondo.</p><h2>Programma Gare</h2><ul><li><strong>Sabato 11 gennaio</strong>: Slalom Gigante - Manche 1 alle 10:30 CET, Manche 2 alle 13:30 CET</li><li><strong>Domenica 12 gennaio</strong>: Slalom - Manche 1 alle 10:30 CET, Manche 2 alle 13:30 CET</li></ul><p>Segui tutta l''azione in diretta su Neve26 con aggiornamenti e notifiche in tempo reale.</p>",

        "es": "<p>Este sábado 11 de enero, los mejores esquiadores de slalom gigante del mundo llegan a la aldea suiza de Adelboden para la 68ª edición de la legendaria carrera del Chuenisbärgli. La pista empinada y exigente se ha convertido en sinónimo de excelencia técnica y carreras dramáticas.</p><h2>El Dominio de Odermatt</h2><p>La sensación suiza <strong>Marco Odermatt</strong> llega a Adelboden como gran favorito. El actual campeón del mundo de la general ha ganado las últimas tres ediciones aquí, estableciéndose como el rey indiscutible del Chuenisbärgli. Su combinación de potencia bruta y precisión técnica lo hace casi imbatible en este terreno.</p><p>\"Adelboden es especial\", dijo Odermatt a principios de esta temporada. \"La atmósfera, los fans, el circuito en sí - todo se combina. Me da energía extra.\"</p><h2>Los Rivales</h2><p>El noruego <strong>Henrik Kristoffersen</strong> sigue siendo el más probable para desafiar a Odermatt. El técnico veterano ha estado en excelente forma esta temporada, con múltiples podios ya asegurados. Su estilo agresivo y de ataque se adapta a las pendientes pronunciadas del Chuenisbärgli.</p><p>También hay que estar atentos a <strong>Loic Meillard</strong>, compañero suizo de Odermatt que ha mostrado destellos de brillantez esta temporada, y al austriaco <strong>Manuel Feller</strong>, siempre peligroso en pruebas técnicas.</p><p>Una historia intrigante rodea a <strong>Lucas Pinheiro Braathen</strong>, que ahora compite bajo bandera brasileña. La antigua estrella noruega causó sensación con su regreso a la competición y podría ser un factor si las condiciones favorecen su enfoque agresivo.</p><h2>El Circuito</h2><p>El Chuenisbärgli es famoso por su empinada sección inicial, seguida de una serie de curvas exigentes que requieren tanto valentía como precisión. El circuito desciende 420 metros en sus 1.510 metros de longitud, con una pendiente media que pone a prueba las piernas incluso de los mejores esquiadores.</p><p>Se esperan miles de aficionados a lo largo del circuito, creando la famosa \"atmósfera de Adelboden\" que convierte esta parada en una de las más esperadas del calendario de la Copa del Mundo.</p><h2>Programa de Carreras</h2><ul><li><strong>Sábado 11 de enero</strong>: Slalom Gigante - Manga 1 a las 10:30 CET, Manga 2 a las 13:30 CET</li><li><strong>Domingo 12 de enero</strong>: Slalom - Manga 1 a las 10:30 CET, Manga 2 a las 13:30 CET</li></ul><p>Sigue toda la acción en directo en Neve26 con actualizaciones y notificaciones en tiempo real.</p>",

        "pt": "<p>Neste sábado, 11 de janeiro, os melhores esquiadores de slalom gigante do mundo chegam à vila suíça de Adelboden para a 68ª edição da lendária corrida do Chuenisbärgli. A pista íngreme e exigente tornou-se sinônimo de excelência técnica e corridas dramáticas.</p><h2>A Dominância de Odermatt</h2><p>A sensação suíça <strong>Marco Odermatt</strong> chega a Adelboden como grande favorito. O atual campeão mundial geral venceu as últimas três edições aqui, estabelecendo-se como o rei indiscutível do Chuenisbärgli. Sua combinação de força bruta e precisão técnica o torna quase imbatível neste terreno.</p><p>\"Adelboden é especial\", disse Odermatt no início desta temporada. \"A atmosfera, os fãs, o percurso em si - tudo se combina. Isso me dá energia extra.\"</p><h2>Os Desafiantes</h2><p>O norueguês <strong>Henrik Kristoffersen</strong> continua sendo o mais provável a desafiar Odermatt. O técnico veterano está em excelente forma nesta temporada, com múltiplos pódios já garantidos. Seu estilo agressivo e de ataque se adapta às encostas íngremes do Chuenisbärgli.</p><p>Fique de olho também em <strong>Loic Meillard</strong>, companheiro suíço de Odermatt que mostrou lampejos de brilhantismo nesta temporada, e no austríaco <strong>Manuel Feller</strong>, sempre perigoso em provas técnicas.</p><p>Uma história intrigante envolve <strong>Lucas Pinheiro Braathen</strong>, que agora compete sob a bandeira brasileira. A antiga estrela norueguesa causou sensação com seu retorno às competições e pode ser um fator se as condições favorecerem sua abordagem agressiva.</p><h2>O Percurso</h2><p>O Chuenisbärgli é famoso por sua seção inicial íngreme, seguida por uma série de curvas exigentes que requerem tanto coragem quanto precisão. O percurso desce 420 metros em seus 1.510 metros de comprimento, com uma inclinação média que testa as pernas até dos melhores esquiadores.</p><p>Milhares de fãs são esperados ao longo do percurso, criando a famosa \"atmosfera de Adelboden\" que torna esta uma das paradas mais aguardadas do calendário da Copa do Mundo.</p><h2>Programação das Corridas</h2><ul><li><strong>Sábado, 11 de janeiro</strong>: Slalom Gigante - Manga 1 às 10:30 CET, Manga 2 às 13:30 CET</li><li><strong>Domingo, 12 de janeiro</strong>: Slalom - Manga 1 às 10:30 CET, Manga 2 às 13:30 CET</li></ul><p>Acompanhe toda a ação ao vivo no Neve26 com atualizações e notificações em tempo real.</p>",

        "nl": "<p>Aanstaande zaterdag 11 januari komen ''s werelds beste reuzenslalomskiërs samen in het Zwitserse dorp Adelboden voor de 68e editie van de legendarische Chuenisbärgli-race. De steile, veeleisende piste is synoniem geworden met technische excellentie en dramatische races.</p><h2>Odermatts Dominantie</h2><p>Het Zwitserse fenomeen <strong>Marco Odermatt</strong> arriveert in Adelboden als torenhoge favoriet. De regerend algemeen wereldbekerkampioen heeft de laatste drie edities hier gewonnen en zich gevestigd als de onbetwiste koning van de Chuenisbärgli. Zijn combinatie van pure kracht en technische precisie maakt hem bijna onverslaanbaar op dit terrein.</p><p>\"Adelboden is speciaal,\" zei Odermatt eerder dit seizoen. \"De sfeer, de fans, de piste zelf - alles komt samen. Het geeft me extra energie.\"</p><h2>De Uitdagers</h2><p>De Noor <strong>Henrik Kristoffersen</strong> blijft de meest waarschijnlijke uitdager van Odermatt. De ervaren technicus is dit seizoen in uitstekende vorm, met al meerdere podiumplaatsen. Zijn agressieve, aanvallende stijl past bij de steile hellingen van de Chuenisbärgli.</p><p>Let ook op <strong>Loic Meillard</strong>, Odermatts Zwitserse teamgenoot die dit seizoen glimpen van genialiteit heeft getoond, en de Oostenrijker <strong>Manuel Feller</strong>, altijd gevaarlijk in technische wedstrijden.</p><p>Een intrigerend verhaal omringt <strong>Lucas Pinheiro Braathen</strong>, die nu onder Braziliaanse vlag racet. De voormalige Noorse ster maakte furore met zijn terugkeer naar de competitie en zou een factor kunnen zijn als de omstandigheden passen bij zijn agressieve aanpak.</p><h2>De Piste</h2><p>De Chuenisbärgli staat bekend om zijn steile openingssectie, gevolgd door een reeks veeleisende bochten die zowel moed als precisie vereisen. De piste daalt 420 meter over zijn 1.510 meter lengte, met een gemiddelde helling die zelfs de benen van de beste skiërs op de proef stelt.</p><p>Duizenden fans worden verwacht langs de piste, wat de beroemde \"Adelboden-sfeer\" creëert die deze stop tot een van de meest verwachte van de wereldbekerkalender maakt.</p><h2>Raceprogramma</h2><ul><li><strong>Zaterdag 11 januari</strong>: Reuzenslalom - Run 1 om 10:30 CET, Run 2 om 13:30 CET</li><li><strong>Zondag 12 januari</strong>: Slalom - Run 1 om 10:30 CET, Run 2 om 13:30 CET</li></ul><p>Volg alle actie live op Neve26 met realtime updates en meldingen.</p>",

        "ar": "<p>يوم السبت 11 يناير، يتجمع أفضل متزلجي التزلج العملاق في العالم في قرية أدلبودن السويسرية للنسخة الـ68 من سباق شوينيسبيرجلي الأسطوري. أصبح هذا المنحدر الحاد والمتطلب مرادفاً للتميز التقني والسباقات المثيرة.</p><h2>هيمنة أوديرمات</h2><p>يصل النجم السويسري <strong>ماركو أوديرمات</strong> إلى أدلبودن كمرشح أول بامتياز. فاز بطل كأس العالم الحالي بالنسخ الثلاث الأخيرة هنا، مثبتاً نفسه كملك بلا منازع لشوينيسبيرجلي. مزيجه من القوة الخام والدقة التقنية يجعله شبه لا يُهزم على هذه الأرضية.</p><p>\"أدلبودن مميز،\" قال أوديرمات في وقت سابق من هذا الموسم. \"الأجواء، الجماهير، المسار نفسه - كل شيء يجتمع. يمنحني طاقة إضافية.\"</p><h2>المنافسون</h2><p>يبقى النرويجي <strong>هنريك كريستوفرسن</strong> الأكثر احتمالاً لتحدي أوديرمات. المتزلج التقني المخضرم في حالة ممتازة هذا الموسم، مع عدة منصات تتويج محققة بالفعل. أسلوبه الهجومي العدواني يناسب المنحدرات الحادة لشوينيسبيرجلي.</p><p>راقب أيضاً <strong>لويك ميلارد</strong>، زميل أوديرمات السويسري الذي أظهر ومضات من العبقرية هذا الموسم، والنمساوي <strong>مانويل فيلر</strong>، الخطير دائماً في الفعاليات التقنية.</p><p>قصة مثيرة تحيط بـ<strong>لوكاس بينيرو براثن</strong>، الذي يتسابق الآن تحت العلم البرازيلي. أحدث النجم النرويجي السابق ضجة بعودته للمنافسة وقد يكون عاملاً مؤثراً إذا ناسبت الظروف نهجه الهجومي.</p><h2>المسار</h2><p>يشتهر شوينيسبيرجلي بقسمه الافتتاحي الحاد، يليه سلسلة من المنعطفات المتطلبة التي تحتاج للشجاعة والدقة معاً. ينحدر المسار 420 متراً على طوله البالغ 1,510 متر، بميل متوسط يختبر أرجل حتى أفضل المتزلجين.</p><p>من المتوقع أن يصطف آلاف المشجعين على طول المسار، خالقين \"أجواء أدلبودن\" الشهيرة التي تجعل هذه المحطة واحدة من أكثر المحطات انتظاراً في تقويم كأس العالم.</p><h2>جدول السباقات</h2><ul><li><strong>السبت 11 يناير</strong>: التزلج العملاق - الجولة 1 الساعة 10:30 بتوقيت وسط أوروبا، الجولة 2 الساعة 13:30</li><li><strong>الأحد 12 يناير</strong>: التزلج المتعرج - الجولة 1 الساعة 10:30 بتوقيت وسط أوروبا، الجولة 2 الساعة 13:30</li></ul><p>تابع كل الأحداث مباشرة على Neve26 مع التحديثات والإشعارات الفورية.</p>",

        "ja": "<p>1月11日土曜日、世界最高の大回転スキーヤーたちがスイスの村アーデルボーデンに集結し、伝説のチュエニスベルグリレース第68回大会が開催されます。この急斜面で要求の厳しいコースは、技術的卓越性とドラマチックなレースの代名詞となっています。</p><h2>オーデルマットの支配</h2><p>スイスのセンセーション、<strong>マルコ・オーデルマット</strong>が圧倒的な優勝候補としてアーデルボーデンに到着します。現総合ワールドカップチャンピオンは、ここで過去3大会連続優勝を果たし、チュエニスベルグリの紛れもない王者としての地位を確立しています。生の力と技術的精度の組み合わせにより、この地形では彼はほぼ無敵です。</p><p>「アーデルボーデンは特別だ」とオーデルマットは今シーズン初めに語りました。「雰囲気、ファン、コースそのもの - すべてが一体となる。それが僕に余分なエネルギーを与えてくれる。」</p><h2>挑戦者たち</h2><p>ノルウェーの<strong>ヘンリク・クリストッフェルセン</strong>は、オーデルマットに挑戦する最有力候補です。このベテラン技術者は今シーズン素晴らしい調子で、すでに複数の表彰台を確保しています。彼の攻撃的なスタイルは、チュエニスベルグリの急斜面に適しています。</p><p>また、今シーズン閃きを見せているオーデルマットのスイス人チームメイト<strong>ロイック・メイヤール</strong>や、技術系種目で常に危険な存在であるオーストリアの<strong>マヌエル・フェラー</strong>にも注目です。</p><p>興味深いストーリーは、現在ブラジル国旗の下でレースをしている<strong>ルーカス・ピニェイロ・ブラーセン</strong>を取り巻いています。この元ノルウェーのスターは競技復帰で話題を呼び、条件が彼の攻撃的なアプローチに合えば、ファクターになる可能性があります。</p><h2>コース</h2><p>チュエニスベルグリは、急な開始セクションで有名で、その後に勇気と精度の両方を必要とする一連の厳しいターンが続きます。コースは1,510メートルの長さで420メートル下降し、最高のスキーヤーの脚でさえ試される平均勾配を持っています。</p><p>数千人のファンがコース沿いに並び、ワールドカップカレンダーで最も期待される停車地の一つとなる有名な「アーデルボーデンの雰囲気」を作り出すことが期待されています。</p><h2>レーススケジュール</h2><ul><li><strong>1月11日土曜日</strong>：大回転 - 第1ラン 10:30 CET、第2ラン 13:30 CET</li><li><strong>1月12日日曜日</strong>：回転 - 第1ラン 10:30 CET、第2ラン 13:30 CET</li></ul><p>Neve26でリアルタイムの更新と通知とともに、すべてのアクションをライブでフォローしてください。</p>",

        "zh": "<p>1月11日星期六，世界顶级大回转滑雪选手将齐聚瑞士阿德尔博登村，参加第68届传奇的楚尼斯贝格利比赛。这条陡峭且极具挑战性的赛道已成为技术卓越和精彩比赛的代名词。</p><h2>奥德马特的统治</h2><p>瑞士明星<strong>马尔科·奥德马特</strong>作为压倒性的夺冠热门抵达阿德尔博登。这位现任世界杯总冠军已连续赢得这里最近三届比赛，确立了自己作为楚尼斯贝格利无可争议之王的地位。他将原始力量与技术精准完美结合，在这种地形上几乎无人能敌。</p><p>"阿德尔博登很特别，"奥德马特在本赛季早些时候说道。"气氛、粉丝、赛道本身——一切都融为一体。这给了我额外的能量。"</p><h2>挑战者</h2><p>挪威选手<strong>亨里克·克里斯托弗森</strong>仍然是最有可能挑战奥德马特的人。这位经验丰富的技术型选手本赛季状态出色，已经获得多次领奖台成绩。他激进的进攻风格非常适合楚尼斯贝格利的陡坡。</p><p>同样值得关注的还有<strong>洛伊克·梅拉德</strong>，奥德马特的瑞士队友，本赛季展现出了闪光时刻，以及奥地利的<strong>曼努埃尔·费勒</strong>，他在技术项目中总是很危险。</p><p>一个引人入胜的故事围绕着<strong>卢卡斯·皮涅罗·布拉森</strong>，他现在代表巴西参赛。这位前挪威明星以复出引起轰动，如果条件适合他的激进风格，他可能成为关键因素。</p><h2>赛道</h2><p>楚尼斯贝格利以其陡峭的开始部分而闻名，随后是一系列需要勇气和精准度的高难度弯道。赛道在1510米的长度内下降420米，平均坡度即使对最优秀滑雪选手的双腿也是严峻考验。</p><p>预计将有数千名粉丝沿着赛道观看，创造出著名的"阿德尔博登氛围"，使这里成为世界杯日历上最受期待的站点之一。</p><h2>比赛日程</h2><ul><li><strong>1月11日星期六</strong>：大回转 - 第一轮 10:30 CET，第二轮 13:30 CET</li><li><strong>1月12日星期日</strong>：回转 - 第一轮 10:30 CET，第二轮 13:30 CET</li></ul><p>在Neve26上实时关注所有赛事动态，获取即时更新和通知。</p>",

        "ko": "<p>1월 11일 토요일, 세계 최고의 대회전 스키 선수들이 스위스 아델보덴 마을에 모여 전설적인 추에니스베르글리 레이스 68회 대회를 펼칩니다. 가파르고 까다로운 이 코스는 기술적 탁월함과 극적인 레이스의 대명사가 되었습니다.</p><h2>오더마트의 지배</h2><p>스위스의 센세이션 <strong>마르코 오더마트</strong>가 압도적인 우승 후보로 아델보덴에 도착합니다. 현 종합 월드컵 챔피언은 이곳에서 최근 3회 연속 우승을 차지하며 추에니스베르글리의 확실한 왕자로 자리매김했습니다. 순수한 파워와 기술적 정밀함의 조합으로 그는 이 지형에서 거의 무적입니다.</p><p>"아델보덴은 특별해요," 오더마트는 이번 시즌 초에 말했습니다. "분위기, 팬들, 코스 자체 - 모든 것이 하나로 합쳐져요. 그게 저에게 추가 에너지를 줍니다."</p><h2>도전자들</h2><p>노르웨이의 <strong>헨리크 크리스토퍼센</strong>이 오더마트에 도전할 가장 유력한 후보로 남아 있습니다. 이 베테랑 테크니션은 이번 시즌 훌륭한 컨디션을 유지하며 이미 여러 차례 포디움에 올랐습니다. 그의 공격적인 스타일은 추에니스베르글리의 가파른 경사에 적합합니다.</p><p>또한 이번 시즌 빛나는 순간을 보여준 오더마트의 스위스 팀메이트 <strong>로익 메이야르</strong>와 기술 종목에서 항상 위험한 오스트리아의 <strong>마누엘 펠러</strong>도 주목하세요.</p><p>흥미로운 스토리는 현재 브라질 국기 아래 경쟁하는 <strong>루카스 피녜이로 브라텐</strong>을 둘러싸고 있습니다. 전 노르웨이 스타는 복귀로 화제를 모았으며, 조건이 그의 공격적인 접근 방식에 맞는다면 변수가 될 수 있습니다.</p><h2>코스</h2><p>추에니스베르글리는 가파른 시작 구간으로 유명하며, 이어서 용기와 정밀함을 모두 요구하는 일련의 까다로운 턴이 이어집니다. 코스는 1,510미터 길이에서 420미터를 하강하며, 평균 경사도는 최고의 스키 선수들의 다리까지도 시험합니다.</p><p>수천 명의 팬들이 코스를 따라 줄지어 서서, 이 정류장을 월드컵 캘린더에서 가장 기대되는 곳 중 하나로 만드는 유명한 "아델보덴 분위기"를 만들어낼 것으로 예상됩니다.</p><h2>경기 일정</h2><ul><li><strong>1월 11일 토요일</strong>: 대회전 - 1차 런 10:30 CET, 2차 런 13:30 CET</li><li><strong>1월 12일 일요일</strong>: 회전 - 1차 런 10:30 CET, 2차 런 13:30 CET</li></ul><p>Neve26에서 실시간 업데이트와 알림으로 모든 액션을 라이브로 팔로우하세요.</p>"
    }'::jsonb,

    -- CATEGORY & SPORT
    'alpine-skiing',
    'ALP',

    -- ATHLETES
    ARRAY['marco-odermatt', 'henrik-kristoffersen', 'loic-meillard', 'manuel-feller', 'lucas-pinheiro-braathen'],

    -- VENUE
    'Chuenisbärgli',
    'Adelboden',

    -- META DESCRIPTIONS (11 languages)
    '{
        "en": "Preview of the 2026 Adelboden Giant Slalom. Marco Odermatt seeks fourth consecutive victory on the legendary Chuenisbärgli course.",
        "de": "Vorschau auf den Adelboden Riesenslalom 2026. Marco Odermatt strebt seinen vierten Sieg in Folge auf der legendären Chuenisbärgli-Strecke an.",
        "fr": "Aperçu du Slalom Géant d''Adelboden 2026. Marco Odermatt vise une quatrième victoire consécutive sur le légendaire Chuenisbärgli.",
        "it": "Anteprima dello Slalom Gigante di Adelboden 2026. Marco Odermatt punta alla quarta vittoria consecutiva sul leggendario Chuenisbärgli.",
        "es": "Vista previa del Slalom Gigante de Adelboden 2026. Marco Odermatt busca su cuarta victoria consecutiva en el legendario Chuenisbärgli.",
        "pt": "Prévia do Slalom Gigante de Adelboden 2026. Marco Odermatt busca quarta vitória consecutiva no lendário Chuenisbärgli.",
        "nl": "Vooruitblik op de Adelboden Reuzenslalom 2026. Marco Odermatt mikt op vierde opeenvolgende overwinning op de legendarische Chuenisbärgli.",
        "ar": "معاينة سباق التزلج العملاق في أدلبودن 2026. أوديرمات يسعى للفوز الرابع على التوالي على منحدر شوينيسبيرجلي الأسطوري.",
        "ja": "2026年アーデルボーデン大回転プレビュー。オーデルマットが伝説のチュエニスベルグリで4連勝を狙う。",
        "zh": "2026年阿德尔博登大回转预告。奥德马特在传奇的楚尼斯贝格利赛道寻求四连胜。",
        "ko": "2026 아델보덴 대회전 프리뷰. 오더마트가 전설적인 추에니스베르글리에서 4연승을 노린다."
    }'::jsonb,

    -- STRUCTURED DATA (JSON-LD)
    '{
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Adelboden Giant Slalom Preview: Odermatt Eyes Fourth Consecutive Victory",
        "datePublished": "2026-01-08T12:00:00+01:00",
        "dateModified": "2026-01-08T12:00:00+01:00",
        "author": {
            "@type": "Organization",
            "name": "Neve26"
        },
        "publisher": {
            "@type": "Organization",
            "name": "Neve26",
            "logo": {
                "@type": "ImageObject",
                "url": "https://neve26.com/logo-512.png"
            }
        },
        "about": [
            {
                "@type": "SportsEvent",
                "name": "FIS World Cup Giant Slalom Adelboden",
                "startDate": "2026-01-11",
                "location": {
                    "@type": "Place",
                    "name": "Chuenisbärgli",
                    "address": {
                        "@type": "PostalAddress",
                        "addressLocality": "Adelboden",
                        "addressCountry": "CH"
                    }
                }
            }
        ]
    }'::jsonb,

    -- STATUS & PUBLISHING
    'published',
    '2026-01-08 12:00:00+01',

    -- SOURCE
    'manual'
);
