-- Migration 007: Nordic Combined Sport Explainer
-- Run with: docker exec -i bronze-db psql -U postgres -d neve26 -f - < migrations/007_nordic_combined.sql

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type) VALUES

-- Nordic Combined Explainer
('nordic-combined-ultimate-winter-sport',
-- Title (11 languages)
'{
  "en": "Nordic Combined: The Ultimate Winter Sport",
  "de": "Nordische Kombination: Der ultimative Wintersport",
  "fr": "Combiné nordique : Le sport d''hiver ultime",
  "it": "Combinata nordica: Lo sport invernale definitivo",
  "es": "Combinada nórdica: El deporte de invierno definitivo",
  "pt": "Combinado nórdico: O esporte de inverno definitivo",
  "nl": "Noordse combinatie: De ultieme wintersport",
  "ar": "الجمع الشمالي: الرياضة الشتوية المطلقة",
  "ja": "ノルディック複合：究極のウィンタースポーツ",
  "zh": "北欧两项：终极冬季运动",
  "ko": "노르딕 복합: 궁극의 겨울 스포츠"
}'::jsonb,

-- Excerpt
'{
  "en": "Nordic combined tests ski jumping and cross-country skiing in one event. Learn how athletes master two very different disciplines.",
  "de": "Die Nordische Kombination testet Skispringen und Langlauf in einem Wettkampf. Erfahren Sie, wie Athleten zwei sehr unterschiedliche Disziplinen meistern.",
  "fr": "Le combiné nordique teste le saut à ski et le ski de fond en une seule épreuve. Découvrez comment les athlètes maîtrisent deux disciplines très différentes.",
  "it": "La combinata nordica testa il salto con gli sci e lo sci di fondo in un unico evento. Scopri come gli atleti padroneggiano due discipline molto diverse.",
  "es": "La combinada nórdica prueba el salto de esquí y el esquí de fondo en un solo evento. Aprende cómo los atletas dominan dos disciplinas muy diferentes.",
  "pt": "O combinado nórdico testa salto de esqui e esqui cross-country em um único evento. Aprenda como os atletas dominam duas disciplinas muito diferentes.",
  "nl": "Noordse combinatie test schansspringen en langlaufen in één evenement. Leer hoe atleten twee zeer verschillende disciplines beheersen.",
  "ar": "يختبر الجمع الشمالي القفز على الجليد والتزلج الريفي في حدث واحد. تعلم كيف يتقن الرياضيون تخصصين مختلفين جدًا.",
  "ja": "ノルディック複合はスキージャンプとクロスカントリースキーを1つのイベントでテストします。アスリートがどのように2つの異なる競技をマスターするかを学びましょう。",
  "zh": "北欧两项在一项赛事中测试跳台滑雪和越野滑雪。了解运动员如何掌握两项截然不同的项目。",
  "ko": "노르딕 복합은 스키점프와 크로스컨트리 스키를 한 종목에서 테스트합니다. 선수들이 두 가지 매우 다른 종목을 어떻게 마스터하는지 알아보세요."
}'::jsonb,

-- Content (11 languages)
'{
  "en": "<article><h2>What is Nordic Combined?</h2><p>Nordic combined is a winter sport that combines two disciplines: <a href=\"/ski-jumping-scoring-technique/\">ski jumping</a> and <a href=\"/cross-country-skiing-techniques/\">cross-country skiing</a>. Athletes must excel at both to compete at the highest level. This makes nordic combined one of the most demanding winter sports.</p><h2>Competition Format</h2><p>The competition has two parts. First, athletes complete the ski jumping portion. The jumping results determine the starting order for the cross-country race. Better jumpers start first. This system is called the Gundersen method.</p><h3>The Gundersen Method</h3><p>Points from ski jumping convert to time advantages. For every point behind the leader, an athlete starts later in the cross-country race. The first person to cross the finish line wins. This creates exciting finishes where anything can happen.</p><h2>Event Types</h2><h3>Individual Normal Hill</h3><p>Athletes jump from a normal hill (around 98 meters). Then they race 10 kilometers cross-country. This is the classic format.</p><h3>Individual Large Hill</h3><p>Athletes jump from a large hill (around 128 meters). The cross-country race is also 10 kilometers. Bigger hills mean more risk and reward.</p><h3>Team Event</h3><p>Four athletes per team. Each jumps once from the large hill. Then the team completes a 4x5 kilometer relay. Team tactics add another layer of strategy.</p><h2>Skills Required</h2><p>Nordic combined athletes need very different abilities. Ski jumping requires explosive power, balance, and courage. Cross-country skiing demands endurance, technique, and mental strength. Few athletes excel at both naturally.</p><h3>Training Challenges</h3><p>Athletes must split their training between two sports. Too much jumping practice reduces skiing fitness. Too much skiing can affect jumping technique. Finding the right balance is key to success.</p><h2>Famous Nordic Combined Athletes</h2><p>The sport has produced remarkable all-around athletes. Norway, Germany, and Austria have traditionally dominated. Athletes like Jarl Magnus Riiber from Norway have pushed the sport to new levels. Japanese athlete Akito Watabe has also been a consistent force.</p><h2>Where to Watch</h2><p>Major competitions happen at famous venues. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> in Oslo hosts prestigious events. Seefeld in Austria is another key location. The World Cup circuit visits venues across Europe and Asia.</p><h2>Why Nordic Combined Matters</h2><p>This sport celebrates versatility. Athletes cannot specialize in just one thing. They must be complete winter sports athletes. This makes champions of nordic combined truly special competitors.</p></article>",

  "de": "<article><h2>Was ist die Nordische Kombination?</h2><p>Die Nordische Kombination ist ein Wintersport, der zwei Disziplinen vereint: <a href=\"/ski-jumping-scoring-technique/\">Skispringen</a> und <a href=\"/cross-country-skiing-techniques/\">Langlauf</a>. Athleten müssen in beiden Bereichen hervorragend sein, um auf höchstem Niveau zu konkurrieren. Das macht die Nordische Kombination zu einem der anspruchsvollsten Wintersportarten.</p><h2>Wettkampfformat</h2><p>Der Wettkampf hat zwei Teile. Zuerst absolvieren die Athleten den Skisprungteil. Die Sprungergebnisse bestimmen die Startreihenfolge für das Langlaufrennen. Bessere Springer starten zuerst. Dieses System heißt Gundersen-Methode.</p><h3>Die Gundersen-Methode</h3><p>Punkte aus dem Skispringen werden in Zeitvorteile umgerechnet. Für jeden Punkt Rückstand auf den Führenden startet ein Athlet später im Langlaufrennen. Wer zuerst die Ziellinie überquert, gewinnt. Das schafft spannende Zieleinläufe.</p><h2>Wettkampfarten</h2><h3>Einzel Normalschanze</h3><p>Athleten springen von einer Normalschanze (etwa 98 Meter). Dann laufen sie 10 Kilometer Langlauf. Das ist das klassische Format.</p><h3>Einzel Großschanze</h3><p>Athleten springen von einer Großschanze (etwa 128 Meter). Das Langlaufrennen ist ebenfalls 10 Kilometer. Größere Schanzen bedeuten mehr Risiko und Belohnung.</p><h3>Teamwettkampf</h3><p>Vier Athleten pro Team. Jeder springt einmal von der Großschanze. Dann absolviert das Team eine 4x5 Kilometer Staffel. Teamtaktik fügt eine weitere strategische Ebene hinzu.</p><h2>Erforderliche Fähigkeiten</h2><p>Nordische Kombinierer brauchen sehr unterschiedliche Fähigkeiten. Skispringen erfordert explosive Kraft, Balance und Mut. Langlauf verlangt Ausdauer, Technik und mentale Stärke. Wenige Athleten sind in beidem von Natur aus hervorragend.</p><h2>Berühmte Nordische Kombinierer</h2><p>Der Sport hat bemerkenswerte Allrounder hervorgebracht. Norwegen, Deutschland und Österreich haben traditionell dominiert. Athleten wie Jarl Magnus Riiber aus Norwegen haben den Sport auf neue Ebenen gehoben.</p><h2>Wo man zusehen kann</h2><p>Große Wettkämpfe finden an berühmten Austragungsorten statt. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> in Oslo veranstaltet prestigeträchtige Events. Seefeld in Österreich ist ein weiterer wichtiger Ort.</p></article>",

  "fr": "<article><h2>Qu''est-ce que le combiné nordique?</h2><p>Le combiné nordique est un sport d''hiver qui combine deux disciplines: <a href=\"/ski-jumping-scoring-technique/\">le saut à ski</a> et <a href=\"/cross-country-skiing-techniques/\">le ski de fond</a>. Les athlètes doivent exceller dans les deux pour concourir au plus haut niveau. Cela fait du combiné nordique l''un des sports d''hiver les plus exigeants.</p><h2>Format de compétition</h2><p>La compétition comprend deux parties. D''abord, les athlètes effectuent la partie saut à ski. Les résultats du saut déterminent l''ordre de départ pour la course de ski de fond. Les meilleurs sauteurs partent en premier. Ce système s''appelle la méthode Gundersen.</p><h3>La méthode Gundersen</h3><p>Les points du saut à ski se convertissent en avantages de temps. Pour chaque point derrière le leader, un athlète part plus tard dans la course de fond. Le premier à franchir la ligne d''arrivée gagne.</p><h2>Types d''épreuves</h2><h3>Individuel tremplin normal</h3><p>Les athlètes sautent d''un tremplin normal (environ 98 mètres). Puis ils courent 10 kilomètres en ski de fond. C''est le format classique.</p><h3>Individuel grand tremplin</h3><p>Les athlètes sautent d''un grand tremplin (environ 128 mètres). La course de fond est également de 10 kilomètres.</p><h3>Épreuve par équipes</h3><p>Quatre athlètes par équipe. Chacun saute une fois du grand tremplin. Puis l''équipe complète un relais 4x5 kilomètres.</p><h2>Compétences requises</h2><p>Les athlètes de combiné nordique ont besoin de capacités très différentes. Le saut à ski nécessite puissance explosive, équilibre et courage. Le ski de fond demande endurance, technique et force mentale.</p><h2>Athlètes célèbres</h2><p>Le sport a produit des athlètes polyvalents remarquables. La Norvège, l''Allemagne et l''Autriche ont traditionnellement dominé. Des athlètes comme Jarl Magnus Riiber de Norvège ont poussé le sport à de nouveaux niveaux.</p><h2>Où regarder</h2><p>Les grandes compétitions ont lieu dans des sites célèbres. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> à Oslo accueille des événements prestigieux.</p></article>",

  "it": "<article><h2>Cos''è la combinata nordica?</h2><p>La combinata nordica è uno sport invernale che combina due discipline: <a href=\"/ski-jumping-scoring-technique/\">il salto con gli sci</a> e <a href=\"/cross-country-skiing-techniques/\">lo sci di fondo</a>. Gli atleti devono eccellere in entrambe per competere al massimo livello. Questo rende la combinata nordica uno degli sport invernali più impegnativi.</p><h2>Formato della competizione</h2><p>La competizione ha due parti. Prima, gli atleti completano la parte di salto. I risultati del salto determinano l''ordine di partenza per la gara di fondo. I saltatori migliori partono per primi. Questo sistema si chiama metodo Gundersen.</p><h3>Il metodo Gundersen</h3><p>I punti del salto si convertono in vantaggi di tempo. Per ogni punto di ritardo dal leader, un atleta parte più tardi nella gara di fondo. Il primo a tagliare il traguardo vince.</p><h2>Tipi di gara</h2><h3>Individuale trampolino normale</h3><p>Gli atleti saltano da un trampolino normale (circa 98 metri). Poi corrono 10 chilometri di fondo. Questo è il formato classico.</p><h3>Individuale trampolino grande</h3><p>Gli atleti saltano da un trampolino grande (circa 128 metri). La gara di fondo è anch''essa di 10 chilometri.</p><h3>Gara a squadre</h3><p>Quattro atleti per squadra. Ognuno salta una volta dal trampolino grande. Poi la squadra completa una staffetta 4x5 chilometri.</p><h2>Abilità richieste</h2><p>Gli atleti di combinata nordica hanno bisogno di abilità molto diverse. Il salto richiede potenza esplosiva, equilibrio e coraggio. Lo sci di fondo richiede resistenza, tecnica e forza mentale.</p><h2>Atleti famosi</h2><p>Lo sport ha prodotto atleti versatili straordinari. Norvegia, Germania e Austria hanno tradizionalmente dominato.</p><h2>Dove guardare</h2><p>Le grandi competizioni si svolgono in sedi famose. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> a Oslo ospita eventi prestigiosi.</p></article>",

  "es": "<article><h2>¿Qué es la combinada nórdica?</h2><p>La combinada nórdica es un deporte de invierno que combina dos disciplinas: <a href=\"/ski-jumping-scoring-technique/\">el salto de esquí</a> y <a href=\"/cross-country-skiing-techniques/\">el esquí de fondo</a>. Los atletas deben sobresalir en ambas para competir al más alto nivel. Esto hace de la combinada nórdica uno de los deportes de invierno más exigentes.</p><h2>Formato de competición</h2><p>La competición tiene dos partes. Primero, los atletas completan la parte de salto. Los resultados del salto determinan el orden de salida para la carrera de fondo. Los mejores saltadores salen primero. Este sistema se llama método Gundersen.</p><h3>El método Gundersen</h3><p>Los puntos del salto se convierten en ventajas de tiempo. Por cada punto detrás del líder, un atleta sale más tarde en la carrera de fondo. El primero en cruzar la meta gana.</p><h2>Tipos de pruebas</h2><h3>Individual trampolín normal</h3><p>Los atletas saltan desde un trampolín normal (unos 98 metros). Luego corren 10 kilómetros de fondo.</p><h3>Individual trampolín grande</h3><p>Los atletas saltan desde un trampolín grande (unos 128 metros). La carrera de fondo también es de 10 kilómetros.</p><h3>Prueba por equipos</h3><p>Cuatro atletas por equipo. Cada uno salta una vez desde el trampolín grande. Luego el equipo completa un relevo 4x5 kilómetros.</p><h2>Habilidades requeridas</h2><p>Los atletas de combinada nórdica necesitan habilidades muy diferentes. El salto requiere potencia explosiva, equilibrio y valentía. El esquí de fondo demanda resistencia, técnica y fortaleza mental.</p><h2>Dónde ver</h2><p>Las grandes competiciones tienen lugar en sedes famosas. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> en Oslo alberga eventos prestigiosos.</p></article>",

  "pt": "<article><h2>O que é o combinado nórdico?</h2><p>O combinado nórdico é um esporte de inverno que combina duas disciplinas: <a href=\"/ski-jumping-scoring-technique/\">salto de esqui</a> e <a href=\"/cross-country-skiing-techniques/\">esqui cross-country</a>. Os atletas devem se destacar em ambas para competir no mais alto nível. Isso torna o combinado nórdico um dos esportes de inverno mais exigentes.</p><h2>Formato da competição</h2><p>A competição tem duas partes. Primeiro, os atletas completam a parte de salto. Os resultados do salto determinam a ordem de largada para a corrida de cross-country. Melhores saltadores largam primeiro. Este sistema é chamado método Gundersen.</p><h3>O método Gundersen</h3><p>Pontos do salto se convertem em vantagens de tempo. Para cada ponto atrás do líder, um atleta larga mais tarde na corrida de cross-country. O primeiro a cruzar a linha de chegada vence.</p><h2>Tipos de provas</h2><h3>Individual trampolim normal</h3><p>Atletas saltam de um trampolim normal (cerca de 98 metros). Depois correm 10 quilômetros de cross-country.</p><h3>Individual trampolim grande</h3><p>Atletas saltam de um trampolim grande (cerca de 128 metros). A corrida de cross-country também é de 10 quilômetros.</p><h3>Prova por equipes</h3><p>Quatro atletas por equipe. Cada um salta uma vez do trampolim grande. Depois a equipe completa um revezamento 4x5 quilômetros.</p><h2>Habilidades necessárias</h2><p>Atletas de combinado nórdico precisam de habilidades muito diferentes. O salto requer potência explosiva, equilíbrio e coragem. O cross-country exige resistência, técnica e força mental.</p><h2>Onde assistir</h2><p>Grandes competições acontecem em locais famosos. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> em Oslo sedia eventos prestigiosos.</p></article>",

  "nl": "<article><h2>Wat is noordse combinatie?</h2><p>Noordse combinatie is een wintersport die twee disciplines combineert: <a href=\"/ski-jumping-scoring-technique/\">schansspringen</a> en <a href=\"/cross-country-skiing-techniques/\">langlaufen</a>. Atleten moeten in beide uitblinken om op het hoogste niveau te concurreren. Dit maakt noordse combinatie een van de meest veeleisende wintersporten.</p><h2>Wedstrijdformaat</h2><p>De wedstrijd heeft twee delen. Eerst voltooien atleten het schansspringdeel. De springresultaten bepalen de startvolgorde voor de langlaufrace. Betere springers starten eerst. Dit systeem heet de Gundersen-methode.</p><h3>De Gundersen-methode</h3><p>Punten van schansspringen worden omgezet in tijdvoordelen. Voor elk punt achter de leider start een atleet later in de langlaufrace. De eerste die de finish kruist wint.</p><h2>Evenemententypes</h2><h3>Individueel normale schans</h3><p>Atleten springen van een normale schans (ongeveer 98 meter). Dan racen ze 10 kilometer langlaufen.</p><h3>Individueel grote schans</h3><p>Atleten springen van een grote schans (ongeveer 128 meter). De langlaufrace is ook 10 kilometer.</p><h3>Teamevenement</h3><p>Vier atleten per team. Elk springt eenmaal van de grote schans. Dan voltooit het team een 4x5 kilometer estafette.</p><h2>Vereiste vaardigheden</h2><p>Noordse combinatie atleten hebben zeer verschillende vaardigheden nodig. Schansspringen vereist explosieve kracht, balans en moed. Langlaufen eist uithoudingsvermogen, techniek en mentale kracht.</p><h2>Waar te kijken</h2><p>Grote wedstrijden vinden plaats op beroemde locaties. <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> in Oslo organiseert prestigieuze evenementen.</p></article>",

  "ar": "<article><h2>ما هو الجمع الشمالي؟</h2><p>الجمع الشمالي هو رياضة شتوية تجمع بين تخصصين: <a href=\"/ski-jumping-scoring-technique/\">القفز على الجليد</a> و<a href=\"/cross-country-skiing-techniques/\">التزلج الريفي</a>. يجب أن يتفوق الرياضيون في كليهما للمنافسة على أعلى مستوى. هذا يجعل الجمع الشمالي من أكثر الرياضات الشتوية تطلبًا.</p><h2>شكل المنافسة</h2><p>المنافسة لها جزءان. أولاً، يكمل الرياضيون جزء القفز. نتائج القفز تحدد ترتيب البداية لسباق التزلج الريفي. القافزون الأفضل يبدأون أولاً. هذا النظام يسمى طريقة غوندرسن.</p><h3>طريقة غوندرسن</h3><p>النقاط من القفز تتحول إلى مزايا زمنية. لكل نقطة خلف القائد، يبدأ الرياضي لاحقًا في سباق التزلج الريفي. أول من يعبر خط النهاية يفوز.</p><h2>أنواع الفعاليات</h2><h3>فردي منصة عادية</h3><p>الرياضيون يقفزون من منصة عادية (حوالي 98 متر). ثم يتسابقون 10 كيلومترات تزلج ريفي.</p><h3>فردي منصة كبيرة</h3><p>الرياضيون يقفزون من منصة كبيرة (حوالي 128 متر). سباق التزلج الريفي أيضًا 10 كيلومترات.</p><h3>فعالية الفرق</h3><p>أربعة رياضيين لكل فريق. كل واحد يقفز مرة من المنصة الكبيرة. ثم يكمل الفريق تتابع 4×5 كيلومترات.</p><h2>المهارات المطلوبة</h2><p>رياضيو الجمع الشمالي يحتاجون قدرات مختلفة جدًا. القفز يتطلب قوة انفجارية وتوازن وشجاعة. التزلج الريفي يتطلب تحمل وتقنية وقوة ذهنية.</p><h2>أين تشاهد</h2><p>المنافسات الكبرى تقام في أماكن شهيرة. <a href=\"/holmenkollen-venue-guide/\">هولمنكولن</a> في أوسلو تستضيف فعاليات مرموقة.</p></article>",

  "ja": "<article><h2>ノルディック複合とは？</h2><p>ノルディック複合は、2つの競技を組み合わせたウィンタースポーツです：<a href=\"/ski-jumping-scoring-technique/\">スキージャンプ</a>と<a href=\"/cross-country-skiing-techniques/\">クロスカントリースキー</a>。選手は両方で優れていなければ、最高レベルで競争できません。これがノルディック複合を最も要求の厳しいウィンタースポーツの1つにしています。</p><h2>競技形式</h2><p>競技は2部構成です。まず、選手はスキージャンプ部門を完了します。ジャンプの結果がクロスカントリーレースのスタート順を決定します。より良いジャンパーが先にスタートします。このシステムはグンダーセン方式と呼ばれます。</p><h3>グンダーセン方式</h3><p>スキージャンプのポイントが時間的アドバンテージに変換されます。リーダーから1ポイント遅れるごとに、選手はクロスカントリーレースで遅れてスタートします。最初にゴールラインを越えた人が勝ちます。</p><h2>種目タイプ</h2><h3>個人ノーマルヒル</h3><p>選手はノーマルヒル（約98メートル）からジャンプします。その後、10キロメートルのクロスカントリーを走ります。</p><h3>個人ラージヒル</h3><p>選手はラージヒル（約128メートル）からジャンプします。クロスカントリーレースも10キロメートルです。</p><h3>団体戦</h3><p>1チーム4人の選手。各選手がラージヒルから1回ジャンプします。その後、チームは4×5キロメートルのリレーを完了します。</p><h2>必要なスキル</h2><p>ノルディック複合の選手は非常に異なる能力を必要とします。スキージャンプは爆発的なパワー、バランス、勇気を必要とします。クロスカントリースキーは持久力、テクニック、精神力を要求します。</p><h2>観戦場所</h2><p>主要な大会は有名な会場で開催されます。オスロの<a href=\"/holmenkollen-venue-guide/\">ホルメンコーレン</a>は権威ある大会を開催しています。</p></article>",

  "zh": "<article><h2>什么是北欧两项？</h2><p>北欧两项是一项结合两个项目的冬季运动：<a href=\"/ski-jumping-scoring-technique/\">跳台滑雪</a>和<a href=\"/cross-country-skiing-techniques/\">越野滑雪</a>。运动员必须在两者都表现出色才能在最高水平竞争。这使北欧两项成为最具挑战性的冬季运动之一。</p><h2>比赛形式</h2><p>比赛分两部分。首先，运动员完成跳台滑雪部分。跳跃成绩决定越野滑雪比赛的出发顺序。跳得更好的选手先出发。这个系统叫做冈德森方法。</p><h3>冈德森方法</h3><p>跳台滑雪的分数转换为时间优势。每落后领先者一分，运动员在越野滑雪比赛中就晚出发相应时间。第一个冲过终点线的人获胜。</p><h2>项目类型</h2><h3>个人标准台</h3><p>运动员从标准台（约98米）跳跃。然后进行10公里越野滑雪比赛。</p><h3>个人大跳台</h3><p>运动员从大跳台（约128米）跳跃。越野滑雪比赛也是10公里。</p><h3>团体赛</h3><p>每队四名运动员。每人从大跳台跳一次。然后团队完成4×5公里接力。</p><h2>所需技能</h2><p>北欧两项运动员需要非常不同的能力。跳台滑雪需要爆发力、平衡感和勇气。越野滑雪需要耐力、技术和心理素质。</p><h2>观看地点</h2><p>重大比赛在著名场馆举行。奥斯陆的<a href=\"/holmenkollen-venue-guide/\">霍尔门科伦</a>举办享有盛誉的赛事。</p></article>",

  "ko": "<article><h2>노르딕 복합이란?</h2><p>노르딕 복합은 두 종목을 결합한 겨울 스포츠입니다: <a href=\"/ski-jumping-scoring-technique/\">스키점프</a>와 <a href=\"/cross-country-skiing-techniques/\">크로스컨트리 스키</a>. 선수들은 최고 수준에서 경쟁하려면 둘 다 뛰어나야 합니다. 이것이 노르딕 복합을 가장 까다로운 겨울 스포츠 중 하나로 만듭니다.</p><h2>경기 형식</h2><p>경기는 두 부분으로 구성됩니다. 먼저 선수들이 스키점프 부분을 완료합니다. 점프 결과가 크로스컨트리 레이스의 출발 순서를 결정합니다. 더 좋은 점퍼가 먼저 출발합니다. 이 시스템을 군데르센 방식이라고 합니다.</p><h3>군데르센 방식</h3><p>스키점프 점수가 시간 이점으로 전환됩니다. 선두보다 1점 뒤처질 때마다 선수는 크로스컨트리 레이스에서 늦게 출발합니다. 먼저 결승선을 통과한 사람이 우승합니다.</p><h2>종목 유형</h2><h3>개인 노멀힐</h3><p>선수들이 노멀힐(약 98미터)에서 점프합니다. 그런 다음 10킬로미터 크로스컨트리를 달립니다.</p><h3>개인 라지힐</h3><p>선수들이 라지힐(약 128미터)에서 점프합니다. 크로스컨트리 레이스도 10킬로미터입니다.</p><h3>단체전</h3><p>팀당 4명의 선수. 각자 라지힐에서 한 번씩 점프합니다. 그런 다음 팀이 4×5킬로미터 계주를 완료합니다.</p><h2>필요한 기술</h2><p>노르딕 복합 선수들은 매우 다른 능력이 필요합니다. 스키점프는 폭발적인 힘, 균형, 용기가 필요합니다. 크로스컨트리 스키는 지구력, 기술, 정신력을 요구합니다.</p><h2>관람 장소</h2><p>주요 대회는 유명한 경기장에서 열립니다. 오슬로의 <a href=\"/holmenkollen-venue-guide/\">홀멘콜렌</a>이 권위 있는 대회를 개최합니다.</p></article>"
}'::jsonb,

'sport-explainer',
'NK',

-- Meta descriptions
'{
  "en": "Learn how nordic combined works. This guide explains the Gundersen method, event formats, and why athletes must master both ski jumping and cross-country skiing.",
  "de": "Erfahren Sie, wie die Nordische Kombination funktioniert. Dieser Leitfaden erklärt die Gundersen-Methode, Wettkampfformate und warum Athleten beide Disziplinen beherrschen müssen.",
  "fr": "Découvrez comment fonctionne le combiné nordique. Ce guide explique la méthode Gundersen, les formats de compétition et pourquoi les athlètes doivent maîtriser le saut et le fond.",
  "it": "Scopri come funziona la combinata nordica. Questa guida spiega il metodo Gundersen, i formati di gara e perché gli atleti devono padroneggiare salto e fondo.",
  "es": "Aprende cómo funciona la combinada nórdica. Esta guía explica el método Gundersen, los formatos de competición y por qué los atletas deben dominar ambas disciplinas.",
  "pt": "Aprenda como funciona o combinado nórdico. Este guia explica o método Gundersen, formatos de competição e por que atletas devem dominar ambas as disciplinas.",
  "nl": "Leer hoe noordse combinatie werkt. Deze gids legt de Gundersen-methode, wedstrijdformaten en waarom atleten beide disciplines moeten beheersen uit.",
  "ar": "تعلم كيف يعمل الجمع الشمالي. هذا الدليل يشرح طريقة غوندرسن وأشكال المنافسة ولماذا يجب على الرياضيين إتقان كلا التخصصين.",
  "ja": "ノルディック複合の仕組みを学びましょう。このガイドではグンダーセン方式、競技形式、選手が両方の競技をマスターする必要がある理由を説明します。",
  "zh": "了解北欧两项的运作方式。本指南解释了冈德森方法、比赛形式以及运动员必须掌握两项技能的原因。",
  "ko": "노르딕 복합의 작동 방식을 알아보세요. 이 가이드는 군데르센 방식, 경기 형식, 선수들이 두 종목을 모두 마스터해야 하는 이유를 설명합니다."
}'::jsonb,

'published',
NOW(),
'evergreen');
