-- Migration 009: Snowboard Sport Explainer
-- Run with: docker exec -i neve26-db psql -U postgres -d neve26 -f - < migrations/009_snowboard.sql

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type) VALUES

('snowboard-racing-freestyle-guide',
-- Title (11 languages)
'{
  "en": "Snowboard: Racing and Freestyle Complete Guide",
  "de": "Snowboard: Kompletter Leitfaden für Rennen und Freestyle",
  "fr": "Snowboard : Guide complet course et freestyle",
  "it": "Snowboard: Guida completa gare e freestyle",
  "es": "Snowboard: Guía completa de carreras y freestyle",
  "pt": "Snowboard: Guia completo de corridas e estilo livre",
  "nl": "Snowboard: Complete gids voor racen en freestyle",
  "ar": "التزلج على الثلج: دليل شامل للسباقات والفريستايل",
  "ja": "スノーボード：レースとフリースタイル完全ガイド",
  "zh": "单板滑雪：竞速和自由式完整指南",
  "ko": "스노보드: 레이싱과 프리스타일 완벽 가이드"
}'::jsonb,

-- Excerpt
'{
  "en": "Snowboard events include halfpipe, slopestyle, big air, snowboard cross, parallel giant slalom, and parallel slalom. Learn the rules and formats for each discipline.",
  "de": "Snowboard-Events umfassen Halfpipe, Slopestyle, Big Air, Snowboardcross, Parallel-Riesenslalom und Parallel-Slalom. Lernen Sie die Regeln für jede Disziplin.",
  "fr": "Les épreuves de snowboard comprennent le halfpipe, le slopestyle, le Big Air, le snowboardcross et le slalom. Découvrez les règles de chaque discipline.",
  "it": "Gli eventi di snowboard includono halfpipe, slopestyle, big air, snowboard cross, slalom gigante parallelo e slalom parallelo. Scopri le regole per ogni disciplina.",
  "es": "Los eventos de snowboard incluyen halfpipe, slopestyle, big air, snowboard cross, slalom gigante paralelo y slalom paralelo. Aprende las reglas para cada disciplina.",
  "pt": "Eventos de snowboard incluem halfpipe, slopestyle, big air, snowboard cross, slalom gigante paralelo e slalom paralelo. Aprenda as regras de cada disciplina.",
  "nl": "Snowboard evenementen omvatten halfpipe, slopestyle, big air, snowboardcross, parallelle reuzenslalom en parallelle slalom. Leer de regels voor elke discipline.",
  "ar": "تشمل فعاليات التزلج على الثلج الهافبايب والسلوبستايل والقفزات الكبيرة وسباق الألواح والتعرج العملاق المتوازي والتعرج المتوازي.",
  "ja": "スノーボード種目にはハーフパイプ、スロープスタイル、ビッグエア、スノーボードクロス、パラレル大回転、パラレルスラロームが含まれます。",
  "zh": "单板滑雪项目包括U型场地、坡面障碍技巧、大跳台、单板滑雪追逐、平行大回转和平行回转。了解每个项目的规则。",
  "ko": "스노보드 종목에는 하프파이프, 슬로프스타일, 빅에어, 스노보드 크로스, 평행 대회전, 평행 회전이 포함됩니다."
}'::jsonb,

-- Content (11 languages)
'{
  "en": "<article><h2>Snowboard Competition Types</h2><p>Snowboard competitions split into two main categories: freestyle and racing. Freestyle rewards creativity and technical tricks. Racing rewards speed and precision. Some athletes compete in both, but most specialize.</p><h2>Freestyle Events</h2><h3>Halfpipe</h3><p>Athletes ride up and down a U-shaped channel carved into snow. They launch off the walls to perform tricks. Height above the lip, difficulty of tricks, and execution all matter. A run includes multiple hits. Judges score overall impression.</p><h3>Slopestyle</h3><p>A course with rails, boxes, and jumps. Athletes choose their line and link tricks together. Variety, difficulty, amplitude, and style all factor into scores. Best run counts from multiple attempts.</p><h3>Big Air</h3><p>One massive jump. Athletes perform a single trick on each attempt. Maximum amplitude and rotation. Judges score difficulty, execution, amplitude, and landing. Simple format with spectacular results.</p><h2>Racing Events</h2><h3>Snowboard Cross</h3><p>Four to six riders race head-to-head down a course with jumps, rollers, and banked turns. Contact happens frequently. First across the finish advances. Knockout rounds create intense drama. Speed and tactics both matter.</p><h3>Parallel Giant Slalom</h3><p>Two riders race down parallel courses with gates. Winner advances to the next round. Gates are wider than slalom, allowing higher speeds. Technical precision meets head-to-head racing excitement.</p><h3>Parallel Slalom</h3><p>Similar to parallel giant slalom but with tighter gates. More turns in a shorter distance. Athletes must balance aggression with control. Quick reactions essential.</p><h2>Equipment Differences</h2><p>Freestyle boards are typically shorter and more flexible. They often have twin tips for riding and landing switch (backwards). Racing boards are longer and stiffer for high-speed stability. Boots and bindings also differ between disciplines.</p><h2>Key Terminology</h2><ul><li><strong>Amplitude</strong>: Height achieved above the lip or jump</li><li><strong>Switch</strong>: Riding or landing backwards</li><li><strong>Grab</strong>: Holding the board during a trick</li><li><strong>Rotation</strong>: Spinning (180, 360, 540, 720, etc.)</li><li><strong>Flip</strong>: Rotating vertically</li></ul><h2>Major Competitions</h2><p>The FIS World Cup circuit includes both freestyle and racing events. X Games showcases the most progressive freestyle riding. Laax in Switzerland hosts major halfpipe events. Racing events happen at ski resorts across Europe and North America.</p><h2>Snowboard vs Skiing</h2><p>Snowboard and <a href=\"/freestyle-skiing-moguls-big-air/\">freestyle skiing</a> often share venues and formats. Both sports have halfpipe, slopestyle, and cross events. Athletes sometimes switch between sports, though it is rare at elite levels.</p></article>",

  "de": "<article><h2>Snowboard-Wettkampfarten</h2><p>Snowboard-Wettkämpfe teilen sich in zwei Hauptkategorien: Freestyle und Rennen. Freestyle belohnt Kreativität und technische Tricks. Rennen belohnt Geschwindigkeit und Präzision.</p><h2>Freestyle-Events</h2><h3>Halfpipe</h3><p>Athleten fahren in einem U-förmigen Kanal auf und ab. Sie starten von den Wänden, um Tricks auszuführen. Höhe über der Kante, Schwierigkeit der Tricks und Ausführung zählen alle.</p><h3>Slopestyle</h3><p>Ein Kurs mit Rails, Boxen und Sprüngen. Athleten wählen ihre Linie und verbinden Tricks. Vielfalt, Schwierigkeit, Amplitude und Stil fließen in die Wertung ein.</p><h3>Big Air</h3><p>Ein massiver Sprung. Athleten führen einen einzelnen Trick bei jedem Versuch aus. Maximale Amplitude und Rotation.</p><h2>Renn-Events</h2><h3>Snowboardcross</h3><p>Vier bis sechs Fahrer fahren Kopf an Kopf durch einen Kurs mit Sprüngen, Wellen und überhöhten Kurven. Kontakt passiert häufig. Der Erste im Ziel kommt weiter.</p><h3>Parallel-Riesenslalom</h3><p>Zwei Fahrer fahren auf parallelen Kursen mit Toren. Der Gewinner kommt in die nächste Runde. Tore sind weiter als beim Slalom.</p><h3>Parallel-Slalom</h3><p>Ähnlich wie Parallel-Riesenslalom, aber mit engeren Toren. Mehr Kurven auf kürzerer Strecke.</p><h2>Ausrüstungsunterschiede</h2><p>Freestyle-Boards sind typischerweise kürzer und flexibler. Renn-Boards sind länger und steifer für Hochgeschwindigkeitsstabilität.</p><h2>Snowboard vs Ski</h2><p>Snowboard und <a href=\"/freestyle-skiing-moguls-big-air/\">Freestyle-Ski</a> teilen oft Austragungsorte und Formate.</p></article>",

  "fr": "<article><h2>Types de compétitions de snowboard</h2><p>Les compétitions de snowboard se divisent en deux catégories principales: freestyle et course. Le freestyle récompense la créativité et les figures techniques. La course récompense la vitesse et la précision.</p><h2>Épreuves freestyle</h2><h3>Halfpipe</h3><p>Les athlètes montent et descendent dans un canal en forme de U. Ils s''élancent des murs pour effectuer des figures. La hauteur au-dessus de la lèvre, la difficulté des figures et l''exécution comptent toutes.</p><h3>Slopestyle</h3><p>Un parcours avec des rails, des boxes et des sauts. Les athlètes choisissent leur ligne et enchaînent les figures.</p><h3>Big Air</h3><p>Un seul saut massif. Les athlètes effectuent une figure à chaque tentative. Amplitude et rotation maximales.</p><h2>Épreuves de course</h2><h3>Snowboardcross</h3><p>Quatre à six riders courent tête à tête sur un parcours avec des sauts, des bosses et des virages relevés.</p><h3>Slalom géant parallèle</h3><p>Deux riders descendent des parcours parallèles avec des portes. Le gagnant avance au tour suivant.</p><h3>Slalom parallèle</h3><p>Similaire au slalom géant parallèle mais avec des portes plus serrées.</p><h2>Différences d''équipement</h2><p>Les planches freestyle sont typiquement plus courtes et plus souples. Les planches de course sont plus longues et plus rigides.</p><h2>Snowboard vs Ski</h2><p>Le snowboard et le <a href=\"/freestyle-skiing-moguls-big-air/\">ski freestyle</a> partagent souvent les sites et les formats.</p></article>",

  "it": "<article><h2>Tipi di gare di snowboard</h2><p>Le gare di snowboard si dividono in due categorie principali: freestyle e racing. Il freestyle premia creatività e trick tecnici. Il racing premia velocità e precisione.</p><h2>Eventi freestyle</h2><h3>Halfpipe</h3><p>Gli atleti salgono e scendono in un canale a U. Si lanciano dalle pareti per eseguire trick. Altezza sopra il bordo, difficoltà dei trick e esecuzione contano tutti.</p><h3>Slopestyle</h3><p>Un percorso con rail, box e salti. Gli atleti scelgono la loro linea e collegano i trick.</p><h3>Big Air</h3><p>Un singolo salto enorme. Gli atleti eseguono un trick ad ogni tentativo.</p><h2>Eventi di gara</h2><h3>Snowboard Cross</h3><p>Da quattro a sei rider gareggiano testa a testa su un percorso con salti, dossi e curve sopraelevate.</p><h3>Slalom Gigante Parallelo</h3><p>Due rider scendono percorsi paralleli con porte. Il vincitore avanza al turno successivo.</p><h3>Slalom Parallelo</h3><p>Simile allo slalom gigante parallelo ma con porte più strette.</p><h2>Differenze di attrezzatura</h2><p>Le tavole freestyle sono tipicamente più corte e flessibili. Le tavole da gara sono più lunghe e rigide.</p><h2>Snowboard vs Sci</h2><p>Snowboard e <a href=\"/freestyle-skiing-moguls-big-air/\">sci freestyle</a> condividono spesso location e formati.</p></article>",

  "es": "<article><h2>Tipos de competiciones de snowboard</h2><p>Las competiciones de snowboard se dividen en dos categorías principales: freestyle y carreras. El freestyle premia la creatividad y los trucos técnicos. Las carreras premian la velocidad y la precisión.</p><h2>Eventos freestyle</h2><h3>Halfpipe</h3><p>Los atletas suben y bajan por un canal en forma de U. Se lanzan desde las paredes para realizar trucos.</p><h3>Slopestyle</h3><p>Un circuito con rieles, cajas y saltos. Los atletas eligen su línea y enlazan trucos.</p><h3>Big Air</h3><p>Un solo salto masivo. Los atletas realizan un truco en cada intento.</p><h2>Eventos de carreras</h2><h3>Snowboard Cross</h3><p>De cuatro a seis riders compiten cara a cara por un circuito con saltos, lomos y curvas peraltadas.</p><h3>Slalom Gigante Paralelo</h3><p>Dos riders bajan por circuitos paralelos con puertas. El ganador avanza a la siguiente ronda.</p><h3>Slalom Paralelo</h3><p>Similar al slalom gigante paralelo pero con puertas más cerradas.</p><h2>Diferencias de equipo</h2><p>Las tablas freestyle son típicamente más cortas y flexibles. Las tablas de carreras son más largas y rígidas.</p><h2>Snowboard vs Esquí</h2><p>El snowboard y el <a href=\"/freestyle-skiing-moguls-big-air/\">esquí freestyle</a> a menudo comparten sedes y formatos.</p></article>",

  "pt": "<article><h2>Tipos de competições de snowboard</h2><p>As competições de snowboard se dividem em duas categorias principais: estilo livre e corridas. O estilo livre recompensa criatividade e truques técnicos. As corridas recompensam velocidade e precisão.</p><h2>Eventos de estilo livre</h2><h3>Halfpipe</h3><p>Os atletas sobem e descem em um canal em forma de U. Eles se lançam das paredes para realizar truques.</p><h3>Slopestyle</h3><p>Um circuito com trilhos, caixas e saltos. Os atletas escolhem sua linha e conectam truques.</p><h3>Big Air</h3><p>Um único salto massivo. Os atletas realizam um truque em cada tentativa.</p><h2>Eventos de corrida</h2><h3>Snowboard Cross</h3><p>De quatro a seis riders competem frente a frente em um circuito com saltos, ondulações e curvas inclinadas.</p><h3>Slalom Gigante Paralelo</h3><p>Dois riders descem percursos paralelos com portas. O vencedor avança para a próxima rodada.</p><h3>Slalom Paralelo</h3><p>Similar ao slalom gigante paralelo, mas com portas mais apertadas.</p><h2>Diferenças de equipamento</h2><p>As pranchas de estilo livre são tipicamente mais curtas e flexíveis. As pranchas de corrida são mais longas e rígidas.</p><h2>Snowboard vs Esqui</h2><p>Snowboard e <a href=\"/freestyle-skiing-moguls-big-air/\">esqui estilo livre</a> frequentemente compartilham locais e formatos.</p></article>",

  "nl": "<article><h2>Snowboard wedstrijdtypes</h2><p>Snowboardwedstrijden splitsen zich in twee hoofdcategorieën: freestyle en racen. Freestyle beloont creativiteit en technische tricks. Racen beloont snelheid en precisie.</p><h2>Freestyle evenementen</h2><h3>Halfpipe</h3><p>Atleten rijden op en neer in een U-vormig kanaal. Ze lanceren van de muren om tricks uit te voeren.</p><h3>Slopestyle</h3><p>Een parcours met rails, boxes en sprongen. Atleten kiezen hun lijn en verbinden tricks.</p><h3>Big Air</h3><p>Eén enorme sprong. Atleten voeren één trick uit bij elke poging.</p><h2>Race evenementen</h2><h3>Snowboardcross</h3><p>Vier tot zes rijders racen head-to-head over een parcours met sprongen, rollers en hellende bochten.</p><h3>Parallelle reuzenslalom</h3><p>Twee rijders dalen parallelle parcoursen met poorten af. De winnaar gaat door naar de volgende ronde.</p><h3>Parallelle slalom</h3><p>Vergelijkbaar met parallelle reuzenslalom maar met strakkere poorten.</p><h2>Uitrustingsverschillen</h2><p>Freestyle boards zijn typisch korter en flexibeler. Race boards zijn langer en stijver.</p><h2>Snowboard vs Skiën</h2><p>Snowboard en <a href=\"/freestyle-skiing-moguls-big-air/\">freestyleskiën</a> delen vaak locaties en formaten.</p></article>",

  "ar": "<article><h2>أنواع منافسات التزلج على الألواح</h2><p>تنقسم منافسات التزلج على الألواح إلى فئتين رئيسيتين: الفريستايل والسباقات. الفريستايل يكافئ الإبداع والحركات التقنية. السباقات تكافئ السرعة والدقة.</p><h2>فعاليات الفريستايل</h2><h3>الهافبايب</h3><p>الرياضيون يتحركون صعودًا ونزولًا في قناة على شكل حرف U. يقفزون من الجدران لأداء الحركات.</p><h3>سلوبستايل</h3><p>مسار به قضبان وصناديق وقفزات. الرياضيون يختارون خطهم ويربطون الحركات.</p><h3>القفزات الكبيرة</h3><p>قفزة ضخمة واحدة. الرياضيون يؤدون حركة واحدة في كل محاولة.</p><h2>فعاليات السباق</h2><h3>سباق الألواح</h3><p>من أربعة إلى ستة متسابقين يتنافسون وجهًا لوجه على مسار به قفزات ومنحدرات ومنعطفات مائلة.</p><h3>التعرج العملاق المتوازي</h3><p>متسابقان ينزلان مسارات متوازية ببوابات. الفائز يتقدم للجولة التالية.</p><h3>التعرج المتوازي</h3><p>مشابه للتعرج العملاق المتوازي لكن ببوابات أضيق.</p><h2>اختلافات المعدات</h2><p>ألواح الفريستايل عادة أقصر وأكثر مرونة. ألواح السباق أطول وأكثر صلابة.</p><h2>التزلج على الألواح مقابل التزلج</h2><p>التزلج على الألواح و<a href=\"/freestyle-skiing-moguls-big-air/\">التزلج الحر</a> يتشاركان غالبًا الأماكن والأشكال.</p></article>",

  "ja": "<article><h2>スノーボード競技の種類</h2><p>スノーボード競技は主に2つのカテゴリーに分かれます：フリースタイルとレース。フリースタイルは創造性と技術的なトリックを評価します。レースはスピードと正確さを評価します。</p><h2>フリースタイル種目</h2><h3>ハーフパイプ</h3><p>選手はU字型のチャンネルを上下に滑ります。壁から飛び出してトリックを行います。</p><h3>スロープスタイル</h3><p>レール、ボックス、ジャンプのあるコース。選手は自分のラインを選び、トリックをつなげます。</p><h3>ビッグエア</h3><p>1つの巨大なジャンプ。選手は各試技で1つのトリックを行います。</p><h2>レース種目</h2><h3>スノーボードクロス</h3><p>4〜6人のライダーがジャンプ、ローラー、バンクターンのあるコースで直接対決します。</p><h3>パラレル大回転</h3><p>2人のライダーがゲートのある並行コースを滑り降ります。勝者が次のラウンドに進みます。</p><h3>パラレルスラローム</h3><p>パラレル大回転と似ていますが、ゲートがより狭いです。</p><h2>装備の違い</h2><p>フリースタイルボードは通常より短く、柔軟です。レースボードはより長く、硬いです。</p><h2>スノーボード vs スキー</h2><p>スノーボードと<a href=\"/freestyle-skiing-moguls-big-air/\">フリースタイルスキー</a>はしばしば会場とフォーマットを共有します。</p></article>",

  "zh": "<article><h2>单板滑雪比赛类型</h2><p>单板滑雪比赛分为两大类：自由式和竞速。自由式奖励创造力和技术动作。竞速奖励速度和精准度。</p><h2>自由式项目</h2><h3>U型场地</h3><p>运动员在U形通道中上下滑行。他们从墙上起跳进行技巧动作。</p><h3>坡面障碍技巧</h3><p>有铁轨、箱子和跳台的赛道。运动员选择自己的路线并连接技巧动作。</p><h3>大跳台</h3><p>一个巨大的跳台。运动员每次尝试完成一个技巧动作。</p><h2>竞速项目</h2><h3>单板滑雪追逐</h3><p>四到六名选手在有跳台、起伏和倾斜弯道的赛道上进行面对面比赛。</p><h3>平行大回转</h3><p>两名选手在有旗门的平行赛道上滑行。获胜者晋级下一轮。</p><h3>平行回转</h3><p>类似于平行大回转，但旗门更紧密。</p><h2>装备差异</h2><p>自由式滑板通常更短、更灵活。竞速滑板更长、更硬。</p><h2>单板滑雪 vs 滑雪</h2><p>单板滑雪和<a href=\"/freestyle-skiing-moguls-big-air/\">自由式滑雪</a>经常共享场地和赛制。</p></article>",

  "ko": "<article><h2>스노보드 경기 유형</h2><p>스노보드 경기는 두 가지 주요 범주로 나뉩니다: 프리스타일과 레이싱. 프리스타일은 창의성과 기술적인 트릭을 보상합니다. 레이싱은 속도와 정확성을 보상합니다.</p><h2>프리스타일 종목</h2><h3>하프파이프</h3><p>선수들이 U자형 채널에서 위아래로 탑니다. 벽에서 뛰어올라 트릭을 수행합니다.</p><h3>슬로프스타일</h3><p>레일, 박스, 점프가 있는 코스. 선수들이 자신의 라인을 선택하고 트릭을 연결합니다.</p><h3>빅에어</h3><p>하나의 거대한 점프. 선수들이 각 시도에서 하나의 트릭을 수행합니다.</p><h2>레이싱 종목</h2><h3>스노보드 크로스</h3><p>4~6명의 라이더가 점프, 롤러, 뱅크 턴이 있는 코스에서 일대일로 경쟁합니다.</p><h3>평행 대회전</h3><p>두 명의 라이더가 게이트가 있는 평행 코스를 내려갑니다. 승자가 다음 라운드로 진출합니다.</p><h3>평행 회전</h3><p>평행 대회전과 비슷하지만 게이트가 더 좁습니다.</p><h2>장비 차이</h2><p>프리스타일 보드는 일반적으로 더 짧고 유연합니다. 레이싱 보드는 더 길고 단단합니다.</p><h2>스노보드 vs 스키</h2><p>스노보드와 <a href=\"/freestyle-skiing-moguls-big-air/\">프리스타일 스키</a>는 종종 장소와 형식을 공유합니다.</p></article>"
}'::jsonb,

'sport-explainer',
'SB',

-- Meta descriptions
'{
  "en": "Complete guide to snowboard events. Learn about halfpipe, slopestyle, big air, snowboard cross, and parallel slalom rules and scoring systems.",
  "de": "Vollständiger Leitfaden zu Snowboard-Events. Erfahren Sie mehr über Halfpipe, Slopestyle, Big Air, Snowboardcross und Parallel-Slalom Regeln.",
  "fr": "Guide complet des épreuves de snowboard. Découvrez le halfpipe, slopestyle, Big Air, snowboardcross et slalom parallèle.",
  "it": "Guida completa agli eventi di snowboard. Scopri halfpipe, slopestyle, big air, snowboard cross e slalom parallelo.",
  "es": "Guía completa de eventos de snowboard. Aprende sobre halfpipe, slopestyle, big air, snowboard cross y slalom paralelo.",
  "pt": "Guia completo de eventos de snowboard. Aprenda sobre halfpipe, slopestyle, big air, snowboard cross e slalom paralelo.",
  "nl": "Complete gids voor snowboard evenementen. Leer over halfpipe, slopestyle, big air, snowboardcross en parallelle slalom.",
  "ar": "دليل شامل لفعاليات التزلج على الألواح. تعرف على الهافبايب والسلوبستايل والقفزات الكبيرة وسباق الألواح والتعرج المتوازي.",
  "ja": "スノーボード種目の完全ガイド。ハーフパイプ、スロープスタイル、ビッグエア、スノーボードクロス、パラレルスラロームのルールを学びましょう。",
  "zh": "单板滑雪项目完整指南。了解U型场地、坡面障碍技巧、大跳台、单板滑雪追逐和平行回转的规则。",
  "ko": "스노보드 종목 완전 가이드. 하프파이프, 슬로프스타일, 빅에어, 스노보드 크로스, 평행 회전 규칙을 알아보세요."
}'::jsonb,

'published',
NOW(),
'evergreen');
