-- Migration 011: Marco Odermatt Athlete Profile
-- Run with: docker exec -i bronze-db psql -U postgres -d neve26 -f - < migrations/011_athlete_odermatt.sql

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type) VALUES

('marco-odermatt-profile',
-- Title (11 languages)
'{
  "en": "Marco Odermatt: The Complete Alpine Skier",
  "de": "Marco Odermatt: Der komplette Skirennläufer",
  "fr": "Marco Odermatt : Le skieur alpin complet",
  "it": "Marco Odermatt: Lo sciatore alpino completo",
  "es": "Marco Odermatt: El esquiador alpino completo",
  "pt": "Marco Odermatt: O esquiador alpino completo",
  "nl": "Marco Odermatt: De complete alpineskiër",
  "ar": "ماركو أودرمات: المتزلج الألبي الكامل",
  "ja": "マルコ・オーデルマット：完璧なアルペンスキーヤー",
  "zh": "马尔科·奥德马特：全能高山滑雪运动员",
  "ko": "마르코 오더마트: 완벽한 알파인 스키어"
}'::jsonb,

-- Excerpt
'{
  "en": "Marco Odermatt dominates World Cup alpine skiing with victories in giant slalom and super-G. The Swiss star has won multiple overall World Cup titles.",
  "de": "Marco Odermatt dominiert den Weltcup-Skisport mit Siegen im Riesenslalom und Super-G. Der Schweizer Star hat mehrere Gesamtweltcup-Titel gewonnen.",
  "fr": "Marco Odermatt domine le ski alpin en Coupe du monde avec des victoires en slalom géant et super-G. La star suisse a remporté plusieurs titres au général.",
  "it": "Marco Odermatt domina lo sci alpino in Coppa del Mondo con vittorie in gigante e super-G. La star svizzera ha vinto più titoli di Coppa del Mondo.",
  "es": "Marco Odermatt domina el esquí alpino de la Copa del Mundo con victorias en slalom gigante y super-G. La estrella suiza ha ganado múltiples títulos generales.",
  "pt": "Marco Odermatt domina o esqui alpino da Copa do Mundo com vitórias em slalom gigante e super-G. A estrela suíça ganhou múltiplos títulos gerais.",
  "nl": "Marco Odermatt domineert de Wereldbeker alpineskiën met overwinningen in reuzenslalom en super-G. De Zwitserse ster heeft meerdere algemene titels gewonnen.",
  "ar": "ماركو أودرمات يهيمن على كأس العالم للتزلج الألبي بانتصارات في التعرج العملاق والسوبر جي. النجم السويسري فاز بعدة ألقاب عامة.",
  "ja": "マルコ・オーデルマットは大回転とスーパーGで勝利を収め、ワールドカップアルペンスキーを支配しています。スイスのスターは複数の総合タイトルを獲得しています。",
  "zh": "马尔科·奥德马特以大回转和超级大回转的胜利主导世界杯高山滑雪。这位瑞士明星赢得了多个总冠军头衔。",
  "ko": "마르코 오더마트는 대회전과 슈퍼 대회전에서의 승리로 월드컵 알파인 스키를 지배하고 있습니다. 스위스의 스타는 여러 종합 타이틀을 획득했습니다."
}'::jsonb,

-- Content (11 languages)
'{
  "en": "<article><h2>Career Overview</h2><p>Marco Odermatt has established himself as the dominant force in men''s alpine skiing. Born October 8, 1997, in Buochs, Switzerland, he combines technical excellence with tactical intelligence. His ability to ski fast across multiple disciplines makes him the most complete skier of his generation.</p><h2>World Cup Success</h2><p>Odermatt won his first overall World Cup title in the 2021-22 season. He defended it successfully in subsequent seasons, cementing his status as the sport''s leading figure. His point totals have been among the highest in World Cup history.</p><h3>Discipline Strengths</h3><p>Giant slalom is Odermatt''s signature event. His technique through gates is exceptionally clean, and he carries speed others cannot match. In <a href=\"/alpine-skiing-disciplines/\">super-G</a>, his ability to read terrain gives him an advantage on technical courses. He has also shown competitive speed in downhill.</p><h2>Racing Style</h2><p>Odermatt''s skiing is characterized by:</p><ul><li><strong>Smooth technique</strong>: Minimal wasted movement</li><li><strong>High edge angles</strong>: Maximum grip through turns</li><li><strong>Risk management</strong>: Aggressive but controlled</li><li><strong>Tactical awareness</strong>: Adapts to conditions quickly</li></ul><h2>Key Victories</h2><p>Odermatt has won at the sport''s most prestigious venues. He has triumphed at <a href=\"/adelboden-venue-guide/\">Adelboden</a> in front of home crowds. Victories at <a href=\"/wengen-venue-guide/\">Wengen</a> and other classic venues have added to his legacy.</p><h2>Personal Background</h2><p>Growing up in central Switzerland, Odermatt developed his skills on the slopes near his home. He progressed through the Swiss ski system, showing talent from an early age. His family has supported his career throughout.</p><h2>Training Approach</h2><p>Odermatt works with a dedicated team of coaches and support staff. His summer training includes intensive physical conditioning. On-snow preparation focuses on refining technique and building confidence for each discipline.</p><h2>Rivalry and Competition</h2><p>Odermatt faces competition from top skiers including <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> of Norway and Austrian rivals. These battles have produced some of the most exciting racing in recent years.</p><h2>Impact on Swiss Skiing</h2><p>Odermatt has become a national hero in Switzerland. His success has inspired young Swiss skiers and brought attention to the sport domestically. He carries on the tradition of Swiss alpine skiing excellence alongside teammate <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p><h2>Looking Forward</h2><p>At his current age and form, Odermatt could dominate alpine skiing for years to come. His consistency and versatility suggest many more victories lie ahead.</p></article>",

  "de": "<article><h2>Karriereübersicht</h2><p>Marco Odermatt hat sich als dominierende Kraft im alpinen Skisport der Männer etabliert. Am 8. Oktober 1997 in Buochs, Schweiz, geboren, kombiniert er technische Exzellenz mit taktischer Intelligenz. Seine Fähigkeit, in mehreren Disziplinen schnell zu fahren, macht ihn zum komplettesten Skifahrer seiner Generation.</p><h2>Weltcup-Erfolg</h2><p>Odermatt gewann seinen ersten Gesamtweltcup-Titel in der Saison 2021-22. Er verteidigte ihn in den folgenden Saisons erfolgreich und festigte seinen Status als führende Figur des Sports.</p><h3>Disziplinstärken</h3><p>Riesenslalom ist Odermatts Paradedisziplin. Seine Technik durch die Tore ist außergewöhnlich sauber, und er trägt Geschwindigkeit, die andere nicht erreichen können. Im <a href=\"/alpine-skiing-disciplines/\">Super-G</a> gibt ihm seine Fähigkeit, das Gelände zu lesen, einen Vorteil auf technischen Kursen.</p><h2>Fahrstil</h2><p>Odermatts Skifahren zeichnet sich aus durch:</p><ul><li><strong>Saubere Technik</strong>: Minimale verschwendete Bewegung</li><li><strong>Hohe Kantenwinkel</strong>: Maximaler Grip in Kurven</li><li><strong>Risikomanagement</strong>: Aggressiv, aber kontrolliert</li><li><strong>Taktisches Bewusstsein</strong>: Passt sich schnell an Bedingungen an</li></ul><h2>Schlüsselsiege</h2><p>Odermatt hat an den prestigeträchtigsten Austragungsorten des Sports gewonnen. Er hat in <a href=\"/adelboden-venue-guide/\">Adelboden</a> vor heimischem Publikum triumphiert.</p><h2>Rivalität und Konkurrenz</h2><p>Odermatt steht im Wettbewerb mit Top-Skifahrern wie <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> aus Norwegen und österreichischen Rivalen.</p><h2>Einfluss auf den Schweizer Skisport</h2><p>Odermatt ist ein Nationalheld in der Schweiz geworden. Sein Erfolg hat junge Schweizer Skifahrer inspiriert. Er führt die Tradition der Schweizer alpinen Skiexzellenz zusammen mit Teamkollegin <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a> fort.</p></article>",

  "fr": "<article><h2>Aperçu de carrière</h2><p>Marco Odermatt s''est imposé comme la force dominante du ski alpin masculin. Né le 8 octobre 1997 à Buochs, en Suisse, il combine excellence technique et intelligence tactique. Sa capacité à skier vite dans plusieurs disciplines fait de lui le skieur le plus complet de sa génération.</p><h2>Succès en Coupe du monde</h2><p>Odermatt a remporté son premier titre au classement général de la Coupe du monde lors de la saison 2021-22. Il l''a défendu avec succès les saisons suivantes, consolidant son statut de figure de proue du sport.</p><h3>Forces par discipline</h3><p>Le slalom géant est l''épreuve signature d''Odermatt. Sa technique entre les portes est exceptionnellement propre. En <a href=\"/alpine-skiing-disciplines/\">super-G</a>, sa capacité à lire le terrain lui donne un avantage sur les parcours techniques.</p><h2>Style de course</h2><p>Le ski d''Odermatt se caractérise par:</p><ul><li><strong>Technique fluide</strong>: Mouvements gaspillés minimaux</li><li><strong>Angles de carre élevés</strong>: Adhérence maximale dans les virages</li><li><strong>Gestion des risques</strong>: Agressif mais contrôlé</li></ul><h2>Victoires clés</h2><p>Odermatt a gagné sur les sites les plus prestigieux. Il a triomphé à <a href=\"/adelboden-venue-guide/\">Adelboden</a> devant son public.</p><h2>Rivalité et compétition</h2><p>Odermatt affronte la concurrence de skieurs comme <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> de Norvège.</p><h2>Impact sur le ski suisse</h2><p>Odermatt est devenu un héros national en Suisse. Il perpétue la tradition d''excellence suisse avec sa coéquipière <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "it": "<article><h2>Panoramica della carriera</h2><p>Marco Odermatt si è affermato come la forza dominante nello sci alpino maschile. Nato l''8 ottobre 1997 a Buochs, in Svizzera, combina eccellenza tecnica con intelligenza tattica. La sua capacità di sciare veloce in più discipline lo rende lo sciatore più completo della sua generazione.</p><h2>Successo in Coppa del Mondo</h2><p>Odermatt ha vinto il suo primo titolo di Coppa del Mondo generale nella stagione 2021-22. Lo ha difeso con successo nelle stagioni successive, consolidando il suo status di figura di riferimento dello sport.</p><h3>Punti di forza per disciplina</h3><p>Il gigante è la gara caratteristica di Odermatt. La sua tecnica tra le porte è eccezionalmente pulita. Nel <a href=\"/alpine-skiing-disciplines/\">super-G</a>, la sua capacità di leggere il terreno gli dà un vantaggio sui percorsi tecnici.</p><h2>Stile di gara</h2><p>Lo sci di Odermatt è caratterizzato da:</p><ul><li><strong>Tecnica fluida</strong>: Movimento sprecato minimo</li><li><strong>Angoli di spigolo elevati</strong>: Massima aderenza nelle curve</li><li><strong>Gestione del rischio</strong>: Aggressivo ma controllato</li></ul><h2>Vittorie chiave</h2><p>Odermatt ha vinto nelle sedi più prestigiose. Ha trionfato ad <a href=\"/adelboden-venue-guide/\">Adelboden</a> davanti al pubblico di casa.</p><h2>Rivalità e competizione</h2><p>Odermatt affronta la concorrenza di sciatori come <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> dalla Norvegia.</p><h2>Impatto sullo sci svizzero</h2><p>Odermatt è diventato un eroe nazionale in Svizzera. Porta avanti la tradizione di eccellenza svizzera con la compagna di squadra <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "es": "<article><h2>Resumen de carrera</h2><p>Marco Odermatt se ha establecido como la fuerza dominante en el esquí alpino masculino. Nacido el 8 de octubre de 1997 en Buochs, Suiza, combina excelencia técnica con inteligencia táctica. Su capacidad para esquiar rápido en múltiples disciplinas lo convierte en el esquiador más completo de su generación.</p><h2>Éxito en la Copa del Mundo</h2><p>Odermatt ganó su primer título general de la Copa del Mundo en la temporada 2021-22. Lo defendió con éxito en temporadas posteriores, consolidando su estatus como figura líder del deporte.</p><h3>Fortalezas por disciplina</h3><p>El slalom gigante es el evento característico de Odermatt. Su técnica a través de las puertas es excepcionalmente limpia. En <a href=\"/alpine-skiing-disciplines/\">super-G</a>, su capacidad para leer el terreno le da ventaja en circuitos técnicos.</p><h2>Estilo de carrera</h2><p>El esquí de Odermatt se caracteriza por:</p><ul><li><strong>Técnica fluida</strong>: Movimiento desperdiciado mínimo</li><li><strong>Ángulos de canto altos</strong>: Máximo agarre en las curvas</li><li><strong>Gestión del riesgo</strong>: Agresivo pero controlado</li></ul><h2>Victorias clave</h2><p>Odermatt ha ganado en las sedes más prestigiosas. Ha triunfado en <a href=\"/adelboden-venue-guide/\">Adelboden</a> frente a su público.</p><h2>Rivalidad y competencia</h2><p>Odermatt enfrenta la competencia de esquiadores como <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> de Noruega.</p><h2>Impacto en el esquí suizo</h2><p>Odermatt se ha convertido en héroe nacional en Suiza. Continúa la tradición de excelencia suiza junto a su compañera <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "pt": "<article><h2>Visão geral da carreira</h2><p>Marco Odermatt se estabeleceu como a força dominante no esqui alpino masculino. Nascido em 8 de outubro de 1997 em Buochs, Suíça, ele combina excelência técnica com inteligência tática. Sua capacidade de esquiar rápido em múltiplas disciplinas o torna o esquiador mais completo de sua geração.</p><h2>Sucesso na Copa do Mundo</h2><p>Odermatt conquistou seu primeiro título geral da Copa do Mundo na temporada 2021-22. Ele o defendeu com sucesso nas temporadas seguintes, consolidando seu status como figura líder do esporte.</p><h3>Pontos fortes por disciplina</h3><p>O slalom gigante é o evento característico de Odermatt. Sua técnica através das portas é excepcionalmente limpa. No <a href=\"/alpine-skiing-disciplines/\">super-G</a>, sua capacidade de ler o terreno lhe dá vantagem em percursos técnicos.</p><h2>Estilo de corrida</h2><p>O esqui de Odermatt é caracterizado por:</p><ul><li><strong>Técnica suave</strong>: Movimento desperdiçado mínimo</li><li><strong>Ângulos de canto altos</strong>: Aderência máxima nas curvas</li><li><strong>Gestão de risco</strong>: Agressivo mas controlado</li></ul><h2>Vitórias importantes</h2><p>Odermatt venceu nos locais mais prestigiados. Ele triunfou em <a href=\"/adelboden-venue-guide/\">Adelboden</a> diante de seu público.</p><h2>Rivalidade e competição</h2><p>Odermatt enfrenta a concorrência de esquiadores como <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> da Noruega.</p><h2>Impacto no esqui suíço</h2><p>Odermatt se tornou um herói nacional na Suíça. Ele continua a tradição de excelência suíça ao lado de sua companheira <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "nl": "<article><h2>Carrière overzicht</h2><p>Marco Odermatt heeft zich gevestigd als de dominante kracht in het herenalpineskiën. Geboren op 8 oktober 1997 in Buochs, Zwitserland, combineert hij technische excellentie met tactische intelligentie. Zijn vermogen om snel te skiën in meerdere disciplines maakt hem de meest complete skiër van zijn generatie.</p><h2>Wereldbeker succes</h2><p>Odermatt won zijn eerste algemene Wereldbekertitel in het seizoen 2021-22. Hij verdedigde deze succesvol in de volgende seizoenen, waardoor hij zijn status als leidende figuur in de sport verstevigde.</p><h3>Sterke punten per discipline</h3><p>Reuzenslalom is Odermatts kenmerkende evenement. Zijn techniek door de poorten is uitzonderlijk schoon. In de <a href=\"/alpine-skiing-disciplines/\">super-G</a> geeft zijn vermogen om het terrein te lezen hem een voordeel op technische parcoursen.</p><h2>Racestijl</h2><p>Odermatts skiën wordt gekenmerkt door:</p><ul><li><strong>Soepele techniek</strong>: Minimale verspilde beweging</li><li><strong>Hoge kanthoeken</strong>: Maximale grip in bochten</li><li><strong>Risicobeheer</strong>: Agressief maar beheerst</li></ul><h2>Belangrijke overwinningen</h2><p>Odermatt heeft gewonnen op de meest prestigieuze locaties. Hij heeft gezegevierd in <a href=\"/adelboden-venue-guide/\">Adelboden</a> voor eigen publiek.</p><h2>Rivaliteit en competitie</h2><p>Odermatt staat tegenover concurrentie van skiërs zoals <a href=\"/henrik-kristoffersen-profile/\">Henrik Kristoffersen</a> uit Noorwegen.</p><h2>Impact op Zwitsers skiën</h2><p>Odermatt is een nationale held geworden in Zwitserland. Hij zet de traditie van Zwitserse excellentie voort met teamgenoot <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "ar": "<article><h2>نظرة عامة على المسيرة</h2><p>أثبت ماركو أودرمات نفسه كقوة مهيمنة في التزلج الألبي للرجال. ولد في 8 أكتوبر 1997 في بوخس، سويسرا، ويجمع بين التميز التقني والذكاء التكتيكي. قدرته على التزلج بسرعة في عدة تخصصات تجعله المتزلج الأكثر اكتمالاً في جيله.</p><h2>نجاح كأس العالم</h2><p>فاز أودرمات بأول لقب له في الترتيب العام لكأس العالم في موسم 2021-22. دافع عنه بنجاح في المواسم التالية، مما عزز مكانته كشخصية رائدة في الرياضة.</p><h3>نقاط القوة حسب التخصص</h3><p>التعرج العملاق هو الحدث المميز لأودرمات. تقنيته عبر البوابات نظيفة بشكل استثنائي. في <a href=\"/alpine-skiing-disciplines/\">السوبر جي</a>، قدرته على قراءة التضاريس تمنحه ميزة في المسارات التقنية.</p><h2>أسلوب السباق</h2><p>يتميز تزلج أودرمات بـ:</p><ul><li><strong>تقنية سلسة</strong>: حركة مهدرة قليلة</li><li><strong>زوايا حافة عالية</strong>: قبضة قصوى في المنعطفات</li><li><strong>إدارة المخاطر</strong>: عدواني لكن متحكم</li></ul><h2>انتصارات رئيسية</h2><p>فاز أودرمات في أكثر الأماكن شهرة. انتصر في <a href=\"/adelboden-venue-guide/\">أديلبودن</a> أمام جمهوره.</p><h2>التأثير على التزلج السويسري</h2><p>أصبح أودرمات بطلاً وطنياً في سويسرا. يواصل تقليد التميز السويسري مع زميلته <a href=\"/lara-gut-behrami-profile/\">لارا غوت بيهرامي</a>.</p></article>",

  "ja": "<article><h2>キャリア概要</h2><p>マルコ・オーデルマットは男子アルペンスキーで支配的な存在として確立しました。1997年10月8日、スイスのブオヒス生まれ、彼は技術的な卓越性と戦術的な知性を兼ね備えています。複数の種目で速く滑る能力は、彼を同世代で最も完成されたスキーヤーにしています。</p><h2>ワールドカップでの成功</h2><p>オーデルマットは2021-22シーズンに初のワールドカップ総合タイトルを獲得しました。その後のシーズンでも防衛に成功し、スポーツのリーダーとしての地位を固めました。</p><h3>種目別の強み</h3><p>大回転はオーデルマットの代表的な種目です。ゲートを通過する技術は非常にクリーンです。<a href=\"/alpine-skiing-disciplines/\">スーパーG</a>では、地形を読む能力が技術的なコースで有利に働きます。</p><h2>レーシングスタイル</h2><p>オーデルマットのスキーは以下で特徴づけられます：</p><ul><li><strong>滑らかな技術</strong>：無駄な動きが最小限</li><li><strong>高いエッジ角</strong>：ターンでの最大グリップ</li><li><strong>リスク管理</strong>：攻撃的だがコントロールされている</li></ul><h2>主要な勝利</h2><p>オーデルマットは最も権威ある会場で勝利を収めています。<a href=\"/adelboden-venue-guide/\">アーデルボーデン</a>でホームの観客の前で勝利しました。</p><h2>スイススキーへの影響</h2><p>オーデルマットはスイスの国民的ヒーローになりました。彼はチームメイトの<a href=\"/lara-gut-behrami-profile/\">ララ・グート・ベーラミ</a>とともにスイスの卓越した伝統を受け継いでいます。</p></article>",

  "zh": "<article><h2>职业生涯概述</h2><p>马尔科·奥德马特已确立了自己在男子高山滑雪领域的统治地位。1997年10月8日出生于瑞士布奥赫斯，他将技术卓越与战术智慧相结合。他在多个项目中快速滑行的能力使他成为这一代最全面的滑雪运动员。</p><h2>世界杯成就</h2><p>奥德马特在2021-22赛季赢得了他的首个世界杯总冠军。他在随后的赛季成功卫冕，巩固了他作为这项运动领军人物的地位。</p><h3>各项目优势</h3><p>大回转是奥德马特的标志性项目。他通过旗门的技术非常干净。在<a href=\"/alpine-skiing-disciplines/\">超级大回转</a>中，他解读地形的能力在技术性赛道上给他带来优势。</p><h2>比赛风格</h2><p>奥德马特的滑雪特点是：</p><ul><li><strong>流畅的技术</strong>：浪费的动作最少</li><li><strong>高边刃角度</strong>：转弯时最大抓地力</li><li><strong>风险管理</strong>：激进但有控制</li></ul><h2>重要胜利</h2><p>奥德马特在最负盛名的赛场上取得了胜利。他在<a href=\"/adelboden-venue-guide/\">阿德尔博登</a>的主场观众面前获胜。</p><h2>对瑞士滑雪的影响</h2><p>奥德马特已成为瑞士的国家英雄。他与队友<a href=\"/lara-gut-behrami-profile/\">拉拉·古特-贝拉米</a>一起延续着瑞士卓越的传统。</p></article>",

  "ko": "<article><h2>경력 개요</h2><p>마르코 오더마트는 남자 알파인 스키에서 지배적인 존재로 자리매김했습니다. 1997년 10월 8일 스위스 부오흐스에서 태어난 그는 기술적 탁월함과 전술적 지능을 결합합니다. 여러 종목에서 빠르게 스키를 타는 그의 능력은 그를 같은 세대에서 가장 완벽한 스키어로 만듭니다.</p><h2>월드컵 성공</h2><p>오더마트는 2021-22 시즌에 첫 월드컵 종합 타이틀을 획득했습니다. 그는 이후 시즌에서 성공적으로 방어하여 스포츠의 선두 인물로서의 지위를 확고히 했습니다.</p><h3>종목별 강점</h3><p>대회전은 오더마트의 대표 종목입니다. 게이트를 통과하는 그의 기술은 예외적으로 깨끗합니다. <a href=\"/alpine-skiing-disciplines/\">슈퍼 대회전</a>에서 지형을 읽는 그의 능력은 기술적인 코스에서 이점을 줍니다.</p><h2>레이싱 스타일</h2><p>오더마트의 스키는 다음과 같은 특징이 있습니다:</p><ul><li><strong>부드러운 기술</strong>: 낭비되는 움직임 최소화</li><li><strong>높은 에지 각도</strong>: 턴에서 최대 그립</li><li><strong>리스크 관리</strong>: 공격적이지만 제어됨</li></ul><h2>주요 승리</h2><p>오더마트는 가장 권위 있는 경기장에서 우승했습니다. 그는 <a href=\"/adelboden-venue-guide/\">아델보덴</a>에서 홈 관중 앞에서 승리했습니다.</p><h2>스위스 스키에 대한 영향</h2><p>오더마트는 스위스의 국민 영웅이 되었습니다. 그는 팀 동료 <a href=\"/lara-gut-behrami-profile/\">라라 구트-베라미</a>와 함께 스위스의 우수한 전통을 이어가고 있습니다.</p></article>"
}'::jsonb,

'athlete-profile',
'AS',

-- Meta descriptions
'{
  "en": "Marco Odermatt profile: Swiss alpine skiing star, multiple World Cup overall champion. Stats, racing style, and career highlights of the dominant giant slalom and super-G skier.",
  "de": "Marco Odermatt Profil: Schweizer Skistar, mehrfacher Gesamtweltcup-Sieger. Statistiken, Fahrstil und Karrierehöhepunkte des dominanten Riesenslalom- und Super-G-Fahrers.",
  "fr": "Profil de Marco Odermatt: star suisse du ski alpin, multiple champion au général de la Coupe du monde. Stats, style et moments forts de carrière.",
  "it": "Profilo di Marco Odermatt: star svizzera dello sci alpino, pluricampione generale di Coppa del Mondo. Statistiche, stile e momenti salienti della carriera.",
  "es": "Perfil de Marco Odermatt: estrella suiza del esquí alpino, múltiple campeón general de la Copa del Mundo. Estadísticas, estilo y momentos destacados.",
  "pt": "Perfil de Marco Odermatt: estrela suíça do esqui alpino, múltiplo campeão geral da Copa do Mundo. Estatísticas, estilo e destaques da carreira.",
  "nl": "Marco Odermatt profiel: Zwitserse alpineski-ster, meervoudig Wereldbeker algemeen kampioen. Statistieken, stijl en carrièrehoogtepunten.",
  "ar": "ملف ماركو أودرمات: نجم التزلج الألبي السويسري، بطل كأس العالم العام المتعدد. إحصائيات وأسلوب وأبرز محطات المسيرة.",
  "ja": "マルコ・オーデルマットプロフィール：スイスのアルペンスキースター、ワールドカップ総合チャンピオン複数回。統計、レーシングスタイル、キャリアハイライト。",
  "zh": "马尔科·奥德马特简介：瑞士高山滑雪明星，多次世界杯总冠军。统计数据、比赛风格和职业生涯亮点。",
  "ko": "마르코 오더마트 프로필: 스위스 알파인 스키 스타, 월드컵 종합 챔피언 다회 수상. 통계, 레이싱 스타일, 커리어 하이라이트."
}'::jsonb,

'published',
NOW(),
'evergreen');
