-- Migration 012: Mikaela Shiffrin Athlete Profile
-- Run with: docker exec -i bronze-db psql -U postgres -d neve26 -f - < migrations/012_athlete_shiffrin.sql

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type) VALUES

('mikaela-shiffrin-profile',
-- Title
'{
  "en": "Mikaela Shiffrin: Record-Breaking Alpine Skier",
  "de": "Mikaela Shiffrin: Rekord-Skirennläuferin",
  "fr": "Mikaela Shiffrin : Skieuse alpine aux records",
  "it": "Mikaela Shiffrin: Sciatrice alpina da record",
  "es": "Mikaela Shiffrin: Esquiadora alpina rompedora de récords",
  "pt": "Mikaela Shiffrin: Esquiadora alpina recordista",
  "nl": "Mikaela Shiffrin: Recordbrekende alpineskiester",
  "ar": "ميكايلا شيفرين: المتزلجة الألبية المحطمة للأرقام القياسية",
  "ja": "ミカエラ・シフリン：記録破りのアルペンスキーヤー",
  "zh": "米凯拉·希夫林：破纪录的高山滑雪运动员",
  "ko": "미카엘라 시프린: 기록을 깨는 알파인 스키어"
}'::jsonb,

-- Excerpt
'{
  "en": "Mikaela Shiffrin holds the record for most World Cup wins in alpine skiing history. The American star dominates in slalom and excels across all disciplines.",
  "de": "Mikaela Shiffrin hält den Rekord für die meisten Weltcup-Siege in der Geschichte des alpinen Skisports. Der amerikanische Star dominiert im Slalom.",
  "fr": "Mikaela Shiffrin détient le record du plus grand nombre de victoires en Coupe du monde. La star américaine domine en slalom.",
  "it": "Mikaela Shiffrin detiene il record di vittorie in Coppa del Mondo nella storia dello sci alpino. La star americana domina in slalom.",
  "es": "Mikaela Shiffrin tiene el récord de más victorias en Copa del Mundo. La estrella estadounidense domina en slalom.",
  "pt": "Mikaela Shiffrin detém o recorde de mais vitórias na Copa do Mundo. A estrela americana domina no slalom.",
  "nl": "Mikaela Shiffrin houdt het record voor meeste Wereldbekerzeges. De Amerikaanse ster domineert in slalom.",
  "ar": "ميكايلا شيفرين تحمل الرقم القياسي لأكثر انتصارات في كأس العالم. النجمة الأمريكية تهيمن في التعرج.",
  "ja": "ミカエラ・シフリンはワールドカップ最多勝利記録を保持しています。アメリカのスターはスラロームで支配的です。",
  "zh": "米凯拉·希夫林保持着世界杯最多胜利的记录。这位美国明星在回转项目中占据主导地位。",
  "ko": "미카엘라 시프린은 월드컵 최다 우승 기록을 보유하고 있습니다. 미국의 스타는 회전에서 지배적입니다."
}'::jsonb,

-- Content
'{
  "en": "<article><h2>The Greatest of All Time?</h2><p>Mikaela Shiffrin has rewritten the record books of alpine skiing. Born March 13, 1995, in Vail, Colorado, she has accumulated more World Cup victories than any skier in history, male or female. Her dominance spans nearly a decade and shows no signs of ending.</p><h2>Record-Breaking Career</h2><p>Shiffrin surpassed Lindsey Vonn''s women''s record and then Ingemar Stenmark''s all-time record. Each victory adds to a legacy that may never be matched. Her consistency across seasons is remarkable.</p><h3>Discipline Mastery</h3><p>While <a href=\"/alpine-skiing-disciplines/\">slalom</a> remains her signature event, Shiffrin has won in all five alpine disciplines. She has World Cup victories in slalom, giant slalom, super-G, downhill, and combined. This versatility sets her apart from specialists.</p><h2>Technical Excellence</h2><p>Shiffrin''s slalom technique is widely considered the best ever. Her characteristics include:</p><ul><li><strong>Early pressure</strong>: Engages the ski at the top of each turn</li><li><strong>Clean line</strong>: Takes the shortest path through gates</li><li><strong>Rhythm</strong>: Maintains consistent tempo throughout runs</li><li><strong>Recovery</strong>: Saves mistakes others cannot</li></ul><h2>Mental Strength</h2><p>Beyond technique, Shiffrin''s mental approach separates her from competitors. She has spoken openly about managing pressure and dealing with setbacks. Her return from personal tragedy demonstrated remarkable resilience.</p><h2>American Skiing Legacy</h2><p>Shiffrin has inspired a generation of American skiers. She followed in the footsteps of Vonn and other pioneers while surpassing their achievements. Her success has raised the profile of alpine skiing in the United States.</p><h2>Key Rivalries</h2><p>Shiffrin has faced strong competition from <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> of Slovakia and Swiss skiers including <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a> and <a href=\"/wendy-holdener-profile/\">Wendy Holdener</a>. These battles have produced memorable racing.</p><h2>Favorite Venues</h2><p>Killington in Vermont hosts the only World Cup race in the eastern United States, and Shiffrin thrives on home snow. She has also excelled in Europe at classic venues.</p><h2>Looking Ahead</h2><p>With her technique and drive, Shiffrin could continue winning for years. Every start is an opportunity to extend her record. The question is not if she will add wins, but how many.</p></article>",

  "de": "<article><h2>Die Größte aller Zeiten?</h2><p>Mikaela Shiffrin hat die Rekordbücher des alpinen Skisports neu geschrieben. Am 13. März 1995 in Vail, Colorado, geboren, hat sie mehr Weltcup-Siege als jeder andere Skifahrer in der Geschichte angesammelt. Ihre Dominanz erstreckt sich über fast ein Jahrzehnt.</p><h2>Rekordkarriere</h2><p>Shiffrin übertraf Lindsey Vonns Frauenrekord und dann Ingemar Stenmarks Allzeitrekord. Jeder Sieg fügt einem Vermächtnis hinzu, das vielleicht nie erreicht wird.</p><h3>Disziplinbeherrschung</h3><p>Während <a href=\"/alpine-skiing-disciplines/\">Slalom</a> ihre Paradedisziplin bleibt, hat Shiffrin in allen fünf alpinen Disziplinen gewonnen. Diese Vielseitigkeit unterscheidet sie von Spezialisten.</p><h2>Technische Exzellenz</h2><p>Shiffrins Slalomtechnik gilt als die beste aller Zeiten. Ihre Merkmale sind:</p><ul><li><strong>Früher Druck</strong>: Belastet den Ski am Anfang jeder Kurve</li><li><strong>Saubere Linie</strong>: Nimmt den kürzesten Weg durch die Tore</li><li><strong>Rhythmus</strong>: Behält ein konstantes Tempo bei</li></ul><h2>Mentale Stärke</h2><p>Über die Technik hinaus unterscheidet Shiffrins mentaler Ansatz sie von Konkurrenten. Ihre Rückkehr nach persönlicher Tragödie zeigte bemerkenswerte Widerstandsfähigkeit.</p><h2>Wichtige Rivalitäten</h2><p>Shiffrin hat starke Konkurrenz von <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> aus der Slowakei und Schweizer Skifahrerinnen wie <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a> erfahren.</p></article>",

  "fr": "<article><h2>La plus grande de tous les temps?</h2><p>Mikaela Shiffrin a réécrit les livres de records du ski alpin. Née le 13 mars 1995 à Vail, Colorado, elle a accumulé plus de victoires en Coupe du monde que tout autre skieur de l''histoire. Sa domination s''étend sur près d''une décennie.</p><h2>Carrière record</h2><p>Shiffrin a dépassé le record féminin de Lindsey Vonn puis le record absolu d''Ingemar Stenmark. Chaque victoire ajoute à un héritage qui ne sera peut-être jamais égalé.</p><h3>Maîtrise des disciplines</h3><p>Bien que le <a href=\"/alpine-skiing-disciplines/\">slalom</a> reste son épreuve signature, Shiffrin a gagné dans les cinq disciplines alpines. Cette polyvalence la distingue des spécialistes.</p><h2>Excellence technique</h2><p>La technique de slalom de Shiffrin est considérée comme la meilleure de tous les temps:</p><ul><li><strong>Pression précoce</strong>: Engage le ski au début de chaque virage</li><li><strong>Ligne propre</strong>: Prend le chemin le plus court entre les portes</li><li><strong>Rythme</strong>: Maintient un tempo constant</li></ul><h2>Force mentale</h2><p>Au-delà de la technique, l''approche mentale de Shiffrin la distingue. Son retour après une tragédie personnelle a démontré une résilience remarquable.</p><h2>Rivalités clés</h2><p>Shiffrin a affronté la forte concurrence de <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> et des Suissesses comme <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "it": "<article><h2>La più grande di tutti i tempi?</h2><p>Mikaela Shiffrin ha riscritto i libri dei record dello sci alpino. Nata il 13 marzo 1995 a Vail, Colorado, ha accumulato più vittorie in Coppa del Mondo di qualsiasi altro sciatore nella storia. Il suo dominio si estende per quasi un decennio.</p><h2>Carriera da record</h2><p>Shiffrin ha superato il record femminile di Lindsey Vonn e poi il record assoluto di Ingemar Stenmark. Ogni vittoria aggiunge a un''eredità che potrebbe non essere mai eguagliata.</p><h3>Padronanza delle discipline</h3><p>Sebbene lo <a href=\"/alpine-skiing-disciplines/\">slalom</a> rimanga il suo evento caratteristico, Shiffrin ha vinto in tutte e cinque le discipline alpine. Questa versatilità la distingue dagli specialisti.</p><h2>Eccellenza tecnica</h2><p>La tecnica di slalom di Shiffrin è considerata la migliore di sempre:</p><ul><li><strong>Pressione precoce</strong>: Impegna lo sci all''inizio di ogni curva</li><li><strong>Linea pulita</strong>: Prende il percorso più breve tra le porte</li><li><strong>Ritmo</strong>: Mantiene un tempo costante</li></ul><h2>Forza mentale</h2><p>Oltre alla tecnica, l''approccio mentale di Shiffrin la distingue. Il suo ritorno dopo una tragedia personale ha dimostrato una notevole resilienza.</p><h2>Rivalità chiave</h2><p>Shiffrin ha affrontato la forte concorrenza di <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> e delle svizzere come <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "es": "<article><h2>¿La más grande de todos los tiempos?</h2><p>Mikaela Shiffrin ha reescrito los libros de récords del esquí alpino. Nacida el 13 de marzo de 1995 en Vail, Colorado, ha acumulado más victorias en Copa del Mundo que cualquier otro esquiador en la historia. Su dominio abarca casi una década.</p><h2>Carrera récord</h2><p>Shiffrin superó el récord femenino de Lindsey Vonn y luego el récord absoluto de Ingemar Stenmark.</p><h3>Dominio de disciplinas</h3><p>Aunque el <a href=\"/alpine-skiing-disciplines/\">slalom</a> sigue siendo su evento característico, Shiffrin ha ganado en las cinco disciplinas alpinas.</p><h2>Excelencia técnica</h2><p>La técnica de slalom de Shiffrin se considera la mejor de todos los tiempos:</p><ul><li><strong>Presión temprana</strong>: Compromete el esquí al inicio de cada giro</li><li><strong>Línea limpia</strong>: Toma el camino más corto entre puertas</li><li><strong>Ritmo</strong>: Mantiene un tempo constante</li></ul><h2>Fortaleza mental</h2><p>Más allá de la técnica, el enfoque mental de Shiffrin la distingue. Su regreso tras una tragedia personal demostró una notable resiliencia.</p><h2>Rivalidades clave</h2><p>Shiffrin ha enfrentado fuerte competencia de <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> y esquiadoras suizas como <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "pt": "<article><h2>A maior de todos os tempos?</h2><p>Mikaela Shiffrin reescreveu os livros de recordes do esqui alpino. Nascida em 13 de março de 1995 em Vail, Colorado, ela acumulou mais vitórias na Copa do Mundo do que qualquer outro esquiador na história. Seu domínio abrange quase uma década.</p><h2>Carreira recorde</h2><p>Shiffrin superou o recorde feminino de Lindsey Vonn e depois o recorde absoluto de Ingemar Stenmark.</p><h3>Domínio das disciplinas</h3><p>Embora o <a href=\"/alpine-skiing-disciplines/\">slalom</a> continue sendo seu evento característico, Shiffrin venceu nas cinco disciplinas alpinas.</p><h2>Excelência técnica</h2><p>A técnica de slalom de Shiffrin é considerada a melhor de todos os tempos:</p><ul><li><strong>Pressão inicial</strong>: Engaja o esqui no início de cada curva</li><li><strong>Linha limpa</strong>: Faz o caminho mais curto entre as portas</li><li><strong>Ritmo</strong>: Mantém um tempo consistente</li></ul><h2>Força mental</h2><p>Além da técnica, a abordagem mental de Shiffrin a distingue. Seu retorno após uma tragédia pessoal demonstrou notável resiliência.</p><h2>Rivalidades importantes</h2><p>Shiffrin enfrentou forte concorrência de <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> e esquiadoras suíças como <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "nl": "<article><h2>De grootste aller tijden?</h2><p>Mikaela Shiffrin heeft de recordboeken van het alpineskiën herschreven. Geboren op 13 maart 1995 in Vail, Colorado, heeft ze meer Wereldbekerzeges behaald dan welke skiër dan ook in de geschiedenis. Haar dominantie strekt zich uit over bijna een decennium.</p><h2>Recordcarrière</h2><p>Shiffrin overtrof het vrouwenrecord van Lindsey Vonn en daarna het absolute record van Ingemar Stenmark.</p><h3>Disciplinebeheersing</h3><p>Hoewel <a href=\"/alpine-skiing-disciplines/\">slalom</a> haar kenmerkende evenement blijft, heeft Shiffrin in alle vijf de alpinedisciplines gewonnen.</p><h2>Technische excellentie</h2><p>Shiffrins slalomtechniek wordt beschouwd als de beste ooit:</p><ul><li><strong>Vroege druk</strong>: Belast de ski aan het begin van elke bocht</li><li><strong>Schone lijn</strong>: Neemt het kortste pad door de poorten</li><li><strong>Ritme</strong>: Behoudt een consistent tempo</li></ul><h2>Mentale kracht</h2><p>Naast techniek onderscheidt Shiffrins mentale aanpak haar. Haar terugkeer na persoonlijke tragedie toonde opmerkelijke veerkracht.</p><h2>Belangrijke rivaliteiten</h2><p>Shiffrin heeft sterke concurrentie ondervonden van <a href=\"/petra-vlhova-profile/\">Petra Vlhová</a> en Zwitserse skiësters zoals <a href=\"/lara-gut-behrami-profile/\">Lara Gut-Behrami</a>.</p></article>",

  "ar": "<article><h2>الأعظم على الإطلاق؟</h2><p>أعادت ميكايلا شيفرين كتابة سجلات التزلج الألبي. ولدت في 13 مارس 1995 في فيل، كولورادو، وجمعت انتصارات في كأس العالم أكثر من أي متزلج في التاريخ. هيمنتها تمتد لما يقرب من عقد.</p><h2>مسيرة قياسية</h2><p>تجاوزت شيفرين رقم ليندسي فون القياسي للنساء ثم رقم إنجمار ستينمارك القياسي المطلق.</p><h3>إتقان التخصصات</h3><p>بينما يظل <a href=\"/alpine-skiing-disciplines/\">التعرج</a> حدثها المميز، فازت شيفرين في جميع التخصصات الألبية الخمسة.</p><h2>التميز التقني</h2><p>تقنية التعرج لدى شيفرين تعتبر الأفضل على الإطلاق:</p><ul><li><strong>ضغط مبكر</strong>: تشغل الزلاجة في بداية كل منعطف</li><li><strong>خط نظيف</strong>: تأخذ أقصر طريق عبر البوابات</li><li><strong>إيقاع</strong>: تحافظ على وتيرة ثابتة</li></ul><h2>القوة الذهنية</h2><p>بعد التقنية، نهج شيفرين الذهني يميزها. عودتها بعد مأساة شخصية أظهرت مرونة ملحوظة.</p><h2>المنافسات الرئيسية</h2><p>واجهت شيفرين منافسة قوية من <a href=\"/petra-vlhova-profile/\">بيترا فلهوفا</a> والمتزلجات السويسريات مثل <a href=\"/lara-gut-behrami-profile/\">لارا غوت بيهرامي</a>.</p></article>",

  "ja": "<article><h2>史上最高か？</h2><p>ミカエラ・シフリンはアルペンスキーの記録を書き換えました。1995年3月13日、コロラド州ベイル生まれの彼女は、歴史上どのスキーヤーよりも多くのワールドカップ勝利を積み重ねています。彼女の支配は約10年にわたっています。</p><h2>記録破りのキャリア</h2><p>シフリンはリンゼイ・ボンの女子記録を超え、その後インゲマル・ステンマルクの歴代記録を超えました。</p><h3>種目のマスタリー</h3><p><a href=\"/alpine-skiing-disciplines/\">スラローム</a>が彼女の代表的な種目ですが、シフリンは5つのアルペン種目すべてで勝利しています。</p><h2>技術的卓越性</h2><p>シフリンのスラローム技術は史上最高と考えられています：</p><ul><li><strong>早い圧力</strong>：各ターンの最初でスキーを使う</li><li><strong>クリーンなライン</strong>：ゲート間で最短経路を取る</li><li><strong>リズム</strong>：一貫したテンポを維持</li></ul><h2>精神的強さ</h2><p>技術を超えて、シフリンの精神的アプローチが彼女を際立たせています。個人的な悲劇からの復帰は驚くべき回復力を示しました。</p><h2>主なライバル関係</h2><p>シフリンは<a href=\"/petra-vlhova-profile/\">ペトラ・ブルホバ</a>や<a href=\"/lara-gut-behrami-profile/\">ララ・グート・ベーラミ</a>などのスイス選手との強い競争に直面しています。</p></article>",

  "zh": "<article><h2>有史以来最伟大？</h2><p>米凯拉·希夫林重写了高山滑雪的记录。1995年3月13日出生于科罗拉多州韦尔，她积累的世界杯胜利比历史上任何滑雪运动员都多。她的统治延续了近十年。</p><h2>破纪录的职业生涯</h2><p>希夫林超越了林赛·沃恩的女子记录，然后又超越了因格马尔·斯滕马克的历史记录。</p><h3>各项目精通</h3><p>虽然<a href=\"/alpine-skiing-disciplines/\">回转</a>仍然是她的标志性项目，但希夫林在所有五个高山项目中都获得过胜利。</p><h2>技术卓越</h2><p>希夫林的回转技术被广泛认为是有史以来最好的：</p><ul><li><strong>早期施压</strong>：在每个弯道开始时使用滑雪板</li><li><strong>干净的路线</strong>：在旗门之间走最短路径</li><li><strong>节奏</strong>：保持一致的节奏</li></ul><h2>心理力量</h2><p>除了技术之外，希夫林的心理方法使她与众不同。她从个人悲剧中恢复展示了非凡的韧性。</p><h2>主要对手</h2><p>希夫林面临着来自<a href=\"/petra-vlhova-profile/\">佩特拉·弗尔霍娃</a>和<a href=\"/lara-gut-behrami-profile/\">拉拉·古特-贝拉米</a>等瑞士选手的强劲竞争。</p></article>",

  "ko": "<article><h2>역사상 가장 위대한가?</h2><p>미카엘라 시프린은 알파인 스키의 기록을 다시 썼습니다. 1995년 3월 13일 콜로라도 베일에서 태어난 그녀는 역사상 어떤 스키어보다 더 많은 월드컵 우승을 축적했습니다. 그녀의 지배는 거의 10년에 걸쳐 있습니다.</p><h2>기록 경력</h2><p>시프린은 린지 본의 여자 기록을 넘어섰고, 그 후 잉게마르 스텐마르크의 역대 기록을 넘어섰습니다.</p><h3>종목 마스터리</h3><p><a href=\"/alpine-skiing-disciplines/\">회전</a>이 그녀의 대표 종목이지만, 시프린은 5개의 알파인 종목 모두에서 우승했습니다.</p><h2>기술적 우수성</h2><p>시프린의 회전 기술은 역사상 최고로 여겨집니다:</p><ul><li><strong>조기 압력</strong>: 각 턴 시작에서 스키 사용</li><li><strong>깨끗한 라인</strong>: 게이트 사이 최단 경로</li><li><strong>리듬</strong>: 일관된 템포 유지</li></ul><h2>정신적 강인함</h2><p>기술을 넘어 시프린의 정신적 접근 방식이 그녀를 구별합니다. 개인적인 비극에서의 복귀는 놀라운 회복력을 보여주었습니다.</p><h2>주요 라이벌</h2><p>시프린은 <a href=\"/petra-vlhova-profile/\">페트라 블호바</a>와 <a href=\"/lara-gut-behrami-profile/\">라라 구트-베라미</a> 같은 스위스 스키어들과의 강한 경쟁에 직면했습니다.</p></article>"
}'::jsonb,

'athlete-profile',
'AS',

-- Meta descriptions
'{
  "en": "Mikaela Shiffrin profile: American alpine skiing legend with the most World Cup wins in history. Stats, technique analysis, and career highlights.",
  "de": "Mikaela Shiffrin Profil: Amerikanische Skileggende mit den meisten Weltcup-Siegen der Geschichte. Statistiken, Technikanalyse und Karrierehöhepunkte.",
  "fr": "Profil de Mikaela Shiffrin: légende américaine du ski alpin avec le plus de victoires en Coupe du monde. Stats, analyse technique et moments forts.",
  "it": "Profilo di Mikaela Shiffrin: leggenda americana dello sci alpino con più vittorie in Coppa del Mondo. Statistiche, analisi tecnica e momenti salienti.",
  "es": "Perfil de Mikaela Shiffrin: leyenda estadounidense del esquí alpino con más victorias en Copa del Mundo. Estadísticas, análisis técnico y momentos destacados.",
  "pt": "Perfil de Mikaela Shiffrin: lenda americana do esqui alpino com mais vitórias na Copa do Mundo. Estatísticas, análise técnica e destaques.",
  "nl": "Mikaela Shiffrin profiel: Amerikaanse skileggende met de meeste Wereldbekerzeges. Statistieken, techniekanalyse en hoogtepunten.",
  "ar": "ملف ميكايلا شيفرين: أسطورة التزلج الألبي الأمريكية مع أكثر انتصارات في كأس العالم. إحصائيات وتحليل تقني وأبرز المحطات.",
  "ja": "ミカエラ・シフリンプロフィール：ワールドカップ最多勝利のアメリカンスキーレジェンド。統計、技術分析、キャリアハイライト。",
  "zh": "米凯拉·希夫林简介：世界杯最多胜利的美国高山滑雪传奇。统计数据、技术分析和职业亮点。",
  "ko": "미카엘라 시프린 프로필: 월드컵 최다 우승의 미국 알파인 스키 전설. 통계, 기술 분석, 커리어 하이라이트."
}'::jsonb,

'published',
NOW(),
'evergreen');
