-- Migration 014: Stefan Kraft Athlete Profile
-- Run with: docker exec -i bronze-db psql -U postgres -d neve26 -f - < migrations/014_athlete_kraft.sql

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type) VALUES

('stefan-kraft-profile',
-- Title
'{
  "en": "Stefan Kraft: Austria''s Ski Jumping Legend",
  "de": "Stefan Kraft: Österreichs Skisprung-Legende",
  "fr": "Stefan Kraft : La légende autrichienne du saut à ski",
  "it": "Stefan Kraft: La leggenda austriaca del salto con gli sci",
  "es": "Stefan Kraft: La leyenda austríaca del salto de esquí",
  "pt": "Stefan Kraft: A lenda austríaca do salto de esqui",
  "nl": "Stefan Kraft: Oostenrijks schansspringend legende",
  "ar": "ستيفان كرافت: أسطورة القفز على الجليد النمساوية",
  "ja": "シュテファン・クラフト：オーストリアのスキージャンプ伝説",
  "zh": "斯特凡·克拉夫特：奥地利跳台滑雪传奇",
  "ko": "슈테판 크라프트: 오스트리아의 스키점프 전설"
}'::jsonb,

-- Excerpt
'{
  "en": "Stefan Kraft holds the world record for the longest ski jump and has won multiple World Cup overall titles. The Austrian combines technical perfection with competitive fire.",
  "de": "Stefan Kraft hält den Weltrekord für den längsten Skisprung und hat mehrere Gesamtweltcup-Titel gewonnen. Der Österreicher kombiniert technische Perfektion mit Wettkampfgeist.",
  "fr": "Stefan Kraft détient le record du monde du plus long saut à ski et a remporté plusieurs titres au général. L''Autrichien combine perfection technique et esprit compétitif.",
  "it": "Stefan Kraft detiene il record mondiale per il salto con gli sci più lungo e ha vinto più titoli generali. L''austriaco combina perfezione tecnica con spirito competitivo.",
  "es": "Stefan Kraft tiene el récord mundial del salto de esquí más largo y ha ganado múltiples títulos generales. El austríaco combina perfección técnica con espíritu competitivo.",
  "pt": "Stefan Kraft detém o recorde mundial do salto de esqui mais longo e ganhou múltiplos títulos gerais. O austríaco combina perfeição técnica com espírito competitivo.",
  "nl": "Stefan Kraft houdt het wereldrecord voor de langste skisprong en heeft meerdere Wereldbeker titels gewonnen. De Oostenrijker combineert technische perfectie met competitieve geest.",
  "ar": "يحمل ستيفان كرافت الرقم القياسي العالمي لأطول قفزة تزلج وفاز بعدة ألقاب عامة. النمساوي يجمع بين الكمال التقني والروح التنافسية.",
  "ja": "シュテファン・クラフトはスキージャンプの世界最長記録を保持し、複数のワールドカップ総合タイトルを獲得しています。オーストリア人は技術的完璧さと競争心を兼ね備えています。",
  "zh": "斯特凡·克拉夫特保持着最远跳台滑雪的世界纪录，并赢得了多个世界杯总冠军。这位奥地利人将技术完美与竞技精神相结合。",
  "ko": "슈테판 크라프트는 스키점프 최장 거리 세계 기록을 보유하고 있으며 여러 월드컵 종합 타이틀을 획득했습니다. 오스트리아인은 기술적 완벽함과 경쟁 정신을 결합합니다."
}'::jsonb,

-- Content
'{
  "en": "<article><h2>World Record Holder</h2><p>Stefan Kraft became a legend on March 18, 2017, when he flew 253.5 meters in Vikersund, Norway. This world record jump showcased everything that makes Kraft special: perfect technique, courage, and the ability to perform when it matters most.</p><h2>Career Highlights</h2><p>Born May 13, 1993, in Schwarzach im Pongau, Austria, Kraft has accumulated an impressive collection of achievements. Multiple World Cup overall titles, World Championship gold medals, and consistent top performances have made him one of the greatest ski jumpers ever.</p><h2>Technical Excellence</h2><p><a href=\"/ski-jumping-scoring-technique/\">Ski jumping</a> rewards athletes who master every phase of the jump. Kraft excels at:</p><ul><li><strong>In-run position</strong>: Aerodynamic and stable approach</li><li><strong>Takeoff timing</strong>: Explosive power at the right moment</li><li><strong>Flight position</strong>: Optimal V-style for maximum distance</li><li><strong>Landing</strong>: Consistent telemark for style points</li></ul><h2>Mental Strength</h2><p>Kraft has shown remarkable ability to handle pressure. Whether leading a competition or needing to jump from behind, he delivers under pressure. This mental fortitude separates elite jumpers from the rest.</p><h2>Key Venues</h2><p>Kraft has performed brilliantly at <a href=\"/planica-venue-guide/\">Planica</a>, where flying hills suit his aggressive style. At <a href=\"/innsbruck-venue-guide/\">Bergisel</a> in Innsbruck, he thrills Austrian fans. He has also excelled at <a href=\"/holmenkollen-venue-guide/\">Holmenkollen</a> and other classic venues.</p><h2>Competition</h2><p>Kraft faces competition from <a href=\"/ryoyu-kobayashi-profile/\">Ryōyū Kobayashi</a> of Japan, <a href=\"/halvor-granerud-profile/\">Halvor Egner Granerud</a> of Norway, and other top jumpers. These rivalries have produced thrilling competitions.</p><h2>Four Hills Tournament</h2><p>The prestigious Four Hills Tournament (Vierschanzentournee) has been a focus for Kraft. Success in this New Year tradition carries special meaning in German-speaking countries.</p><h2>Austrian Ski Jumping Legacy</h2><p>Kraft continues Austria''s proud ski jumping tradition. He follows legends while inspiring the next generation. His success has maintained Austria''s position as a ski jumping powerhouse.</p><h2>Training and Approach</h2><p>Austrian ski jumping benefits from excellent facilities and coaching. Kraft''s preparation combines physical training, technical refinement, and mental conditioning. Every detail is optimized for competition.</p></article>",

  "de": "<article><h2>Weltrekordhalter</h2><p>Stefan Kraft wurde am 18. März 2017 zur Legende, als er in Vikersund, Norwegen, 253,5 Meter flog. Dieser Weltrekordsprung zeigte alles, was Kraft besonders macht: perfekte Technik, Mut und die Fähigkeit, zu liefern, wenn es darauf ankommt.</p><h2>Karrierehöhepunkte</h2><p>Am 13. Mai 1993 in Schwarzach im Pongau, Österreich, geboren, hat Kraft eine beeindruckende Sammlung von Erfolgen angehäuft. Mehrere Gesamtweltcup-Titel und WM-Goldmedaillen haben ihn zu einem der größten Skispringer aller Zeiten gemacht.</p><h2>Technische Exzellenz</h2><p><a href=\"/ski-jumping-scoring-technique/\">Skispringen</a> belohnt Athleten, die jede Phase des Sprungs meistern. Kraft glänzt bei:</p><ul><li><strong>Anlaufposition</strong>: Aerodynamischer und stabiler Anlauf</li><li><strong>Absprungtiming</strong>: Explosive Kraft im richtigen Moment</li><li><strong>Flugposition</strong>: Optimaler V-Stil für maximale Weite</li><li><strong>Landung</strong>: Konstanter Telemark für Haltungsnoten</li></ul><h2>Mentale Stärke</h2><p>Kraft hat bemerkenswerte Fähigkeit gezeigt, mit Druck umzugehen.</p><h2>Wichtige Austragungsorte</h2><p>Kraft hat brillant in <a href=\"/planica-venue-guide/\">Planica</a> performt. Am <a href=\"/innsbruck-venue-guide/\">Bergisel</a> in Innsbruck begeistert er österreichische Fans.</p><h2>Vierschanzentournee</h2><p>Die prestigeträchtige Vierschanzentournee war ein Fokus für Kraft. Erfolg in dieser Neujahrstradition hat besondere Bedeutung im deutschsprachigen Raum.</p><h2>Österreichs Skisprung-Vermächtnis</h2><p>Kraft setzt Österreichs stolze Skisprung-Tradition fort.</p></article>",

  "fr": "<article><h2>Détenteur du record du monde</h2><p>Stefan Kraft est devenu une légende le 18 mars 2017, quand il a volé 253,5 mètres à Vikersund, Norvège. Ce saut record a montré tout ce qui rend Kraft spécial.</p><h2>Points forts de carrière</h2><p>Né le 13 mai 1993 à Schwarzach im Pongau, Autriche, Kraft a accumulé une collection impressionnante de réalisations.</p><h2>Excellence technique</h2><p>Le <a href=\"/ski-jumping-scoring-technique/\">saut à ski</a> récompense les athlètes qui maîtrisent chaque phase. Kraft excelle dans:</p><ul><li><strong>Position d''élan</strong>: Approche aérodynamique et stable</li><li><strong>Timing de décollage</strong>: Puissance explosive au bon moment</li><li><strong>Position de vol</strong>: Style V optimal pour distance maximale</li><li><strong>Atterrissage</strong>: Telemark constant pour les points de style</li></ul><h2>Force mentale</h2><p>Kraft a montré une capacité remarquable à gérer la pression.</p><h2>Sites clés</h2><p>Kraft a brillé à <a href=\"/planica-venue-guide/\">Planica</a>. Au <a href=\"/innsbruck-venue-guide/\">Bergisel</a> à Innsbruck, il ravit les fans autrichiens.</p><h2>Tournée des quatre tremplins</h2><p>La prestigieuse Tournée des quatre tremplins a été un objectif pour Kraft.</p></article>",

  "it": "<article><h2>Detentore del record mondiale</h2><p>Stefan Kraft è diventato una leggenda il 18 marzo 2017, quando ha volato 253,5 metri a Vikersund, Norvegia. Questo salto da record ha mostrato tutto ciò che rende Kraft speciale.</p><h2>Momenti salienti della carriera</h2><p>Nato il 13 maggio 1993 a Schwarzach im Pongau, Austria, Kraft ha accumulato un''impressionante collezione di successi.</p><h2>Eccellenza tecnica</h2><p>Il <a href=\"/ski-jumping-scoring-technique/\">salto con gli sci</a> premia gli atleti che padroneggiano ogni fase. Kraft eccelle in:</p><ul><li><strong>Posizione di rincorsa</strong>: Approccio aerodinamico e stabile</li><li><strong>Timing di decollo</strong>: Potenza esplosiva al momento giusto</li><li><strong>Posizione di volo</strong>: Stile V ottimale per massima distanza</li><li><strong>Atterraggio</strong>: Telemark costante per punti di stile</li></ul><h2>Forza mentale</h2><p>Kraft ha mostrato notevole capacità di gestire la pressione.</p><h2>Sedi chiave</h2><p>Kraft ha brillato a <a href=\"/planica-venue-guide/\">Planica</a>. Al <a href=\"/innsbruck-venue-guide/\">Bergisel</a> a Innsbruck, entusiasma i fan austriaci.</p><h2>Torneo dei Quattro Trampolini</h2><p>Il prestigioso Torneo dei Quattro Trampolini è stato un obiettivo per Kraft.</p></article>",

  "es": "<article><h2>Poseedor del récord mundial</h2><p>Stefan Kraft se convirtió en leyenda el 18 de marzo de 2017, cuando voló 253,5 metros en Vikersund, Noruega. Este salto récord mostró todo lo que hace especial a Kraft.</p><h2>Puntos destacados de carrera</h2><p>Nacido el 13 de mayo de 1993 en Schwarzach im Pongau, Austria, Kraft ha acumulado una impresionante colección de logros.</p><h2>Excelencia técnica</h2><p>El <a href=\"/ski-jumping-scoring-technique/\">salto de esquí</a> premia a los atletas que dominan cada fase. Kraft sobresale en:</p><ul><li><strong>Posición de impulso</strong>: Aproximación aerodinámica y estable</li><li><strong>Timing de despegue</strong>: Potencia explosiva en el momento correcto</li><li><strong>Posición de vuelo</strong>: Estilo V óptimo para máxima distancia</li></ul><h2>Fuerza mental</h2><p>Kraft ha mostrado notable capacidad para manejar la presión.</p><h2>Sedes clave</h2><p>Kraft ha brillado en <a href=\"/planica-venue-guide/\">Planica</a>. En <a href=\"/innsbruck-venue-guide/\">Bergisel</a> en Innsbruck, emociona a los fans austríacos.</p></article>",

  "pt": "<article><h2>Detentor do recorde mundial</h2><p>Stefan Kraft se tornou uma lenda em 18 de março de 2017, quando voou 253,5 metros em Vikersund, Noruega. Este salto recorde mostrou tudo o que torna Kraft especial.</p><h2>Destaques da carreira</h2><p>Nascido em 13 de maio de 1993 em Schwarzach im Pongau, Áustria, Kraft acumulou uma impressionante coleção de conquistas.</p><h2>Excelência técnica</h2><p>O <a href=\"/ski-jumping-scoring-technique/\">salto de esqui</a> recompensa atletas que dominam cada fase. Kraft se destaca em:</p><ul><li><strong>Posição de aproximação</strong>: Abordagem aerodinâmica e estável</li><li><strong>Timing de decolagem</strong>: Potência explosiva no momento certo</li><li><strong>Posição de voo</strong>: Estilo V ideal para distância máxima</li></ul><h2>Força mental</h2><p>Kraft mostrou notável capacidade de lidar com pressão.</p><h2>Locais principais</h2><p>Kraft brilhou em <a href=\"/planica-venue-guide/\">Planica</a>. No <a href=\"/innsbruck-venue-guide/\">Bergisel</a> em Innsbruck, ele emociona os fãs austríacos.</p></article>",

  "nl": "<article><h2>Wereldrecordhouder</h2><p>Stefan Kraft werd een legende op 18 maart 2017, toen hij 253,5 meter vloog in Vikersund, Noorwegen. Deze wereldrecordsprong toonde alles wat Kraft speciaal maakt.</p><h2>Carrièrehoogtepunten</h2><p>Geboren op 13 mei 1993 in Schwarzach im Pongau, Oostenrijk, heeft Kraft een indrukwekkende verzameling prestaties verzameld.</p><h2>Technische excellentie</h2><p><a href=\"/ski-jumping-scoring-technique/\">Schansspringen</a> beloont atleten die elke fase beheersen. Kraft blinkt uit in:</p><ul><li><strong>Aanlooppositie</strong>: Aerodynamische en stabiele aanloop</li><li><strong>Afzettiming</strong>: Explosieve kracht op het juiste moment</li><li><strong>Vliegpositie</strong>: Optimale V-stijl voor maximale afstand</li></ul><h2>Mentale kracht</h2><p>Kraft heeft opmerkelijk vermogen getoond om met druk om te gaan.</p><h2>Belangrijke locaties</h2><p>Kraft heeft briljant gepresteerd in <a href=\"/planica-venue-guide/\">Planica</a>.</p></article>",

  "ar": "<article><h2>حامل الرقم القياسي العالمي</h2><p>أصبح ستيفان كرافت أسطورة في 18 مارس 2017، عندما طار 253.5 متر في فيكرسوند، النرويج. هذه القفزة القياسية أظهرت كل ما يجعل كرافت مميزًا.</p><h2>أبرز محطات المسيرة</h2><p>ولد في 13 مايو 1993 في شفارتساخ إم بونغاو، النمسا، وجمع كرافت مجموعة مثيرة للإعجاب من الإنجازات.</p><h2>التميز التقني</h2><p><a href=\"/ski-jumping-scoring-technique/\">القفز على الجليد</a> يكافئ الرياضيين الذين يتقنون كل مرحلة. كرافت يتفوق في:</p><ul><li><strong>وضع الانطلاق</strong>: مقاربة ديناميكية هوائية ومستقرة</li><li><strong>توقيت الإقلاع</strong>: قوة انفجارية في اللحظة المناسبة</li><li><strong>وضع الطيران</strong>: أسلوب V الأمثل لأقصى مسافة</li></ul><h2>القوة الذهنية</h2><p>أظهر كرافت قدرة ملحوظة على التعامل مع الضغط.</p><h2>الأماكن الرئيسية</h2><p>تألق كرافت في <a href=\"/planica-venue-guide/\">بلانيكا</a>.</p></article>",

  "ja": "<article><h2>世界記録保持者</h2><p>シュテファン・クラフトは2017年3月18日、ノルウェーのヴィケルスンドで253.5メートルを飛んで伝説となりました。この世界記録ジャンプはクラフトを特別にするすべてを示しました。</p><h2>キャリアハイライト</h2><p>1993年5月13日、オーストリアのシュヴァルツァッハ・イム・ポンガウ生まれのクラフトは、印象的な実績を積み重ねてきました。</p><h2>技術的卓越性</h2><p><a href=\"/ski-jumping-scoring-technique/\">スキージャンプ</a>はすべての段階をマスターした選手を評価します。クラフトが優れている点：</p><ul><li><strong>助走姿勢</strong>：空力的で安定したアプローチ</li><li><strong>踏切タイミング</strong>：適切なタイミングでの爆発的なパワー</li><li><strong>飛行姿勢</strong>：最大距離のための最適なV字スタイル</li></ul><h2>精神的強さ</h2><p>クラフトはプレッシャーに対処する驚くべき能力を示しています。</p><h2>主要会場</h2><p>クラフトは<a href=\"/planica-venue-guide/\">プラニツァ</a>で素晴らしいパフォーマンスを見せています。</p></article>",

  "zh": "<article><h2>世界纪录保持者</h2><p>斯特凡·克拉夫特于2017年3月18日成为传奇，当时他在挪威维克松德飞行了253.5米。这一世界纪录跳跃展示了克拉夫特的所有特质。</p><h2>职业生涯亮点</h2><p>1993年5月13日出生于奥地利蓬高地区施瓦察赫，克拉夫特积累了令人印象深刻的成就。</p><h2>技术卓越</h2><p><a href=\"/ski-jumping-scoring-technique/\">跳台滑雪</a>奖励掌握每个阶段的运动员。克拉夫特擅长：</p><ul><li><strong>助滑姿势</strong>：空气动力学和稳定的接近</li><li><strong>起跳时机</strong>：在正确时刻的爆发力</li><li><strong>飞行姿势</strong>：最大距离的最佳V型</li></ul><h2>心理力量</h2><p>克拉夫特展示了处理压力的非凡能力。</p><h2>主要场馆</h2><p>克拉夫特在<a href=\"/planica-venue-guide/\">普拉尼察</a>表现出色。</p></article>",

  "ko": "<article><h2>세계 기록 보유자</h2><p>슈테판 크라프트는 2017년 3월 18일 노르웨이 비케르순드에서 253.5미터를 날아 전설이 되었습니다. 이 세계 기록 점프는 크라프트를 특별하게 만드는 모든 것을 보여주었습니다.</p><h2>커리어 하이라이트</h2><p>1993년 5월 13일 오스트리아 슈바르차흐 임 퐁가우에서 태어난 크라프트는 인상적인 업적을 쌓아왔습니다.</p><h2>기술적 우수성</h2><p><a href=\"/ski-jumping-scoring-technique/\">스키점프</a>는 모든 단계를 마스터한 선수를 보상합니다. 크라프트가 뛰어난 점:</p><ul><li><strong>활주 자세</strong>: 공기역학적이고 안정적인 접근</li><li><strong>도약 타이밍</strong>: 적절한 순간의 폭발적인 힘</li><li><strong>비행 자세</strong>: 최대 거리를 위한 최적의 V스타일</li></ul><h2>정신적 강인함</h2><p>크라프트는 압박을 다루는 놀라운 능력을 보여주었습니다.</p><h2>주요 경기장</h2><p>크라프트는 <a href=\"/planica-venue-guide/\">플라니차</a>에서 훌륭하게 활약했습니다.</p></article>"
}'::jsonb,

'athlete-profile',
'SJ',

-- Meta descriptions
'{
  "en": "Stefan Kraft profile: Austrian ski jumping legend and world record holder (253.5m). Career highlights, technique analysis, and Four Hills Tournament success.",
  "de": "Stefan Kraft Profil: Österreichische Skisprung-Legende und Weltrekordhalter (253,5m). Karrierehöhepunkte, Technikanalyse und Vierschanzentournee-Erfolg.",
  "fr": "Profil de Stefan Kraft: légende autrichienne du saut à ski et détenteur du record mondial. Points forts, analyse technique et succès à la Tournée des quatre tremplins.",
  "it": "Profilo di Stefan Kraft: leggenda austriaca del salto con gli sci e detentore del record mondiale. Momenti salienti, analisi tecnica e successi al Torneo dei Quattro Trampolini.",
  "es": "Perfil de Stefan Kraft: leyenda austríaca del salto de esquí y poseedor del récord mundial. Momentos destacados, análisis técnico y éxito en el Torneo de los Cuatro Trampolines.",
  "pt": "Perfil de Stefan Kraft: lenda austríaca do salto de esqui e detentor do recorde mundial. Destaques, análise técnica e sucesso no Torneio dos Quatro Trampolins.",
  "nl": "Stefan Kraft profiel: Oostenrijkse schansspringlegend en wereldrecordhouder. Carrièrehoogtepunten, techniekanalyse en Vierschansentoernooi succes.",
  "ar": "ملف ستيفان كرافت: أسطورة القفز على الجليد النمساوية وحامل الرقم القياسي العالمي. أبرز المحطات وتحليل التقنية ونجاح بطولة التلال الأربعة.",
  "ja": "シュテファン・クラフトプロフィール：オーストリアのスキージャンプ伝説と世界記録保持者。キャリアハイライト、技術分析、ジャンプ週間の成功。",
  "zh": "斯特凡·克拉夫特简介：奥地利跳台滑雪传奇和世界纪录保持者。职业亮点、技术分析和四山赛成功。",
  "ko": "슈테판 크라프트 프로필: 오스트리아 스키점프 전설이자 세계 기록 보유자. 커리어 하이라이트, 기술 분석, 포힐스 토너먼트 성공."
}'::jsonb,

'published',
NOW(),
'evergreen');
