-- Migration: 018_athlete_vlhova.sql
-- Petra Vlhova athlete profile (Slovak slalom specialist)

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type)
VALUES (
    'petra-vlhova-profile',
    '{
        "en": "Petra Vlhova: Slovakia''s Slalom Queen",
        "de": "Petra Vlhova: Slowakeis Slalom-Konigin",
        "fr": "Petra Vlhova : La Reine du Slalom Slovaque",
        "it": "Petra Vlhova: La Regina dello Slalom Slovacca",
        "es": "Petra Vlhova: La Reina del Eslalon Eslovaca",
        "pt": "Petra Vlhova: A Rainha do Slalom Eslovaca",
        "nl": "Petra Vlhova: Slowakije''s Slalom Koningin",
        "ar": "بيترا فلهوفا: ملكة التزلج المتعرج السلوفاكية",
        "ja": "ペトラ・ブルホバ：スロバキアのスラローム女王",
        "zh": "佩特拉·弗尔霍娃：斯洛伐克回转女王",
        "ko": "페트라 블호바: 슬로바키아의 회전 여왕"
    }',
    '{
        "en": "Meet Petra Vlhova, the Slovak ski racing star who became a national hero by winning her country''s first ever skiing gold medal.",
        "de": "Lernen Sie Petra Vlhova kennen, den slowakischen Skistar, der durch den Gewinn der ersten Ski-Goldmedaille ihres Landes zur Nationalheldin wurde.",
        "fr": "Decouvrez Petra Vlhova, la star slovaque du ski qui est devenue une heroine nationale en remportant la premiere medaille d''or de ski de son pays.",
        "it": "Scopri Petra Vlhova, la star slovacca dello sci che e diventata un''eroina nazionale vincendo la prima medaglia d''oro nello sci del suo paese.",
        "es": "Conoce a Petra Vlhova, la estrella eslovaca del esqui que se convirtio en heroina nacional al ganar la primera medalla de oro en esqui de su pais.",
        "pt": "Conheca Petra Vlhova, a estrela eslovaca do esqui que se tornou heroina nacional ao conquistar a primeira medalha de ouro do esqui de seu pais.",
        "nl": "Maak kennis met Petra Vlhova, de Slowaakse skister die een nationale heldin werd door de eerste gouden skimedaille van haar land te winnen.",
        "ar": "تعرف على بيترا فلهوفا، نجمة التزلج السلوفاكية التي أصبحت بطلة وطنية بفوزها بأول ميدالية ذهبية في التزلج لبلادها.",
        "ja": "スロバキア初のスキー金メダルを獲得し、国民的英雄となったスロバキアのスキースター、ペトラ・ブルホバを紹介します。",
        "zh": "认识佩特拉·弗尔霍娃，这位斯洛伐克滑雪明星为祖国赢得了首枚滑雪金牌，成为民族英雄。",
        "ko": "슬로바키아 최초의 스키 금메달을 획득하여 국가 영웅이 된 슬로바키아 스키 스타 페트라 블호바를 만나보세요."
    }',
    '{
        "en": "<h2>A Nation''s First Champion</h2><p>Petra Vlhova made history by becoming Slovakia''s most successful skier ever. In a country with limited skiing tradition, she rose to become one of the best <a href=\"/alpine-skiing-guide/\">alpine skiers</a> in the world.</p><p>Born in 1995 in Liptovsky Mikulas, a small town in northern Slovakia, Vlhova grew up skiing in the Jasna resort. Unlike many top skiers from bigger nations, she had to work harder for training opportunities and funding.</p><h2>Technical Excellence</h2><p>Vlhova is known for her incredible slalom skills. She has:</p><ul><li>Won 30+ World Cup races</li><li>Overall World Cup champion (2020-21 season)</li><li>Multiple slalom globe winner</li><li>Giant slalom victories too</li></ul><p>Her technique is unique. She skis very close to the gates, taking aggressive lines that others cannot match. This style requires perfect timing and incredible reflexes.</p><h2>The Big Breakthrough</h2><p>Vlhova''s biggest moment came when she won the slalom gold at the 2022 Games. This was Slovakia''s first ever skiing medal at the top level. The whole nation celebrated.</p><p>Her victory was extra special because she beat her biggest rival <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> in a dramatic race. The two have had one of skiing''s greatest rivalries in slalom.</p><h2>Racing Style</h2><p>What makes Vlhova special:</p><ul><li>Extremely aggressive gate contact</li><li>Late timing that builds speed</li><li>Strong second runs under pressure</li><li>Mental toughness in big races</li></ul><h2>Beyond Slalom</h2><p>While slalom is her best event, Vlhova has shown she can compete in giant slalom too. She has won races in both disciplines, making her a true technical specialist.</p><h2>Looking Ahead</h2><p>Vlhova continues to be a top contender in every slalom race. Her rivalry with Shiffrin keeps pushing both athletes to new heights. For Slovakia, she has opened doors for future skiers and shown what is possible.</p><p>Watch her race this season in <a href=\"/alpine-skiing-guide/\">alpine skiing</a> events across Europe and North America.</p>",
        "de": "<h2>Die erste Meisterin einer Nation</h2><p>Petra Vlhova schrieb Geschichte als erfolgreichste Skifahrerin der Slowakei aller Zeiten. In einem Land mit begrenzter Skitradition stieg sie zu einer der besten <a href=\"/alpine-skiing-guide/\">Alpinskifahrerinnen</a> der Welt auf.</p><p>1995 in Liptovsky Mikulas, einer kleinen Stadt in der Nordslowakei, geboren, wuchs Vlhova im Skigebiet Jasna auf. Anders als viele Spitzenskifahrer aus grosseren Nationen musste sie harter fur Trainingsmoglichkeiten und Finanzierung arbeiten.</p><h2>Technische Exzellenz</h2><p>Vlhova ist fur ihre unglaublichen Slalomfahigkeiten bekannt. Sie hat:</p><ul><li>Uber 30 Weltcuprennen gewonnen</li><li>Gesamtweltcupsiegerin (Saison 2020-21)</li><li>Mehrfache Slalom-Kugelgewinnerin</li><li>Auch Riesenslalom-Siege</li></ul><p>Ihre Technik ist einzigartig. Sie fahrt sehr nah an den Toren und wahlt aggressive Linien, die andere nicht nachahmen konnen. Dieser Stil erfordert perfektes Timing und unglaubliche Reflexe.</p><h2>Der grosse Durchbruch</h2><p>Vlhovas grosster Moment kam, als sie 2022 die Slalom-Goldmedaille gewann. Dies war die erste Skimedaille der Slowakei auf hochstem Niveau uberhaupt. Die ganze Nation feierte.</p><p>Ihr Sieg war besonders speziell, weil sie ihre grosste Rivalin <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> in einem dramatischen Rennen schlug. Die beiden haben eine der grossten Rivalitaten des Skisports im Slalom.</p><h2>Rennstil</h2><p>Was Vlhova besonders macht:</p><ul><li>Extrem aggressiver Torkontakt</li><li>Spates Timing, das Geschwindigkeit aufbaut</li><li>Starke zweite Laufe unter Druck</li><li>Mentale Starke bei grossen Rennen</li></ul><h2>Uber den Slalom hinaus</h2><p>Wahrend Slalom ihre beste Disziplin ist, hat Vlhova gezeigt, dass sie auch im Riesenslalom konkurrieren kann. Sie hat Rennen in beiden Disziplinen gewonnen und ist damit eine echte Technikspezialistin.</p><h2>Ausblick</h2><p>Vlhova ist weiterhin eine Top-Anwarterin in jedem Slalomrennen. Ihre Rivalitat mit Shiffrin treibt beide Athletinnen zu neuen Hochstleistungen. Fur die Slowakei hat sie Turen fur zukunftige Skifahrer geoffnet und gezeigt, was moglich ist.</p><p>Sehen Sie sie diese Saison bei <a href=\"/alpine-skiing-guide/\">Alpinski</a>-Veranstaltungen in Europa und Nordamerika.</p>",
        "fr": "<h2>La Premiere Championne d''une Nation</h2><p>Petra Vlhova a fait l''histoire en devenant la skieuse la plus titr ee de Slovaquie. Dans un pays a tradition de ski limitee, elle s''est hissee parmi les meilleures <a href=\"/alpine-skiing-guide/\">skieuses alpines</a> du monde.</p><p>Nee en 1995 a Liptovsky Mikulas, une petite ville du nord de la Slovaquie, Vlhova a grandi en skiant a la station de Jasna. Contrairement a de nombreuses skieuses de pointe de nations plus grandes, elle a du travailler plus dur pour obtenir des opportunites d''entrainement et du financement.</p><h2>Excellence Technique</h2><p>Vlhova est connue pour ses incroyables competences en slalom. Elle a:</p><ul><li>Remporte plus de 30 courses de Coupe du monde</li><li>Championne du classement general de la Coupe du monde (saison 2020-21)</li><li>Multiple vainqueur du globe de slalom</li><li>Des victoires en slalom geant aussi</li></ul><p>Sa technique est unique. Elle skie tres pres des portes, prenant des lignes agressives que d''autres ne peuvent pas egaler. Ce style necessite un timing parfait et des reflexes incroyables.</p><h2>La Grande Percee</h2><p>Le plus grand moment de Vlhova est arrive quand elle a remporte l''or en slalom aux Jeux de 2022. C''etait la toute premiere medaille de ski de la Slovaquie au plus haut niveau. Toute la nation a celebre.</p><p>Sa victoire etait d''autant plus speciale qu''elle a battu sa plus grande rivale <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> dans une course dramatique. Les deux ont une des plus grandes rivalites du ski en slalom.</p><h2>Style de Course</h2><p>Ce qui rend Vlhova speciale:</p><ul><li>Contact de porte extremement agressif</li><li>Timing tardif qui accumule la vitesse</li><li>Secondes manches solides sous pression</li><li>Force mentale dans les grandes courses</li></ul><h2>Au-dela du Slalom</h2><p>Bien que le slalom soit sa meilleure epreuve, Vlhova a montre qu''elle peut concourir en slalom geant aussi. Elle a gagne des courses dans les deux disciplines, ce qui fait d''elle une vraie specialiste technique.</p><h2>Perspectives</h2><p>Vlhova continue d''etre une favorite dans chaque course de slalom. Sa rivalite avec Shiffrin pousse les deux athletes vers de nouveaux sommets. Pour la Slovaquie, elle a ouvert des portes pour les futurs skieurs et montre ce qui est possible.</p><p>Regardez-la courir cette saison dans les epreuves de <a href=\"/alpine-skiing-guide/\">ski alpin</a> a travers l''Europe et l''Amerique du Nord.</p>",
        "it": "<h2>La Prima Campionessa di una Nazione</h2><p>Petra Vlhova ha fatto la storia diventando la sciatrice slovacca di maggior successo di sempre. In un paese con tradizione sciistica limitata, e diventata una delle migliori <a href=\"/alpine-skiing-guide/\">sciatrici alpine</a> del mondo.</p><p>Nata nel 1995 a Liptovsky Mikulas, una piccola citta nel nord della Slovacchia, Vlhova e cresciuta sciando nella stazione di Jasna. A differenza di molte sciatrici di punta di nazioni piu grandi, ha dovuto lavorare piu duramente per opportunita di allenamento e finanziamenti.</p><h2>Eccellenza Tecnica</h2><p>Vlhova e nota per le sue incredibili abilita nello slalom. Ha:</p><ul><li>Vinto oltre 30 gare di Coppa del Mondo</li><li>Campionessa generale di Coppa del Mondo (stagione 2020-21)</li><li>Vincitrice multipla della coppa di slalom</li><li>Anche vittorie in slalom gigante</li></ul><p>La sua tecnica e unica. Scia molto vicino alle porte, prendendo linee aggressive che altri non possono eguagliare. Questo stile richiede un timing perfetto e riflessi incredibili.</p><h2>La Grande Svolta</h2><p>Il momento piu grande di Vlhova e arrivato quando ha vinto l''oro nello slalom ai Giochi del 2022. Questa e stata la prima medaglia di sci della Slovacchia al massimo livello. L''intera nazione ha festeggiato.</p><p>La sua vittoria e stata ancora piu speciale perche ha battuto la sua piu grande rivale <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> in una gara drammatica. Le due hanno una delle piu grandi rivalita dello sci nello slalom.</p><h2>Stile di Gara</h2><p>Cosa rende Vlhova speciale:</p><ul><li>Contatto con le porte estremamente aggressivo</li><li>Timing ritardato che costruisce velocita</li><li>Seconde manche forti sotto pressione</li><li>Forza mentale nelle grandi gare</li></ul><h2>Oltre lo Slalom</h2><p>Mentre lo slalom e la sua migliore specialita, Vlhova ha dimostrato di poter competere anche in slalom gigante. Ha vinto gare in entrambe le discipline, rendendola una vera specialista tecnica.</p><h2>Guardando Avanti</h2><p>Vlhova continua a essere una delle favorite in ogni gara di slalom. La sua rivalita con Shiffrin spinge entrambe le atlete verso nuove vette. Per la Slovacchia, ha aperto le porte per i futuri sciatori e mostrato cosa e possibile.</p><p>Guardala gareggiare questa stagione negli eventi di <a href=\"/alpine-skiing-guide/\">sci alpino</a> in Europa e Nord America.</p>",
        "es": "<h2>La Primera Campeona de una Nacion</h2><p>Petra Vlhova hizo historia al convertirse en la esquiadora mas exitosa de Eslovaquia. En un pais con tradicion limitada de esqui, se convirtio en una de las mejores <a href=\"/alpine-skiing-guide/\">esquiadoras alpinas</a> del mundo.</p><p>Nacida en 1995 en Liptovsky Mikulas, una pequena ciudad en el norte de Eslovaquia, Vlhova crecio esquiando en la estacion de Jasna. A diferencia de muchas esquiadoras de paises mas grandes, tuvo que trabajar mas duro para obtener oportunidades de entrenamiento y financiacion.</p><h2>Excelencia Tecnica</h2><p>Vlhova es conocida por sus increibles habilidades en eslalon. Ella ha:</p><ul><li>Ganado mas de 30 carreras de Copa del Mundo</li><li>Campeona general de la Copa del Mundo (temporada 2020-21)</li><li>Multiple ganadora del globo de eslalon</li><li>Tambien victorias en eslalon gigante</li></ul><p>Su tecnica es unica. Esquia muy cerca de las puertas, tomando lineas agresivas que otros no pueden igualar. Este estilo requiere un timing perfecto y reflejos increibles.</p><h2>El Gran Avance</h2><p>El mayor momento de Vlhova llego cuando gano el oro en eslalon en los Juegos de 2022. Esta fue la primera medalla de esqui de Eslovaquia al mas alto nivel. Toda la nacion celebro.</p><p>Su victoria fue aun mas especial porque vencio a su mayor rival <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> en una carrera dramatica. Las dos tienen una de las mayores rivalidades del esqui en eslalon.</p><h2>Estilo de Carrera</h2><p>Lo que hace especial a Vlhova:</p><ul><li>Contacto con las puertas extremadamente agresivo</li><li>Timing tardio que construye velocidad</li><li>Segundas mangas fuertes bajo presion</li><li>Fortaleza mental en grandes carreras</li></ul><h2>Mas Alla del Eslalon</h2><p>Aunque el eslalon es su mejor prueba, Vlhova ha demostrado que puede competir en eslalon gigante tambien. Ha ganado carreras en ambas disciplinas, lo que la convierte en una verdadera especialista tecnica.</p><h2>Mirando Adelante</h2><p>Vlhova continua siendo una de las favoritas en cada carrera de eslalon. Su rivalidad con Shiffrin sigue empujando a ambas atletas hacia nuevas alturas. Para Eslovaquia, ha abierto puertas para futuros esquiadores y mostrado lo que es posible.</p><p>Mirala competir esta temporada en eventos de <a href=\"/alpine-skiing-guide/\">esqui alpino</a> en Europa y Norteamerica.</p>",
        "pt": "<h2>A Primeira Campea de uma Nacao</h2><p>Petra Vlhova fez historia ao se tornar a esquiadora mais bem-sucedida da Eslovaquia. Em um pais com tradicao limitada de esqui, ela se tornou uma das melhores <a href=\"/alpine-skiing-guide/\">esquiadoras alpinas</a> do mundo.</p><p>Nascida em 1995 em Liptovsky Mikulas, uma pequena cidade no norte da Eslovaquia, Vlhova cresceu esquiando na estacao de Jasna. Ao contrario de muitas esquiadoras de paises maiores, ela teve que trabalhar mais para conseguir oportunidades de treinamento e financiamento.</p><h2>Excelencia Tecnica</h2><p>Vlhova e conhecida por suas incriveis habilidades no slalom. Ela:</p><ul><li>Venceu mais de 30 corridas da Copa do Mundo</li><li>Campea geral da Copa do Mundo (temporada 2020-21)</li><li>Multipla vencedora do globo de slalom</li><li>Tambem vitorias no slalom gigante</li></ul><p>Sua tecnica e unica. Ela esquia muito perto das portas, tomando linhas agressivas que outros nao conseguem igualar. Este estilo requer timing perfeito e reflexos incriveis.</p><h2>A Grande Conquista</h2><p>O maior momento de Vlhova veio quando ela ganhou o ouro no slalom nos Jogos de 2022. Esta foi a primeira medalha de esqui da Eslovaquia no mais alto nivel. Toda a nacao celebrou.</p><p>Sua vitoria foi ainda mais especial porque ela venceu sua maior rival <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> em uma corrida dramatica. As duas tem uma das maiores rivalidades do esqui no slalom.</p><h2>Estilo de Corrida</h2><p>O que torna Vlhova especial:</p><ul><li>Contato com as portas extremamente agressivo</li><li>Timing tardio que constroi velocidade</li><li>Segundas descidas fortes sob pressao</li><li>Forca mental em grandes corridas</li></ul><h2>Alem do Slalom</h2><p>Embora o slalom seja sua melhor prova, Vlhova mostrou que pode competir no slalom gigante tambem. Ela venceu corridas em ambas as disciplinas, tornando-a uma verdadeira especialista tecnica.</p><h2>Olhando para o Futuro</h2><p>Vlhova continua sendo uma das favoritas em cada corrida de slalom. Sua rivalidade com Shiffrin continua empurrando ambas as atletas para novas alturas. Para a Eslovaquia, ela abriu portas para futuros esquiadores e mostrou o que e possivel.</p><p>Assista-a competir nesta temporada em eventos de <a href=\"/alpine-skiing-guide/\">esqui alpino</a> na Europa e America do Norte.</p>",
        "nl": "<h2>De Eerste Kampioene van een Natie</h2><p>Petra Vlhova maakte geschiedenis door de meest succesvolle Slowaakse skister ooit te worden. In een land met een beperkte skitraditie groeide ze uit tot een van de beste <a href=\"/alpine-skiing-guide/\">alpineskisters</a> ter wereld.</p><p>Geboren in 1995 in Liptovsky Mikulas, een kleine stad in het noorden van Slowakije, groeide Vlhova op met skien in het Jasna resort. Anders dan veel topskisters uit grotere landen moest ze harder werken voor trainingsmogelijkheden en financiering.</p><h2>Technische Excellentie</h2><p>Vlhova staat bekend om haar ongelooflijke slalomvaardigheden. Ze heeft:</p><ul><li>Meer dan 30 Wereldbekeroverwinningen</li><li>Algemeen Wereldbekerkampioene (seizoen 2020-21)</li><li>Meervoudig slalombol winnares</li><li>Ook reuzenslalom overwinningen</li></ul><p>Haar techniek is uniek. Ze skiet heel dicht bij de poorten en neemt agressieve lijnen die anderen niet kunnen evenaren. Deze stijl vereist perfecte timing en ongelooflijke reflexen.</p><h2>De Grote Doorbraak</h2><p>Vlhova''s grootste moment kwam toen ze goud won in de slalom op de Spelen van 2022. Dit was de allereerste skimedaille van Slowakije op het hoogste niveau. Het hele land vierde feest.</p><p>Haar overwinning was extra speciaal omdat ze haar grootste rivaal <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> versloeg in een dramatische race. De twee hebben een van de grootste rivaliteiten van het skien in de slalom.</p><h2>Racestijl</h2><p>Wat Vlhova speciaal maakt:</p><ul><li>Extreem agressief poortcontact</li><li>Late timing die snelheid opbouwt</li><li>Sterke tweede runs onder druk</li><li>Mentale kracht in grote races</li></ul><h2>Voorbij de Slalom</h2><p>Hoewel slalom haar beste onderdeel is, heeft Vlhova laten zien dat ze ook kan concurreren in de reuzenslalom. Ze heeft races gewonnen in beide disciplines, wat haar een echte technische specialist maakt.</p><h2>Vooruitkijkend</h2><p>Vlhova blijft een topkandidaat in elke slalomrace. Haar rivaliteit met Shiffrin blijft beide atleten naar nieuwe hoogtes pushen. Voor Slowakije heeft ze deuren geopend voor toekomstige skisters en laten zien wat mogelijk is.</p><p>Bekijk haar racen dit seizoen in <a href=\"/alpine-skiing-guide/\">alpineski</a> evenementen door Europa en Noord-Amerika.</p>",
        "ar": "<h2>أول بطلة لأمتها</h2><p>صنعت بيترا فلهوفا التاريخ بأن أصبحت أنجح متزلجة سلوفاكية على الإطلاق. في بلد ذي تقاليد محدودة في التزلج، ارتقت لتصبح واحدة من أفضل <a href=\"/alpine-skiing-guide/\">متزلجات جبال الألب</a> في العالم.</p><p>ولدت في عام 1995 في ليبتوفسكي ميكولاش، وهي بلدة صغيرة في شمال سلوفاكيا، ونشأت فلهوفا وهي تتزلج في منتجع ياسنا. على عكس العديد من المتزلجات البارزات من دول أكبر، كان عليها العمل بجد أكبر للحصول على فرص التدريب والتمويل.</p><h2>التميز التقني</h2><p>تشتهر فلهوفا بمهاراتها المذهلة في التزلج المتعرج. لقد:</p><ul><li>فازت بأكثر من 30 سباقاً في كأس العالم</li><li>بطلة كأس العالم العامة (موسم 2020-21)</li><li>فائزة متعددة بكرة التزلج المتعرج</li><li>انتصارات في التزلج المتعرج العملاق أيضاً</li></ul><p>تقنيتها فريدة. تتزلج قريباً جداً من البوابات، متخذة خطوطاً عدوانية لا يستطيع الآخرون مجاراتها. يتطلب هذا الأسلوب توقيتاً مثالياً وردود فعل مذهلة.</p><h2>الإنجاز الكبير</h2><p>جاءت أعظم لحظة لفلهوفا عندما فازت بذهبية التزلج المتعرج في دورة 2022. كانت هذه أول ميدالية تزلج لسلوفاكيا على أعلى مستوى. احتفلت الأمة بأكملها.</p><p>كان انتصارها مميزاً بشكل خاص لأنها هزمت منافستها الأكبر <a href=\"/mikaela-shiffrin-profile/\">ميكايلا شيفرين</a> في سباق درامي. الاثنتان لديهما واحدة من أعظم المنافسات في التزلج المتعرج.</p><h2>أسلوب السباق</h2><p>ما يجعل فلهوفا مميزة:</p><ul><li>اتصال عدواني للغاية بالبوابات</li><li>توقيت متأخر يبني السرعة</li><li>جولات ثانية قوية تحت الضغط</li><li>قوة عقلية في السباقات الكبرى</li></ul><h2>ما وراء التزلج المتعرج</h2><p>بينما التزلج المتعرج هو أفضل أحداثها، أظهرت فلهوفا أنها تستطيع المنافسة في التزلج المتعرج العملاق أيضاً. فازت بسباقات في كلا التخصصين، مما يجعلها متخصصة تقنية حقيقية.</p><h2>نظرة للمستقبل</h2><p>تستمر فلهوفا في كونها منافسة بارزة في كل سباق تزلج متعرج. منافستها مع شيفرين تستمر في دفع كلتا الرياضيتين نحو آفاق جديدة. بالنسبة لسلوفاكيا، فتحت الأبواب للمتزلجين المستقبليين وأظهرت ما هو ممكن.</p><p>شاهدها تتسابق هذا الموسم في فعاليات <a href=\"/alpine-skiing-guide/\">التزلج الألبي</a> عبر أوروبا وأمريكا الشمالية.</p>",
        "ja": "<h2>国家初のチャンピオン</h2><p>ペトラ・ブルホバは、スロバキア史上最も成功したスキーヤーとなり歴史を作りました。スキーの伝統が限られた国で、彼女は世界最高の<a href=\"/alpine-skiing-guide/\">アルペンスキーヤー</a>の一人にまで上り詰めました。</p><p>1995年にスロバキア北部の小さな町リプトフスキー・ミクラーシュで生まれたブルホバは、ヤスナリゾートでスキーをして育ちました。大国の多くのトップスキーヤーとは異なり、彼女はトレーニングの機会と資金を得るためにより懸命に働かなければなりませんでした。</p><h2>技術的卓越性</h2><p>ブルホバは信じられないほどのスラロームスキルで知られています。彼女は：</p><ul><li>30以上のワールドカップレースで優勝</li><li>ワールドカップ総合チャンピオン（2020-21シーズン）</li><li>複数回のスラローム部門優勝</li><li>ジャイアントスラロームでも勝利</li></ul><p>彼女の技術はユニークです。ゲートの非常に近くを滑り、他の選手が真似できない攻撃的なラインを取ります。このスタイルには完璧なタイミングと信じられないほどの反射神経が必要です。</p><h2>大きな飛躍</h2><p>ブルホバの最大の瞬間は、2022年大会でスラロームの金メダルを獲得した時でした。これはスロバキア初の最高レベルでのスキーメダルでした。国中が祝いました。</p><p>彼女の勝利は、劇的なレースで最大のライバル<a href=\"/mikaela-shiffrin-profile/\">ミカエラ・シフリン</a>を破ったため、さらに特別なものでした。二人はスラロームにおけるスキー界最大のライバル関係の一つを持っています。</p><h2>レーススタイル</h2><p>ブルホバを特別にするもの：</p><ul><li>極めて攻撃的なゲートコンタクト</li><li>スピードを築く遅いタイミング</li><li>プレッシャー下での強い2本目</li><li>大きなレースでのメンタルの強さ</li></ul><h2>スラロームを超えて</h2><p>スラロームが彼女の最高の種目である一方、ブルホバはジャイアントスラロームでも競争できることを示しています。彼女は両方の種目でレースに勝ち、真の技術スペシャリストとなっています。</p><h2>今後の展望</h2><p>ブルホバは引き続きすべてのスラロームレースでトップ候補です。シフリンとのライバル関係は、両アスリートを新たな高みへと押し上げ続けています。スロバキアにとって、彼女は将来のスキーヤーのための扉を開き、何が可能かを示しました。</p><p>今シーズン、ヨーロッパと北米の<a href=\"/alpine-skiing-guide/\">アルペンスキー</a>イベントで彼女のレースをご覧ください。</p>",
        "zh": "<h2>国家的首位冠军</h2><p>佩特拉·弗尔霍娃创造了历史，成为斯洛伐克有史以来最成功的滑雪运动员。在一个滑雪传统有限的国家，她成长为世界顶级<a href=\"/alpine-skiing-guide/\">高山滑雪</a>运动员之一。</p><p>弗尔霍娃1995年出生于斯洛伐克北部小镇利普托夫斯基米库拉什，在亚斯纳度假村长大并学习滑雪。与许多来自大国的顶级滑雪运动员不同，她必须更加努力才能获得训练机会和资金支持。</p><h2>技术卓越</h2><p>弗尔霍娃以其令人难以置信的回转技术而闻名。她：</p><ul><li>赢得超过30场世界杯比赛</li><li>世界杯总冠军（2020-21赛季）</li><li>多次回转水晶球得主</li><li>大回转也有胜绩</li></ul><p>她的技术独一无二。她滑行时非常靠近旗门，采取其他人无法匹敌的激进路线。这种风格需要完美的时机和令人难以置信的反应能力。</p><h2>重大突破</h2><p>弗尔霍娃最伟大的时刻是在2022年冬奥会上赢得回转金牌。这是斯洛伐克在最高级别比赛中获得的第一枚滑雪奖牌。整个国家都在庆祝。</p><p>她的胜利格外特别，因为她在一场戏剧性的比赛中击败了最大的对手<a href=\"/mikaela-shiffrin-profile/\">米凯拉·希夫林</a>。两人在回转项目上有着滑雪界最伟大的竞争之一。</p><h2>比赛风格</h2><p>弗尔霍娃的特别之处：</p><ul><li>极其激进的旗门接触</li><li>积累速度的延迟时机</li><li>压力下强劲的第二轮</li><li>大赛中的心理素质</li></ul><h2>超越回转</h2><p>虽然回转是她最好的项目，弗尔霍娃已经证明她也能在大回转中竞争。她在两个项目中都赢得过比赛，使她成为真正的技术专家。</p><h2>展望未来</h2><p>弗尔霍娃继续是每场回转比赛的顶级竞争者。她与希夫林的竞争不断推动两位运动员达到新的高度。对于斯洛伐克来说，她为未来的滑雪运动员打开了大门，展示了什么是可能的。</p><p>本赛季在欧洲和北美的<a href=\"/alpine-skiing-guide/\">高山滑雪</a>赛事中观看她的比赛。</p>",
        "ko": "<h2>국가 최초의 챔피언</h2><p>페트라 블호바는 슬로바키아 역대 가장 성공적인 스키 선수가 되어 역사를 썼습니다. 스키 전통이 제한적인 나라에서 그녀는 세계 최고의 <a href=\"/alpine-skiing-guide/\">알파인 스키</a> 선수 중 한 명으로 성장했습니다.</p><p>1995년 슬로바키아 북부의 작은 도시 립토프스키 미쿨라시에서 태어난 블호바는 야스나 리조트에서 스키를 타며 자랐습니다. 더 큰 나라의 많은 최고 스키 선수들과 달리, 그녀는 훈련 기회와 자금을 얻기 위해 더 열심히 일해야 했습니다.</p><h2>기술적 우수성</h2><p>블호바는 놀라운 회전 실력으로 유명합니다. 그녀는:</p><ul><li>30회 이상의 월드컵 우승</li><li>월드컵 종합 챔피언 (2020-21 시즌)</li><li>다수의 회전 크리스탈 글로브 획득</li><li>대회전에서도 승리</li></ul><p>그녀의 기술은 독특합니다. 그녀는 게이트에 매우 가깝게 스키를 타며 다른 선수들이 따라할 수 없는 공격적인 라인을 선택합니다. 이 스타일은 완벽한 타이밍과 놀라운 반사신경을 필요로 합니다.</p><h2>대단한 돌파구</h2><p>블호바의 가장 큰 순간은 2022년 대회에서 회전 금메달을 획득했을 때였습니다. 이것은 슬로바키아의 최고 수준 최초의 스키 메달이었습니다. 온 나라가 축하했습니다.</p><p>그녀의 승리는 극적인 경기에서 최대 라이벌 <a href=\"/mikaela-shiffrin-profile/\">미카엘라 시프린</a>을 이겼기 때문에 더욱 특별했습니다. 두 선수는 회전에서 스키계 최고의 라이벌 관계 중 하나를 가지고 있습니다.</p><h2>레이싱 스타일</h2><p>블호바를 특별하게 만드는 것:</p><ul><li>극도로 공격적인 게이트 접촉</li><li>속도를 높이는 늦은 타이밍</li><li>압박 속에서 강한 2차 주행</li><li>큰 경기에서의 정신적 강인함</li></ul><h2>회전을 넘어서</h2><p>회전이 그녀의 최고 종목이지만, 블호바는 대회전에서도 경쟁할 수 있음을 보여주었습니다. 그녀는 두 종목 모두에서 우승하여 진정한 기술 전문가가 되었습니다.</p><h2>앞을 내다보며</h2><p>블호바는 모든 회전 경기에서 계속해서 최고의 우승 후보입니다. 시프린과의 경쟁은 두 선수 모두를 새로운 높이로 밀어붙이고 있습니다. 슬로바키아에게 그녀는 미래 스키 선수들을 위한 문을 열고 무엇이 가능한지 보여주었습니다.</p><p>이번 시즌 유럽과 북미 전역의 <a href=\"/alpine-skiing-guide/\">알파인 스키</a> 이벤트에서 그녀의 경기를 시청하세요.</p>"
    }',
    'athlete-profile',
    'ALP',
    '{
        "en": "Petra Vlhova profile: Slovakia''s slalom champion who won her country''s first ever skiing gold medal. Career stats, racing style, and rivalry with Shiffrin.",
        "de": "Petra Vlhova Profil: Slowakeis Slalom-Meisterin, die die erste Ski-Goldmedaille ihres Landes gewann. Karrierestatistiken, Rennstil und Rivalitat mit Shiffrin.",
        "fr": "Profil de Petra Vlhova : la championne de slalom slovaque qui a remporte la premiere medaille d''or de ski de son pays. Stats de carriere, style de course et rivalite avec Shiffrin.",
        "it": "Profilo di Petra Vlhova: la campionessa di slalom slovacca che ha vinto la prima medaglia d''oro di sci del suo paese. Statistiche della carriera, stile di gara e rivalita con Shiffrin.",
        "es": "Perfil de Petra Vlhova: la campeona eslovaca de eslalon que gano la primera medalla de oro de esqui de su pais. Estadisticas de carrera, estilo de carrera y rivalidad con Shiffrin.",
        "pt": "Perfil de Petra Vlhova: a campea eslovaca de slalom que conquistou a primeira medalha de ouro de esqui de seu pais. Estatisticas da carreira, estilo de corrida e rivalidade com Shiffrin.",
        "nl": "Petra Vlhova profiel: Slowakije''s slalomkampioene die de eerste gouden skimedaille van haar land won. Carriere statistieken, racestijl en rivaliteit met Shiffrin.",
        "ar": "ملف بيترا فلهوفا: بطلة التزلج المتعرج السلوفاكية التي فازت بأول ميدالية ذهبية في التزلج لبلادها. إحصائيات المسيرة وأسلوب السباق والمنافسة مع شيفرين.",
        "ja": "ペトラ・ブルホバのプロフィール：母国初のスキー金メダルを獲得したスロバキアのスラロームチャンピオン。キャリア統計、レーススタイル、シフリンとのライバル関係。",
        "zh": "佩特拉·弗尔霍娃简介：为祖国赢得首枚滑雪金牌的斯洛伐克回转冠军。职业生涯数据、比赛风格及与希夫林的竞争。",
        "ko": "페트라 블호바 프로필: 조국 최초의 스키 금메달을 획득한 슬로바키아 회전 챔피언. 커리어 통계, 레이싱 스타일, 시프린과의 라이벌 관계."
    }',
    'published',
    NOW(),
    'generated'
);
