-- Migration: 021_athlete_kilde.sql
-- Aleksander Aamodt Kilde athlete profile (Norwegian speed specialist)

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type)
VALUES (
    'aleksander-kilde-profile',
    '{
        "en": "Aleksander Aamodt Kilde: Norway''s Speed King",
        "de": "Aleksander Aamodt Kilde: Norwegens Speed-Konig",
        "fr": "Aleksander Aamodt Kilde : Le Roi de la Vitesse Norvegien",
        "it": "Aleksander Aamodt Kilde: Il Re della Velocita Norvegese",
        "es": "Aleksander Aamodt Kilde: El Rey de la Velocidad Noruego",
        "pt": "Aleksander Aamodt Kilde: O Rei da Velocidade Noruegues",
        "nl": "Aleksander Aamodt Kilde: Noorwegen''s Snelheidskoning",
        "ar": "ألكسندر أموت كيلده: ملك السرعة النرويجي",
        "ja": "アレクサンダー・オーモット・キルデ：ノルウェーのスピードキング",
        "zh": "亚历山大·奥莫特·基尔德：挪威速度之王",
        "ko": "알렉산더 오모트 킬데: 노르웨이의 스피드 킹"
    }',
    '{
        "en": "Meet Aleksander Aamodt Kilde, the Norwegian downhill and super-G champion who has become one of alpine skiing''s biggest stars.",
        "de": "Lernen Sie Aleksander Aamodt Kilde kennen, den norwegischen Abfahrts- und Super-G-Champion, der zu einem der grossten Stars des Alpenskisports geworden ist.",
        "fr": "Decouvrez Aleksander Aamodt Kilde, le champion norvegien de descente et super-G devenu l''une des plus grandes stars du ski alpin.",
        "it": "Scopri Aleksander Aamodt Kilde, il campione norvegese di discesa e super-G che e diventato una delle piu grandi star dello sci alpino.",
        "es": "Conoce a Aleksander Aamodt Kilde, el campeon noruego de descenso y super-G que se ha convertido en una de las mayores estrellas del esqui alpino.",
        "pt": "Conheca Aleksander Aamodt Kilde, o campeao noruegues de downhill e super-G que se tornou uma das maiores estrelas do esqui alpino.",
        "nl": "Maak kennis met Aleksander Aamodt Kilde, de Noorse afdaling en super-G kampioen die een van de grootste sterren van het alpineskien is geworden.",
        "ar": "تعرف على ألكسندر أموت كيلده، بطل الانحدار والسوبر جي النرويجي الذي أصبح واحداً من أكبر نجوم التزلج الألبي.",
        "ja": "アルペンスキー界最大のスターの一人となったノルウェーのダウンヒル・スーパーGチャンピオン、アレクサンダー・オーモット・キルデを紹介します。",
        "zh": "认识亚历山大·奥莫特·基尔德，这位挪威滑降和超级大回转冠军已成为高山滑雪界最大的明星之一。",
        "ko": "알파인 스키계 최고의 스타 중 한 명이 된 노르웨이 활강 및 슈퍼대회전 챔피언 알렉산더 오모트 킬데를 만나보세요."
    }',
    '{
        "en": "<h2>Norway''s Speed Sensation</h2><p>Aleksander Aamodt Kilde has established himself as one of the most dominant speed skiers in the world. Born in 1992 in Baerum, Norway, Kilde has won multiple World Cup titles in both downhill and super-G disciplines.</p><p>His combination of power, technical skill, and fearlessness makes him a formidable competitor on any <a href=\"/alpine-skiing-guide/\">alpine skiing</a> speed course.</p><h2>Career Highlights</h2><p>Kilde''s impressive achievements include:</p><ul><li>Multiple overall World Cup top-3 finishes</li><li>Downhill World Cup globe winner</li><li>Super-G World Cup globe winner</li><li>20+ World Cup victories</li><li>World Championship medals</li></ul><p>He has won on some of skiing''s most legendary courses, including Kitzbuhel''s Streif and Wengen''s Lauberhorn.</p><h2>Racing Style</h2><p>Kilde is known for:</p><ul><li>Explosive power out of the start</li><li>Aggressive approach to speed sections</li><li>Strong gliding skills</li><li>Ability to take risks that others cannot</li></ul><p>His physical strength allows him to hold lines that other racers must back off from, particularly in the toughest sections of downhill courses.</p><h2>Comeback Story</h2><p>Kilde''s career has included significant injury setbacks. After a serious knee injury, many wondered if he could return to the top level. His determination and work ethic brought him back stronger than ever.</p><p>This comeback mentality has become a defining characteristic of his career and an inspiration to athletes everywhere.</p><h2>Beyond the Slopes</h2><p>Off the snow, Kilde has become one of skiing''s most recognizable personalities. His relationship with American skier <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> has made them skiing''s power couple.</p><p>Together, they share a passion for the sport and continue to push each other to new heights.</p><h2>Looking Ahead</h2><p>Kilde remains focused on adding to his trophy collection. His consistency in speed events and his hunger for more victories make him a threat at every race.</p><p>Follow his season in <a href=\"/alpine-skiing-guide/\">alpine skiing</a> speed events around the world.</p>",
        "de": "<h2>Norwegens Speed-Sensation</h2><p>Aleksander Aamodt Kilde hat sich als einer der dominantesten Speed-Skifahrer der Welt etabliert. 1992 in Baerum, Norwegen, geboren, hat Kilde mehrere Weltcuptitel sowohl in der Abfahrt als auch im Super-G gewonnen.</p><p>Seine Kombination aus Kraft, technischem Konnen und Furchtlosigkeit macht ihn zu einem beeindruckenden Konkurrenten auf jeder <a href=\"/alpine-skiing-guide/\">Alpinski</a>-Speed-Strecke.</p><h2>Karriere-Hohepunkte</h2><p>Kildes beeindruckende Erfolge umfassen:</p><ul><li>Mehrere Top-3-Platzierungen im Gesamtweltcup</li><li>Abfahrts-Weltcupkugel-Gewinner</li><li>Super-G-Weltcupkugel-Gewinner</li><li>Uber 20 Weltcupsiege</li><li>Weltmeisterschaftsmedaillen</li></ul><p>Er hat auf einigen der legendirsten Strecken des Skisports gewonnen, darunter die Streif in Kitzbuhel und die Lauberhorn in Wengen.</p><h2>Rennstil</h2><p>Kilde ist bekannt fur:</p><ul><li>Explosive Kraft aus dem Start</li><li>Aggressive Herangehensweise an Speedpassagen</li><li>Starke Gleittechnik</li><li>Fahigkeit, Risiken einzugehen, die andere nicht konnen</li></ul><p>Seine korperliche Starke ermoglicht es ihm, Linien zu halten, von denen andere Rennlaufer zuruckweichen mussen, besonders in den schwierigsten Abschnitten von Abfahrtsstrecken.</p><h2>Comeback-Geschichte</h2><p>Kildes Karriere beinhaltete bedeutende Verletzungsruckschlage. Nach einer schweren Knieverletzung fragten sich viele, ob er auf hochstem Niveau zuruckkehren konnte. Seine Entschlossenheit und Arbeitsmoral brachten ihn starker denn je zuruck.</p><p>Diese Comeback-Mentalitat ist zu einem pragenden Merkmal seiner Karriere und einer Inspiration fur Athleten uberall geworden.</p><h2>Abseits der Pisten</h2><p>Abseits des Schnees ist Kilde zu einer der bekanntesten Personlichkeiten des Skisports geworden. Seine Beziehung mit der amerikanischen Skifahrerin <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> hat sie zum Power-Paar des Skisports gemacht.</p><p>Gemeinsam teilen sie eine Leidenschaft fur den Sport und treiben sich gegenseitig zu neuen Hochstleistungen.</p><h2>Ausblick</h2><p>Kilde bleibt darauf konzentriert, seine Trophiensammlung zu erweitern. Seine Konstanz in Speed-Disziplinen und sein Hunger nach mehr Siegen machen ihn bei jedem Rennen zu einer Bedrohung.</p><p>Verfolgen Sie seine Saison bei <a href=\"/alpine-skiing-guide/\">Alpinski</a>-Speed-Veranstaltungen weltweit.</p>",
        "fr": "<h2>La Sensation de Vitesse Norvegienne</h2><p>Aleksander Aamodt Kilde s''est impose comme l''un des skieurs de vitesse les plus dominants au monde. Ne en 1992 a Baerum, en Norvege, Kilde a remporte plusieurs titres de Coupe du monde en descente et en super-G.</p><p>Sa combinaison de puissance, de competence technique et d''intrepidite en fait un concurrent redoutable sur tout parcours de vitesse de <a href=\"/alpine-skiing-guide/\">ski alpin</a>.</p><h2>Points Forts de Carriere</h2><p>Les realisations impressionnantes de Kilde incluent:</p><ul><li>Plusieurs top 3 au classement general de la Coupe du monde</li><li>Vainqueur du globe de descente</li><li>Vainqueur du globe de super-G</li><li>Plus de 20 victoires en Coupe du monde</li><li>Medailles aux Championnats du monde</li></ul><p>Il a gagne sur certaines des pistes les plus legendaires du ski, dont la Streif de Kitzbuhel et le Lauberhorn de Wengen.</p><h2>Style de Course</h2><p>Kilde est connu pour:</p><ul><li>Puissance explosive au depart</li><li>Approche agressive dans les sections rapides</li><li>Fortes competences de glisse</li><li>Capacite a prendre des risques que d''autres ne peuvent pas</li></ul><p>Sa force physique lui permet de tenir des lignes dont d''autres coureurs doivent s''ecarter, particulierement dans les sections les plus difficiles des parcours de descente.</p><h2>Histoire de Retour</h2><p>La carriere de Kilde a inclus des revers importants dus a des blessures. Apres une grave blessure au genou, beaucoup se demandaient s''il pourrait revenir au plus haut niveau. Sa determination et son ethique de travail l''ont ramene plus fort que jamais.</p><p>Cette mentalite de retour est devenue une caracteristique definissante de sa carriere et une inspiration pour les athletes partout.</p><h2>En Dehors des Pistes</h2><p>Hors de la neige, Kilde est devenu l''une des personnalites les plus reconnaissables du ski. Sa relation avec la skieuse americaine <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> en a fait le couple phare du ski.</p><p>Ensemble, ils partagent une passion pour le sport et continuent de se pousser mutuellement vers de nouveaux sommets.</p><h2>Perspectives</h2><p>Kilde reste concentre sur l''ajout a sa collection de trophees. Sa regularite dans les epreuves de vitesse et sa faim de victoires en font une menace a chaque course.</p><p>Suivez sa saison dans les epreuves de vitesse de <a href=\"/alpine-skiing-guide/\">ski alpin</a> a travers le monde.</p>",
        "it": "<h2>La Sensazione della Velocita Norvegese</h2><p>Aleksander Aamodt Kilde si e affermato come uno degli sciatori di velocita piu dominanti al mondo. Nato nel 1992 a Baerum, in Norvegia, Kilde ha vinto diversi titoli di Coppa del Mondo sia in discesa che in super-G.</p><p>La sua combinazione di potenza, abilita tecnica e coraggio lo rende un concorrente formidabile su qualsiasi percorso di velocita dello <a href=\"/alpine-skiing-guide/\">sci alpino</a>.</p><h2>Momenti Salienti della Carriera</h2><p>I successi impressionanti di Kilde includono:</p><ul><li>Diversi piazzamenti nei primi 3 della Coppa del Mondo generale</li><li>Vincitore della coppa di discesa</li><li>Vincitore della coppa di super-G</li><li>Oltre 20 vittorie in Coppa del Mondo</li><li>Medaglie ai Campionati del Mondo</li></ul><p>Ha vinto su alcune delle piste piu leggendarie dello sci, tra cui la Streif di Kitzbuhel e la Lauberhorn di Wengen.</p><h2>Stile di Gara</h2><p>Kilde e noto per:</p><ul><li>Potenza esplosiva alla partenza</li><li>Approccio aggressivo nelle sezioni veloci</li><li>Forti capacita di scivolamento</li><li>Capacita di correre rischi che altri non possono</li></ul><p>La sua forza fisica gli permette di tenere linee da cui altri corridori devono tirarsi indietro, particolarmente nelle sezioni piu difficili dei percorsi di discesa.</p><h2>Storia del Ritorno</h2><p>La carriera di Kilde ha incluso significativi contrattempi dovuti a infortuni. Dopo un grave infortunio al ginocchio, molti si chiedevano se potesse tornare ai massimi livelli. La sua determinazione e etica del lavoro lo hanno riportato piu forte che mai.</p><p>Questa mentalita del ritorno e diventata una caratteristica distintiva della sua carriera e un''ispirazione per gli atleti ovunque.</p><h2>Oltre le Piste</h2><p>Fuori dalla neve, Kilde e diventato una delle personalita piu riconoscibili dello sci. La sua relazione con la sciatrice americana <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> li ha resi la coppia d''oro dello sci.</p><p>Insieme, condividono una passione per lo sport e continuano a spingersi verso nuove vette.</p><h2>Guardando Avanti</h2><p>Kilde rimane concentrato sull''aggiungere alla sua collezione di trofei. La sua costanza nelle discipline veloci e la sua fame di altre vittorie lo rendono una minaccia a ogni gara.</p><p>Segui la sua stagione nelle gare di velocita dello <a href=\"/alpine-skiing-guide/\">sci alpino</a> in tutto il mondo.</p>",
        "es": "<h2>La Sensacion de la Velocidad Noruega</h2><p>Aleksander Aamodt Kilde se ha establecido como uno de los esquiadores de velocidad mas dominantes del mundo. Nacido en 1992 en Baerum, Noruega, Kilde ha ganado multiples titulos de Copa del Mundo tanto en descenso como en super-G.</p><p>Su combinacion de potencia, habilidad tecnica e intrepidez lo convierte en un competidor formidable en cualquier pista de velocidad de <a href=\"/alpine-skiing-guide/\">esqui alpino</a>.</p><h2>Momentos Destacados de su Carrera</h2><p>Los logros impresionantes de Kilde incluyen:</p><ul><li>Multiples top 3 en la Copa del Mundo general</li><li>Ganador del globo de descenso</li><li>Ganador del globo de super-G</li><li>Mas de 20 victorias en Copa del Mundo</li><li>Medallas en Campeonatos del Mundo</li></ul><p>Ha ganado en algunas de las pistas mas legendarias del esqui, incluyendo la Streif de Kitzbuhel y la Lauberhorn de Wengen.</p><h2>Estilo de Carrera</h2><p>Kilde es conocido por:</p><ul><li>Potencia explosiva en la salida</li><li>Enfoque agresivo en las secciones de velocidad</li><li>Fuertes habilidades de deslizamiento</li><li>Capacidad para tomar riesgos que otros no pueden</li></ul><p>Su fuerza fisica le permite mantener lineas de las que otros corredores deben retirarse, particularmente en las secciones mas dificiles de las pistas de descenso.</p><h2>Historia de Regreso</h2><p>La carrera de Kilde ha incluido importantes contratiempos por lesiones. Despues de una grave lesion de rodilla, muchos se preguntaban si podria volver al nivel mas alto. Su determinacion y etica de trabajo lo trajeron de vuelta mas fuerte que nunca.</p><p>Esta mentalidad de regreso se ha convertido en una caracteristica definitoria de su carrera y una inspiracion para atletas en todas partes.</p><h2>Fuera de las Pistas</h2><p>Fuera de la nieve, Kilde se ha convertido en una de las personalidades mas reconocibles del esqui. Su relacion con la esquiadora estadounidense <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> los ha convertido en la pareja poderosa del esqui.</p><p>Juntos, comparten una pasion por el deporte y continuan empujandose mutuamente hacia nuevas alturas.</p><h2>Mirando Adelante</h2><p>Kilde sigue enfocado en agregar a su coleccion de trofeos. Su consistencia en las pruebas de velocidad y su hambre de mas victorias lo convierten en una amenaza en cada carrera.</p><p>Sigue su temporada en las pruebas de velocidad de <a href=\"/alpine-skiing-guide/\">esqui alpino</a> alrededor del mundo.</p>",
        "pt": "<h2>A Sensacao de Velocidade Norueguesa</h2><p>Aleksander Aamodt Kilde se estabeleceu como um dos esquiadores de velocidade mais dominantes do mundo. Nascido em 1992 em Baerum, Noruega, Kilde ganhou multiplos titulos da Copa do Mundo tanto no downhill quanto no super-G.</p><p>Sua combinacao de potencia, habilidade tecnica e destemor o torna um competidor formidavel em qualquer pista de velocidade do <a href=\"/alpine-skiing-guide/\">esqui alpino</a>.</p><h2>Destaques da Carreira</h2><p>As conquistas impressionantes de Kilde incluem:</p><ul><li>Multiplos top 3 na Copa do Mundo geral</li><li>Vencedor do globo de downhill</li><li>Vencedor do globo de super-G</li><li>Mais de 20 vitorias na Copa do Mundo</li><li>Medalhas em Campeonatos Mundiais</li></ul><p>Ele venceu em algumas das pistas mais lendarias do esqui, incluindo a Streif de Kitzbuhel e a Lauberhorn de Wengen.</p><h2>Estilo de Corrida</h2><p>Kilde e conhecido por:</p><ul><li>Potencia explosiva na largada</li><li>Abordagem agressiva nas secoes de velocidade</li><li>Fortes habilidades de deslizamento</li><li>Capacidade de assumir riscos que outros nao podem</li></ul><p>Sua forca fisica permite que ele mantenha linhas das quais outros corredores precisam recuar, particularmente nas secoes mais dificeis das pistas de downhill.</p><h2>Historia de Retorno</h2><p>A carreira de Kilde incluiu contratempos significativos por lesoes. Apos uma grave lesao no joelho, muitos se perguntavam se ele poderia voltar ao nivel mais alto. Sua determinacao e etica de trabalho o trouxeram de volta mais forte do que nunca.</p><p>Essa mentalidade de retorno se tornou uma caracteristica definidora de sua carreira e uma inspiracao para atletas em todos os lugares.</p><h2>Fora das Pistas</h2><p>Fora da neve, Kilde se tornou uma das personalidades mais reconheciveis do esqui. Seu relacionamento com a esquiadora americana <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> os tornou o casal poderoso do esqui.</p><p>Juntos, eles compartilham uma paixao pelo esporte e continuam a empurrar um ao outro para novos patamares.</p><h2>Olhando para o Futuro</h2><p>Kilde permanece focado em adicionar a sua colecao de trofeus. Sua consistencia em provas de velocidade e sua fome por mais vitorias o tornam uma ameaca em cada corrida.</p><p>Acompanhe sua temporada nas provas de velocidade do <a href=\"/alpine-skiing-guide/\">esqui alpino</a> ao redor do mundo.</p>",
        "nl": "<h2>Noorwegen''s Snelheidssensatie</h2><p>Aleksander Aamodt Kilde heeft zich gevestigd als een van de meest dominante snelheidsski<br>ers ter wereld. Geboren in 1992 in Baerum, Noorwegen, heeft Kilde meerdere Wereldbekertitels gewonnen in zowel afdaling als super-G.</p><p>Zijn combinatie van kracht, technische vaardigheid en onverschrokkenheid maakt hem een formidabele concurrent op elk <a href=\"/alpine-skiing-guide/\">alpineski</a> snelheidsparcours.</p><h2>Carriere Hoogtepunten</h2><p>Kilde''s indrukwekkende prestaties omvatten:</p><ul><li>Meerdere algemene Wereldbeker top-3 finishes</li><li>Winnaar afdalingsbol</li><li>Winnaar super-G bol</li><li>Meer dan 20 Wereldbekeroverwinningen</li><li>Wereldkampioenschapsmedailles</li></ul><p>Hij heeft gewonnen op enkele van de meest legendarische banen van het skien, waaronder de Streif van Kitzbuhel en de Lauberhorn van Wengen.</p><h2>Racestijl</h2><p>Kilde staat bekend om:</p><ul><li>Explosieve kracht uit de start</li><li>Agressieve benadering in snelheidssecties</li><li>Sterke glijvaardigheden</li><li>Vermogen om risico''s te nemen die anderen niet kunnen</li></ul><p>Zijn fysieke kracht stelt hem in staat om lijnen te houden waar andere racers van terug moeten wijken, vooral in de moeilijkste secties van afdalingsparcoursen.</p><h2>Comeback Verhaal</h2><p>Kilde''s carriere bevatte significante tegenslagen door blessures. Na een ernstige knieblessure vroegen velen zich af of hij terug kon keren naar het hoogste niveau. Zijn vastberadenheid en arbeidsethos brachten hem sterker dan ooit terug.</p><p>Deze comebackmentaliteit is een bepalend kenmerk van zijn carriere geworden en een inspiratie voor atleten overal.</p><h2>Buiten de Pistes</h2><p>Buiten de sneeuw is Kilde een van de meest herkenbare persoonlijkheden van het skien geworden. Zijn relatie met de Amerikaanse skister <a href=\"/mikaela-shiffrin-profile/\">Mikaela Shiffrin</a> heeft hen tot het powerkoppel van het skien gemaakt.</p><p>Samen delen ze een passie voor de sport en blijven ze elkaar naar nieuwe hoogtes pushen.</p><h2>Vooruitkijkend</h2><p>Kilde blijft gefocust op het uitbreiden van zijn trofeeencollectie. Zijn consistentie in snelheidsonderdelen en zijn honger naar meer overwinningen maken hem bij elke race een bedreiging.</p><p>Volg zijn seizoen in <a href=\"/alpine-skiing-guide/\">alpineski</a> snelheidsonderdelen over de hele wereld.</p>",
        "ar": "<h2>إحساس السرعة النرويجي</h2><p>أثبت ألكسندر أموت كيلده نفسه كواحد من أكثر متزلجي السرعة هيمنة في العالم. ولد في عام 1992 في باروم، النرويج، وفاز كيلده بعدة ألقاب في كأس العالم في كل من الانحدار والسوبر جي.</p><p>مزيجه من القوة والمهارة التقنية والجرأة يجعله منافساً هائلاً على أي مسار سرعة في <a href=\"/alpine-skiing-guide/\">التزلج الألبي</a>.</p><h2>أبرز مراحل المسيرة</h2><p>تشمل إنجازات كيلده المثيرة للإعجاب:</p><ul><li>عدة مراكز ضمن الثلاثة الأوائل في كأس العالم العام</li><li>الفائز بكرة الانحدار</li><li>الفائز بكرة السوبر جي</li><li>أكثر من 20 انتصاراً في كأس العالم</li><li>ميداليات بطولة العالم</li></ul><p>فاز على بعض أكثر المسارات أسطورية في التزلج، بما في ذلك ستريف كيتزبوهيل ولاوبرهورن وينغن.</p><h2>أسلوب السباق</h2><p>يُعرف كيلده بـ:</p><ul><li>قوة انفجارية من البداية</li><li>نهج عدواني في مقاطع السرعة</li><li>مهارات انزلاق قوية</li><li>القدرة على المخاطرة التي لا يستطيعها الآخرون</li></ul><p>قوته البدنية تسمح له بالحفاظ على خطوط يجب على المتسابقين الآخرين التراجع عنها، خاصة في الأقسام الأصعب من مسارات الانحدار.</p><h2>قصة العودة</h2><p>تضمنت مسيرة كيلده انتكاسات كبيرة بسبب الإصابات. بعد إصابة خطيرة في الركبة، تساءل الكثيرون عما إذا كان يمكنه العودة إلى أعلى مستوى. عزيمته وأخلاقيات عمله أعادته أقوى من أي وقت مضى.</p><p>أصبحت عقلية العودة هذه سمة مميزة لمسيرته وإلهاماً للرياضيين في كل مكان.</p><h2>خارج المنحدرات</h2><p>بعيداً عن الثلج، أصبح كيلده واحداً من أكثر الشخصيات شهرة في التزلج. علاقته مع المتزلجة الأمريكية <a href=\"/mikaela-shiffrin-profile/\">ميكايلا شيفرين</a> جعلتهما الثنائي القوي في التزلج.</p><p>معاً، يتشاركان شغفاً بالرياضة ويستمران في دفع بعضهما البعض نحو آفاق جديدة.</p><h2>نظرة للمستقبل</h2><p>يظل كيلده مركزاً على إضافة المزيد إلى مجموعة جوائزه. ثباته في أحداث السرعة وجوعه للمزيد من الانتصارات يجعله تهديداً في كل سباق.</p><p>تابع موسمه في أحداث السرعة في <a href=\"/alpine-skiing-guide/\">التزلج الألبي</a> حول العالم.</p>",
        "ja": "<h2>ノルウェーのスピードセンセーション</h2><p>アレクサンダー・オーモット・キルデは、世界で最も支配的なスピードスキーヤーの一人としての地位を確立しました。1992年にノルウェーのベールムで生まれ、キルデはダウンヒルとスーパーGの両方で複数のワールドカップタイトルを獲得しています。</p><p>パワー、テクニカルスキル、そして恐れを知らない姿勢の組み合わせは、どんな<a href=\"/alpine-skiing-guide/\">アルペンスキー</a>スピードコースでも強力な競争相手となります。</p><h2>キャリアハイライト</h2><p>キルデの印象的な実績には以下が含まれます：</p><ul><li>複数のワールドカップ総合トップ3フィニッシュ</li><li>ダウンヒルワールドカップ部門優勝</li><li>スーパーGワールドカップ部門優勝</li><li>20以上のワールドカップ勝利</li><li>世界選手権メダル</li></ul><p>彼はスキー界で最も伝説的なコースで勝利を収めています。キッツビュールのストライフやウェンゲンのラウバーホルンなどです。</p><h2>レーススタイル</h2><p>キルデは以下で知られています：</p><ul><li>スタートからの爆発的なパワー</li><li>スピードセクションへの攻撃的なアプローチ</li><li>強いグライディングスキル</li><li>他の選手ができないリスクを取る能力</li></ul><p>彼の身体的な強さにより、特にダウンヒルコースの最も難しいセクションで、他のレーサーが引かざるを得ないラインをキープすることができます。</p><h2>カムバックストーリー</h2><p>キルデのキャリアには重大な怪我による挫折が含まれています。深刻な膝の怪我の後、多くの人が彼がトップレベルに戻れるかどうか疑問に思いました。彼の決意と労働倫理が、彼をかつてないほど強く復活させました。</p><p>このカムバック精神は、彼のキャリアを特徴づけるものとなり、世界中のアスリートへのインスピレーションとなっています。</p><h2>ゲレンデ以外で</h2><p>雪の外では、キルデはスキー界で最も認知度の高い人物の一人となっています。アメリカのスキーヤー<a href=\"/mikaela-shiffrin-profile/\">ミカエラ・シフリン</a>との関係は、彼らをスキー界のパワーカップルにしました。</p><p>二人はスポーツへの情熱を共有し、互いを新たな高みへと押し上げ続けています。</p><h2>今後の展望</h2><p>キルデはトロフィーコレクションに加えることに集中し続けています。スピード種目での一貫性と勝利への飢えが、すべてのレースで彼を脅威にしています。</p><p>世界中の<a href=\"/alpine-skiing-guide/\">アルペンスキー</a>スピード種目で彼のシーズンを追いかけてください。</p>",
        "zh": "<h2>挪威速度感觉</h2><p>亚历山大·奥莫特·基尔德已确立自己作为世界上最具统治力的速度滑雪运动员之一的地位。1992年出生于挪威贝鲁姆，基尔德在滑降和超级大回转项目中赢得了多个世界杯冠军。</p><p>他的力量、技术能力和无畏的结合使他成为任何<a href=\"/alpine-skiing-guide/\">高山滑雪</a>速度赛道上的强劲竞争者。</p><h2>职业生涯亮点</h2><p>基尔德令人印象深刻的成就包括：</p><ul><li>多次世界杯总积分前三名</li><li>滑降世界杯水晶球得主</li><li>超级大回转世界杯水晶球得主</li><li>20多次世界杯胜利</li><li>世锦赛奖牌</li></ul><p>他在滑雪界一些最传奇的赛道上取得了胜利，包括基茨比厄尔的斯特赖夫和温根的劳伯霍恩。</p><h2>比赛风格</h2><p>基尔德以以下特点著称：</p><ul><li>起跑时的爆发力</li><li>在速度段的激进方式</li><li>强大的滑行技术</li><li>能够承担他人无法承担的风险</li></ul><p>他的身体力量使他能够保持其他选手必须退让的路线，特别是在滑降赛道最困难的部分。</p><h2>复出故事</h2><p>基尔德的职业生涯包括重大的伤病挫折。在严重的膝伤之后，许多人怀疑他是否能重返顶级水平。他的决心和职业道德使他比以往任何时候都更强大地回归。</p><p>这种复出心态已成为他职业生涯的标志性特征，也是对世界各地运动员的激励。</p><h2>赛道之外</h2><p>在雪地之外，基尔德已成为滑雪界最知名的人物之一。他与美国滑雪运动员<a href=\"/mikaela-shiffrin-profile/\">米凯拉·希夫林</a>的关系使他们成为滑雪界的明星情侣。</p><p>他们一起分享对这项运动的热情，并继续推动彼此达到新的高度。</p><h2>展望未来</h2><p>基尔德仍然专注于增加他的奖杯收藏。他在速度项目中的稳定性和对更多胜利的渴望使他在每场比赛中都是一个威胁。</p><p>在世界各地的<a href=\"/alpine-skiing-guide/\">高山滑雪</a>速度项目中关注他的赛季。</p>",
        "ko": "<h2>노르웨이의 스피드 센세이션</h2><p>알렉산더 오모트 킬데는 세계에서 가장 지배적인 스피드 스키 선수 중 한 명으로 자리매김했습니다. 1992년 노르웨이 베룸에서 태어난 킬데는 활강과 슈퍼대회전 모두에서 여러 월드컵 타이틀을 획득했습니다.</p><p>그의 파워, 기술적 능력, 그리고 두려움 없는 자세의 조합은 그를 어떤 <a href=\"/alpine-skiing-guide/\">알파인 스키</a> 스피드 코스에서도 강력한 경쟁자로 만듭니다.</p><h2>커리어 하이라이트</h2><p>킬데의 인상적인 업적은 다음을 포함합니다:</p><ul><li>여러 번의 월드컵 종합 톱3 피니시</li><li>활강 월드컵 크리스탈 글로브 획득</li><li>슈퍼대회전 월드컵 크리스탈 글로브 획득</li><li>20회 이상의 월드컵 우승</li><li>세계선수권대회 메달</li></ul><p>그는 키츠뷔엘의 슈트라이프와 벵엔의 라우버호른을 포함한 스키계에서 가장 전설적인 코스에서 우승했습니다.</p><h2>레이싱 스타일</h2><p>킬데는 다음으로 알려져 있습니다:</p><ul><li>스타트에서의 폭발적인 파워</li><li>스피드 구간에서의 공격적인 접근</li><li>강한 활강 기술</li><li>다른 선수들이 할 수 없는 위험을 감수하는 능력</li></ul><p>그의 신체적 강인함은 특히 활강 코스의 가장 어려운 구간에서 다른 레이서들이 물러나야 하는 라인을 유지할 수 있게 합니다.</p><h2>컴백 스토리</h2><p>킬데의 커리어에는 심각한 부상으로 인한 좌절이 포함되어 있습니다. 심각한 무릎 부상 후 많은 사람들은 그가 최고 수준으로 복귀할 수 있을지 의문을 품었습니다. 그의 결단력과 직업 윤리가 그를 그 어느 때보다 강하게 돌아오게 했습니다.</p><p>이 컴백 정신은 그의 커리어를 정의하는 특성이 되었고 전 세계 선수들에게 영감을 주고 있습니다.</p><h2>슬로프 밖에서</h2><p>눈 밖에서 킬데는 스키계에서 가장 인지도 높은 인물 중 한 명이 되었습니다. 미국 스키 선수 <a href=\"/mikaela-shiffrin-profile/\">미카엘라 시프린</a>과의 관계는 그들을 스키계의 파워 커플로 만들었습니다.</p><p>함께 그들은 스포츠에 대한 열정을 공유하고 서로를 새로운 높이로 밀어붙이고 있습니다.</p><h2>앞을 내다보며</h2><p>킬데는 트로피 컬렉션을 늘리는 데 집중하고 있습니다. 스피드 종목에서의 꾸준함과 더 많은 승리에 대한 갈망이 그를 모든 경기에서 위협적인 존재로 만듭니다.</p><p>전 세계 <a href=\"/alpine-skiing-guide/\">알파인 스키</a> 스피드 종목에서 그의 시즌을 팔로우하세요.</p>"
    }',
    'athlete-profile',
    'ALP',
    '{
        "en": "Aleksander Aamodt Kilde profile: Norwegian downhill and super-G champion, comeback story, and relationship with Mikaela Shiffrin. Career stats and racing style.",
        "de": "Aleksander Aamodt Kilde Profil: Norwegischer Abfahrts- und Super-G-Champion, Comeback-Geschichte und Beziehung mit Mikaela Shiffrin. Karrierestatistiken und Rennstil.",
        "fr": "Profil d''Aleksander Aamodt Kilde : champion norvegien de descente et super-G, histoire de retour et relation avec Mikaela Shiffrin. Stats et style de course.",
        "it": "Profilo di Aleksander Aamodt Kilde: campione norvegese di discesa e super-G, storia del ritorno e relazione con Mikaela Shiffrin. Statistiche e stile di gara.",
        "es": "Perfil de Aleksander Aamodt Kilde: campeon noruego de descenso y super-G, historia de regreso y relacion con Mikaela Shiffrin. Estadisticas y estilo de carrera.",
        "pt": "Perfil de Aleksander Aamodt Kilde: campeao noruegues de downhill e super-G, historia de retorno e relacionamento com Mikaela Shiffrin. Estatisticas e estilo de corrida.",
        "nl": "Aleksander Aamodt Kilde profiel: Noorse afdaling en super-G kampioen, comeback verhaal en relatie met Mikaela Shiffrin. Carriere statistieken en racestijl.",
        "ar": "ملف ألكسندر أموت كيلده: بطل الانحدار والسوبر جي النرويجي، قصة العودة والعلاقة مع ميكايلا شيفرين. إحصائيات المسيرة وأسلوب السباق.",
        "ja": "アレクサンダー・オーモット・キルデのプロフィール：ノルウェーのダウンヒル・スーパーGチャンピオン、カムバックストーリー、ミカエラ・シフリンとの関係。キャリア統計とレーススタイル。",
        "zh": "亚历山大·奥莫特·基尔德简介：挪威滑降和超级大回转冠军、复出故事及与米凯拉·希夫林的关系。职业生涯数据和比赛风格。",
        "ko": "알렉산더 오모트 킬데 프로필: 노르웨이 활강 및 슈퍼대회전 챔피언, 컴백 스토리, 미카엘라 시프린과의 관계. 커리어 통계와 레이싱 스타일."
    }',
    'published',
    NOW(),
    'generated'
);
