-- Migration: 024_athlete_johaug.sql
-- Therese Johaug athlete profile (Norwegian cross-country skier)

INSERT INTO articles (slug, title, excerpt, content, category, sport_code, meta_description, status, published_at, source_type)
VALUES (
    'therese-johaug-profile',
    '{
        "en": "Therese Johaug: The Queen of Cross-Country Skiing",
        "de": "Therese Johaug: Die Konigin des Langlaufs",
        "fr": "Therese Johaug : La Reine du Ski de Fond",
        "it": "Therese Johaug: La Regina dello Sci di Fondo",
        "es": "Therese Johaug: La Reina del Esqui de Fondo",
        "pt": "Therese Johaug: A Rainha do Esqui Cross-Country",
        "nl": "Therese Johaug: De Koningin van het Langlaufen",
        "ar": "تيريز يوهوغ: ملكة التزلج الريفي",
        "ja": "テレーセ・ヨーハウグ：クロスカントリースキーの女王",
        "zh": "特蕾丝·约豪格：越野滑雪女王",
        "ko": "테레세 요하우그: 크로스컨트리 스키의 여왕"
    }',
    '{
        "en": "Meet Therese Johaug, Norway''s legendary cross-country skier who has dominated distance events with an unmatched winning record.",
        "de": "Lernen Sie Therese Johaug kennen, Norwegens legendare Langlaeuerin, die Distanzrennen mit einer unerreichten Siegbilanz dominiert hat.",
        "fr": "Decouvrez Therese Johaug, la legendaire skieuse de fond norvegienne qui a domine les epreuves de distance avec un palmares inegale.",
        "it": "Scopri Therese Johaug, la leggendaria fondista norvegese che ha dominato le gare di distanza con un record di vittorie ineguagliato.",
        "es": "Conoce a Therese Johaug, la legendaria esquiadora de fondo noruega que ha dominado las pruebas de distancia con un record de victorias inigualable.",
        "pt": "Conheca Therese Johaug, a lendaria esquiadora cross-country norueguesa que dominou as provas de distancia com um recorde de vitorias incomparavel.",
        "nl": "Maak kennis met Therese Johaug, Noorwegen''s legendarische langlaufster die afstandswedstrijden heeft gedomineerd met een ongeevenaarde overwinningsrecord.",
        "ar": "تعرف على تيريز يوهوغ، أسطورة التزلج الريفي النرويجية التي هيمنت على سباقات المسافات بسجل انتصارات لا مثيل له.",
        "ja": "比類のない勝利記録で距離種目を支配してきたノルウェーの伝説的クロスカントリースキーヤー、テレーセ・ヨーハウグを紹介します。",
        "zh": "认识特蕾丝·约豪格，这位挪威传奇越野滑雪运动员以无与伦比的获胜记录主宰了长距离项目。",
        "ko": "비교할 수 없는 승리 기록으로 장거리 종목을 지배해온 노르웨이의 전설적인 크로스컨트리 스키 선수 테레세 요하우그를 만나보세요."
    }',
    '{
        "en": "<h2>A Dominant Force</h2><p>Therese Johaug is widely considered one of the greatest <a href=\"/cross-country-skiing-guide/\">cross-country skiers</a> of all time. Born in 1988 in Dalsbygda, Norway, she has won more World Championship gold medals than any other female cross-country skier in history.</p><p>Her dominance in distance events has been so complete that the question at most races is often who will finish second behind her.</p><h2>Career Achievements</h2><p>Johaug''s incredible record includes:</p><ul><li>14 World Championship gold medals</li><li>4 major Games medals</li><li>80+ World Cup victories</li><li>Multiple overall World Cup titles</li><li>Distance World Cup champion multiple times</li></ul><p>These numbers place her among the most successful winter sports athletes ever.</p><h2>Racing Dominance</h2><p>In distance events, Johaug has shown remarkable superiority:</p><ul><li>Often wins by margins of 30+ seconds</li><li>Strongest climber in women''s cross-country</li><li>Devastating pace on difficult courses</li><li>Exceptional technique in all conditions</li></ul><p>Her ability to break away from the pack and maintain punishing speeds makes her nearly unbeatable in her preferred events.</p><h2>Training Philosophy</h2><p>Johaug is known for her incredible training volume. She trains more hours per year than almost any other athlete in any sport. This dedication to preparation has built the endurance base that powers her race performances.</p><p>Her summer training camps in the mountains are legendary for their intensity.</p><h2>Beyond the Track</h2><p>Off the snow, Johaug has become a successful businesswoman and fashion designer. Her clothing brand reflects her personal style and has become popular in Norway.</p><p>She has also been open about mental health challenges athletes face, becoming an advocate for athlete wellbeing.</p><h2>Legacy</h2><p>Whether she continues competing or retires, Johaug''s legacy is secure. She has inspired a generation of young skiers and redefined what is possible in <a href=\"/cross-country-skiing-guide/\">cross-country skiing</a>.</p><p>Her records may stand for decades.</p>",
        "de": "<h2>Eine dominante Kraft</h2><p>Therese Johaug gilt weithin als eine der grossten <a href=\"/cross-country-skiing-guide/\">Langlaeuferinnen</a> aller Zeiten. 1988 in Dalsbygda, Norwegen, geboren, hat sie mehr WM-Goldmedaillen gewonnen als jede andere Langlaeuerin in der Geschichte.</p><p>Ihre Dominanz in Distanzrennen war so vollstandig, dass bei den meisten Rennen die Frage oft lautet, wer hinter ihr Zweiter wird.</p><h2>Karriere-Erfolge</h2><p>Johaugs unglaubliche Bilanz umfasst:</p><ul><li>14 WM-Goldmedaillen</li><li>4 Medaillen bei grossen Spielen</li><li>Uber 80 Weltcupsiege</li><li>Mehrere Gesamtweltcup-Titel</li><li>Mehrfache Distanz-Weltcup-Siegerin</li></ul><p>Diese Zahlen machen sie zu einer der erfolgreichsten Wintersportlerinnen uberhaupt.</p><h2>Renndominanz</h2><p>In Distanzrennen hat Johaug bemerkenswerte Uberlegenheit gezeigt:</p><ul><li>Gewinnt oft mit Vorsprungen von uber 30 Sekunden</li><li>Starkste Bergsteigerin im Damen-Langlauf</li><li>Verheerendes Tempo auf schwierigen Strecken</li><li>Aussergewohnliche Technik unter allen Bedingungen</li></ul><p>Ihre Fahigkeit, sich vom Feld abzusetzen und strafende Geschwindigkeiten beizubehalten, macht sie in ihren bevorzugten Disziplinen nahezu unschlagbar.</p><h2>Trainingsphilosophie</h2><p>Johaug ist fur ihr unglaubliches Trainingsvolumen bekannt. Sie trainiert mehr Stunden pro Jahr als fast jeder andere Athlet in irgendeiner Sportart. Diese Hingabe an die Vorbereitung hat die Ausdauerbasis aufgebaut, die ihre Rennleistungen antreibt.</p><p>Ihre Sommertrainingslager in den Bergen sind fur ihre Intensitat legendar.</p><h2>Abseits der Loipe</h2><p>Abseits des Schnees ist Johaug zu einer erfolgreichen Geschaftsfrau und Modedesignerin geworden. Ihre Bekleidungsmarke spiegelt ihren personlichen Stil wider und ist in Norwegen popular geworden.</p><p>Sie hat auch offen uber psychische Herausforderungen gesprochen, denen Athleten gegenubergestellt sind, und ist zur Fursprecherin fur das Wohlbefinden von Athleten geworden.</p><h2>Vermachtnis</h2><p>Ob sie weiter antritt oder sich zuruckzieht, Johaugs Vermachtnis ist gesichert. Sie hat eine Generation junger Skifahrer inspiriert und neu definiert, was im <a href=\"/cross-country-skiing-guide/\">Langlauf</a> moglich ist.</p><p>Ihre Rekorde konnten Jahrzehnte bestehen bleiben.</p>",
        "fr": "<h2>Une Force Dominante</h2><p>Therese Johaug est largement consideree comme l''une des plus grandes <a href=\"/cross-country-skiing-guide/\">skieuses de fond</a> de tous les temps. Nee en 1988 a Dalsbygda, en Norvege, elle a remporte plus de medailles d''or aux Championnats du monde que toute autre skieuse de fond de l''histoire.</p><p>Sa domination dans les epreuves de distance a ete si complete que la question lors de la plupart des courses est souvent de savoir qui finira deuxieme derriere elle.</p><h2>Palmares</h2><p>L''incroyable bilan de Johaug comprend:</p><ul><li>14 medailles d''or aux Championnats du monde</li><li>4 medailles aux grands Jeux</li><li>Plus de 80 victoires en Coupe du monde</li><li>Plusieurs titres de Coupe du monde generale</li><li>Championne de la Coupe du monde de distance plusieurs fois</li></ul><p>Ces chiffres la placent parmi les athletes de sports d''hiver les plus titrees de tous les temps.</p><h2>Domination en Course</h2><p>Dans les epreuves de distance, Johaug a montre une superiorite remarquable:</p><ul><li>Gagne souvent avec des marges de plus de 30 secondes</li><li>Meilleure grimpeuse du ski de fond feminin</li><li>Rythme devastateur sur les parcours difficiles</li><li>Technique exceptionnelle dans toutes les conditions</li></ul><p>Sa capacite a s''echapper du peloton et a maintenir des vitesses punitives la rend presque imbattable dans ses epreuves preferees.</p><h2>Philosophie d''Entrainement</h2><p>Johaug est connue pour son volume d''entrainement incroyable. Elle s''entraine plus d''heures par an que presque tout autre athlete dans n''importe quel sport. Cette dedication a la preparation a construit la base d''endurance qui alimente ses performances en course.</p><p>Ses camps d''entrainement d''ete en montagne sont legendaires pour leur intensite.</p><h2>Au-dela des Pistes</h2><p>Hors de la neige, Johaug est devenue une femme d''affaires et designer de mode a succes. Sa marque de vetements reflete son style personnel et est devenue populaire en Norvege.</p><p>Elle a aussi ete ouverte sur les defis de sante mentale auxquels les athletes font face, devenant une avocate du bien-etre des athletes.</p><h2>Heritage</h2><p>Qu''elle continue la competition ou prenne sa retraite, l''heritage de Johaug est assure. Elle a inspire une generation de jeunes skieurs et redefini ce qui est possible en <a href=\"/cross-country-skiing-guide/\">ski de fond</a>.</p><p>Ses records pourraient tenir pendant des decennies.</p>",
        "it": "<h2>Una Forza Dominante</h2><p>Therese Johaug e ampiamente considerata una delle piu grandi <a href=\"/cross-country-skiing-guide/\">sciatrici di fondo</a> di tutti i tempi. Nata nel 1988 a Dalsbygda, in Norvegia, ha vinto piu medaglie d''oro ai Campionati del Mondo di qualsiasi altra fondista nella storia.</p><p>Il suo dominio nelle gare di distanza e stato cosi completo che la domanda nella maggior parte delle gare e spesso chi finira secondo dietro di lei.</p><h2>Successi in Carriera</h2><p>L''incredibile palmare di Johaug include:</p><ul><li>14 medaglie d''oro ai Campionati del Mondo</li><li>4 medaglie ai grandi Giochi</li><li>Oltre 80 vittorie in Coppa del Mondo</li><li>Diversi titoli di Coppa del Mondo generale</li><li>Campionessa della Coppa del Mondo di distanza piu volte</li></ul><p>Questi numeri la collocano tra le atlete degli sport invernali di maggior successo di sempre.</p><h2>Dominio in Gara</h2><p>Nelle gare di distanza, Johaug ha mostrato una superiorita notevole:</p><ul><li>Spesso vince con margini di oltre 30 secondi</li><li>La migliore scalatrice nel fondo femminile</li><li>Ritmo devastante su percorsi difficili</li><li>Tecnica eccezionale in tutte le condizioni</li></ul><p>La sua capacita di staccarsi dal gruppo e mantenere ritmi punitivi la rende quasi imbattibile nelle sue gare preferite.</p><h2>Filosofia di Allenamento</h2><p>Johaug e nota per il suo incredibile volume di allenamento. Si allena piu ore all''anno di quasi qualsiasi altro atleta in qualsiasi sport. Questa dedizione alla preparazione ha costruito la base di resistenza che alimenta le sue prestazioni in gara.</p><p>I suoi ritiri di allenamento estivi in montagna sono leggendari per la loro intensita.</p><h2>Oltre le Piste</h2><p>Fuori dalla neve, Johaug e diventata un''imprenditrice e stilista di successo. Il suo marchio di abbigliamento riflette il suo stile personale ed e diventato popolare in Norvegia.</p><p>Ha anche parlato apertamente delle sfide di salute mentale che gli atleti affrontano, diventando un''avvocata del benessere degli atleti.</p><h2>Eredita</h2><p>Che continui a gareggiare o si ritiri, l''eredita di Johaug e sicura. Ha ispirato una generazione di giovani sciatori e ridefinito cio che e possibile nello <a href=\"/cross-country-skiing-guide/\">sci di fondo</a>.</p><p>I suoi record potrebbero durare per decenni.</p>",
        "es": "<h2>Una Fuerza Dominante</h2><p>Therese Johaug es ampliamente considerada una de las mas grandes <a href=\"/cross-country-skiing-guide/\">esquiadoras de fondo</a> de todos los tiempos. Nacida en 1988 en Dalsbygda, Noruega, ha ganado mas medallas de oro en Campeonatos del Mundo que cualquier otra esquiadora de fondo en la historia.</p><p>Su dominio en las pruebas de distancia ha sido tan completo que la pregunta en la mayoria de las carreras es a menudo quien terminara segundo detras de ella.</p><h2>Logros en su Carrera</h2><p>El increible palmare de Johaug incluye:</p><ul><li>14 medallas de oro en Campeonatos del Mundo</li><li>4 medallas en grandes Juegos</li><li>Mas de 80 victorias en Copa del Mundo</li><li>Multiples titulos de Copa del Mundo general</li><li>Campeona de la Copa del Mundo de distancia multiples veces</li></ul><p>Estos numeros la colocan entre las atletas de deportes de invierno mas exitosas de la historia.</p><h2>Dominio en Carrera</h2><p>En las pruebas de distancia, Johaug ha mostrado una superioridad notable:</p><ul><li>A menudo gana por margenes de mas de 30 segundos</li><li>La mejor escaladora del esqui de fondo femenino</li><li>Ritmo devastador en circuitos dificiles</li><li>Tecnica excepcional en todas las condiciones</li></ul><p>Su capacidad para escaparse del grupo y mantener ritmos castigadores la hace casi invencible en sus pruebas preferidas.</p><h2>Filosofia de Entrenamiento</h2><p>Johaug es conocida por su increible volumen de entrenamiento. Entrena mas horas al ano que casi cualquier otro atleta en cualquier deporte. Esta dedicacion a la preparacion ha construido la base de resistencia que impulsa sus actuaciones en carrera.</p><p>Sus campamentos de entrenamiento de verano en las montanas son legendarios por su intensidad.</p><h2>Fuera de las Pistas</h2><p>Fuera de la nieve, Johaug se ha convertido en una exitosa empresaria y disenadora de moda. Su marca de ropa refleja su estilo personal y se ha vuelto popular en Noruega.</p><p>Tambien ha sido abierta sobre los desafios de salud mental que enfrentan los atletas, convirtiendose en defensora del bienestar de los atletas.</p><h2>Legado</h2><p>Ya sea que continue compitiendo o se retire, el legado de Johaug esta asegurado. Ha inspirado a una generacion de jovenes esquiadores y redefinido lo que es posible en el <a href=\"/cross-country-skiing-guide/\">esqui de fondo</a>.</p><p>Sus records podrian perdurar durante decadas.</p>",
        "pt": "<h2>Uma Forca Dominante</h2><p>Therese Johaug e amplamente considerada uma das maiores <a href=\"/cross-country-skiing-guide/\">esquiadoras cross-country</a> de todos os tempos. Nascida em 1988 em Dalsbygda, Noruega, ela ganhou mais medalhas de ouro em Campeonatos Mundiais do que qualquer outra esquiadora cross-country na historia.</p><p>Seu dominio nas provas de distancia foi tao completo que a pergunta na maioria das corridas e frequentemente quem terminara em segundo atras dela.</p><h2>Conquistas na Carreira</h2><p>O incrivel curriculo de Johaug inclui:</p><ul><li>14 medalhas de ouro em Campeonatos Mundiais</li><li>4 medalhas em grandes Jogos</li><li>Mais de 80 vitorias na Copa do Mundo</li><li>Multiplos titulos gerais da Copa do Mundo</li><li>Campea da Copa do Mundo de distancia varias vezes</li></ul><p>Esses numeros a colocam entre as atletas de esportes de inverno mais bem-sucedidas de todos os tempos.</p><h2>Dominio em Corrida</h2><p>Nas provas de distancia, Johaug mostrou superioridade notavel:</p><ul><li>Frequentemente vence por margens de mais de 30 segundos</li><li>Melhor escaladora do cross-country feminino</li><li>Ritmo devastador em percursos dificeis</li><li>Tecnica excepcional em todas as condicoes</li></ul><p>Sua capacidade de se destacar do pelotao e manter ritmos punitivos a torna quase imbativel em suas provas preferidas.</p><h2>Filosofia de Treinamento</h2><p>Johaug e conhecida por seu incrivel volume de treinamento. Ela treina mais horas por ano do que quase qualquer outro atleta em qualquer esporte. Essa dedicacao a preparacao construiu a base de resistencia que alimenta suas performances em corrida.</p><p>Seus acampamentos de treinamento de verao nas montanhas sao lendarios por sua intensidade.</p><h2>Alem das Pistas</h2><p>Fora da neve, Johaug se tornou uma empresaria e designer de moda bem-sucedida. Sua marca de roupas reflete seu estilo pessoal e se tornou popular na Noruega.</p><p>Ela tambem tem sido aberta sobre os desafios de saude mental que os atletas enfrentam, tornando-se uma defensora do bem-estar dos atletas.</p><h2>Legado</h2><p>Quer ela continue competindo ou se aposente, o legado de Johaug esta garantido. Ela inspirou uma geracao de jovens esquiadores e redefiniu o que e possivel no <a href=\"/cross-country-skiing-guide/\">esqui cross-country</a>.</p><p>Seus recordes podem durar por decadas.</p>",
        "nl": "<h2>Een Dominante Kracht</h2><p>Therese Johaug wordt algemeen beschouwd als een van de grootste <a href=\"/cross-country-skiing-guide/\">langlaufsters</a> aller tijden. Geboren in 1988 in Dalsbygda, Noorwegen, heeft ze meer WK-gouden medailles gewonnen dan enige andere vrouwelijke langlaufster in de geschiedenis.</p><p>Haar dominantie in afstandswedstrijden is zo volledig geweest dat de vraag bij de meeste races vaak is wie er tweede wordt achter haar.</p><h2>Carriere Prestaties</h2><p>Johaug''s ongelooflijke palmares omvat:</p><ul><li>14 WK-gouden medailles</li><li>4 medailles op grote Spelen</li><li>Meer dan 80 Wereldbekeroverwinningen</li><li>Meerdere algemene Wereldbekertitels</li><li>Meervoudig Afstand Wereldbekerkampioene</li></ul><p>Deze cijfers plaatsen haar onder de meest succesvolle wintersportatleten ooit.</p><h2>Racedominantie</h2><p>In afstandswedstrijden heeft Johaug opmerkelijke superioriteit getoond:</p><ul><li>Wint vaak met marges van 30+ seconden</li><li>Sterkste klimster in het vrouwenlanglaufen</li><li>Verwoestend tempo op moeilijke parcoursen</li><li>Uitzonderlijke techniek in alle omstandigheden</li></ul><p>Haar vermogen om weg te rijden van het peloton en straffe snelheden aan te houden maakt haar bijna onverslaanbaar in haar favoriete onderdelen.</p><h2>Trainingsfilosofie</h2><p>Johaug staat bekend om haar ongelooflijke trainingsvolume. Ze traint meer uren per jaar dan bijna elke andere atleet in welke sport dan ook. Deze toewijding aan voorbereiding heeft de uithoudingsbasis opgebouwd die haar raceprestaties aandrijft.</p><p>Haar zomertrainingskampen in de bergen zijn legendarisch om hun intensiteit.</p><h2>Buiten de Piste</h2><p>Buiten de sneeuw is Johaug een succesvolle zakenvrouw en modeontwerper geworden. Haar kledingmerk weerspiegelt haar persoonlijke stijl en is populair geworden in Noorwegen.</p><p>Ze is ook open geweest over mentale gezondheidsuitdagingen waarmee atleten worden geconfronteerd en is een pleitbezorger geworden voor het welzijn van atleten.</p><h2>Nalatenschap</h2><p>Of ze nu doorgaat met concurreren of stopt, Johaug''s nalatenschap staat vast. Ze heeft een generatie jonge skisters geinspireerd en herdefinieert wat mogelijk is in <a href=\"/cross-country-skiing-guide/\">langlaufen</a>.</p><p>Haar records kunnen decennia stand houden.</p>",
        "ar": "<h2>قوة مهيمنة</h2><p>تُعتبر تيريز يوهوغ على نطاق واسع واحدة من أعظم <a href=\"/cross-country-skiing-guide/\">متزلجات الريفي</a> على الإطلاق. ولدت في عام 1988 في دالسبيغدا، النرويج، وفازت بميداليات ذهبية في بطولات العالم أكثر من أي متزلجة ريفية أخرى في التاريخ.</p><p>كانت هيمنتها في سباقات المسافات كاملة لدرجة أن السؤال في معظم السباقات غالباً ما يكون من سيحل ثانياً خلفها.</p><h2>الإنجازات المهنية</h2><p>يتضمن سجل يوهوغ المذهل:</p><ul><li>14 ميدالية ذهبية في بطولات العالم</li><li>4 ميداليات في الألعاب الكبرى</li><li>أكثر من 80 انتصاراً في كأس العالم</li><li>عدة ألقاب عامة في كأس العالم</li><li>بطلة كأس العالم للمسافات عدة مرات</li></ul><p>تضعها هذه الأرقام بين أنجح رياضيات الألعاب الشتوية على الإطلاق.</p><h2>الهيمنة في السباقات</h2><p>في سباقات المسافات، أظهرت يوهوغ تفوقاً ملحوظاً:</p><ul><li>غالباً ما تفوز بفوارق تزيد عن 30 ثانية</li><li>أقوى متسلقة في تزلج الريفي للسيدات</li><li>إيقاع مدمر على المسارات الصعبة</li><li>تقنية استثنائية في جميع الظروف</li></ul><p>قدرتها على الانفصال عن المجموعة والحفاظ على سرعات عقابية تجعلها شبه لا تُقهر في أحداثها المفضلة.</p><h2>فلسفة التدريب</h2><p>تُعرف يوهوغ بحجم تدريبها المذهل. تتدرب ساعات أكثر سنوياً من أي رياضي تقريباً في أي رياضة. هذا التفاني في الإعداد بنى قاعدة التحمل التي تغذي أداءها في السباقات.</p><p>معسكراتها التدريبية الصيفية في الجبال أسطورية بسبب شدتها.</p><h2>خارج الحلبة</h2><p>بعيداً عن الثلج، أصبحت يوهوغ سيدة أعمال ومصممة أزياء ناجحة. علامتها التجارية للملابس تعكس أسلوبها الشخصي وأصبحت شائعة في النرويج.</p><p>كانت أيضاً منفتحة بشأن تحديات الصحة النفسية التي يواجهها الرياضيون، وأصبحت مدافعة عن رفاهية الرياضيين.</p><h2>الإرث</h2><p>سواء استمرت في المنافسة أو تقاعدت، فإن إرث يوهوغ مضمون. لقد ألهمت جيلاً من المتزلجين الشباب وأعادت تعريف ما هو ممكن في <a href=\"/cross-country-skiing-guide/\">التزلج الريفي</a>.</p><p>قد تصمد أرقامها القياسية لعقود.</p>",
        "ja": "<h2>圧倒的な力</h2><p>テレーセ・ヨーハウグは、史上最も偉大な<a href=\"/cross-country-skiing-guide/\">クロスカントリースキーヤー</a>の一人として広く認められています。1988年にノルウェーのダルスビグダで生まれ、歴史上どの女性クロスカントリースキーヤーよりも多くの世界選手権金メダルを獲得しています。</p><p>距離種目での彼女の支配は非常に完全で、ほとんどのレースでの問題は彼女の後ろで誰が2位になるかということです。</p><h2>キャリアの実績</h2><p>ヨーハウグの驚異的な記録には以下が含まれます：</p><ul><li>世界選手権金メダル14個</li><li>大会メダル4個</li><li>ワールドカップ勝利80以上</li><li>複数の総合ワールドカップタイトル</li><li>距離ワールドカップチャンピオン複数回</li></ul><p>これらの数字は、彼女を史上最も成功した冬季スポーツアスリートの一人に位置づけています。</p><h2>レースでの支配</h2><p>距離種目で、ヨーハウグは驚くべき優位性を示しています：</p><ul><li>しばしば30秒以上の差で勝利</li><li>女子クロスカントリーで最強のクライマー</li><li>難しいコースでの壊滅的なペース</li><li>あらゆる条件での卓越した技術</li></ul><p>集団から抜け出し、厳しいスピードを維持する能力は、彼女を好きな種目でほぼ無敵にしています。</p><h2>トレーニング哲学</h2><p>ヨーハウグは、信じられないほどのトレーニング量で知られています。彼女はどのスポーツのほぼどのアスリートよりも年間多くの時間トレーニングしています。この準備への献身が、彼女のレースパフォーマンスを支える持久力の基盤を構築しました。</p><p>山での夏のトレーニングキャンプは、その強度で伝説的です。</p><h2>トラック以外で</h2><p>雪の外では、ヨーハウグは成功したビジネスウーマンでファッションデザイナーになりました。彼女の服ブランドは彼女の個人的なスタイルを反映し、ノルウェーで人気になっています。</p><p>彼女はまた、アスリートが直面するメンタルヘルスの課題についてオープンに語り、アスリートの幸福のための支持者となっています。</p><h2>遺産</h2><p>競技を続けるか引退するかにかかわらず、ヨーハウグの遺産は確保されています。彼女は若いスキーヤーの世代にインスピレーションを与え、<a href=\"/cross-country-skiing-guide/\">クロスカントリースキー</a>で何が可能かを再定義しました。</p><p>彼女の記録は数十年続く可能性があります。</p>",
        "zh": "<h2>统治力量</h2><p>特蕾丝·约豪格被广泛认为是有史以来最伟大的<a href=\"/cross-country-skiing-guide/\">越野滑雪</a>运动员之一。1988年出生于挪威达尔斯比格达，她获得的世锦赛金牌比历史上任何其他女性越野滑雪运动员都多。</p><p>她在长距离项目上的统治是如此彻底，以至于大多数比赛的问题通常是谁将在她身后获得第二名。</p><h2>职业生涯成就</h2><p>约豪格令人难以置信的记录包括：</p><ul><li>14枚世锦赛金牌</li><li>4枚大型赛事奖牌</li><li>80多次世界杯胜利</li><li>多个世界杯总冠军头衔</li><li>多次获得长距离世界杯冠军</li></ul><p>这些数字使她跻身有史以来最成功的冬季运动员之列。</p><h2>比赛统治力</h2><p>在长距离项目中，约豪格表现出了非凡的优势：</p><ul><li>经常以超过30秒的优势获胜</li><li>女子越野滑雪中最强的爬坡能力</li><li>在困难赛道上毁灭性的节奏</li><li>在所有条件下都有出色的技术</li></ul><p>她脱离大部队并保持惩罚性速度的能力使她在自己喜欢的项目中几乎无敌。</p><h2>训练理念</h2><p>约豪格以其令人难以置信的训练量而闻名。她每年的训练时间比几乎任何运动中的任何其他运动员都多。这种对准备工作的奉献建立了支撑她比赛表现的耐力基础。</p><p>她在山区的夏季训练营以其强度而闻名。</p><h2>赛道之外</h2><p>在雪地之外，约豪格已成为一位成功的女商人和时装设计师。她的服装品牌反映了她的个人风格，在挪威很受欢迎。</p><p>她也公开谈论运动员面临的心理健康挑战，成为运动员福祉的倡导者。</p><h2>遗产</h2><p>无论她继续参赛还是退役，约豪格的遗产都已确定。她激励了一代年轻滑雪运动员，并重新定义了<a href=\"/cross-country-skiing-guide/\">越野滑雪</a>的可能性。</p><p>她的记录可能会保持数十年。</p>",
        "ko": "<h2>압도적인 힘</h2><p>테레세 요하우그는 역사상 가장 위대한 <a href=\"/cross-country-skiing-guide/\">크로스컨트리 스키</a> 선수 중 한 명으로 널리 인정받고 있습니다. 1988년 노르웨이 달스비그다에서 태어난 그녀는 역사상 다른 어떤 여성 크로스컨트리 스키 선수보다 더 많은 세계선수권대회 금메달을 획득했습니다.</p><p>장거리 종목에서의 그녀의 지배력은 너무나 완전해서 대부분의 경기에서의 질문은 종종 그녀 뒤에서 누가 2위를 할 것인가입니다.</p><h2>커리어 업적</h2><p>요하우그의 놀라운 기록에는 다음이 포함됩니다:</p><ul><li>세계선수권대회 금메달 14개</li><li>주요 대회 메달 4개</li><li>80회 이상의 월드컵 우승</li><li>여러 번의 월드컵 종합 타이틀</li><li>여러 차례 장거리 월드컵 챔피언</li></ul><p>이 숫자들은 그녀를 역대 가장 성공한 동계 스포츠 선수 중 한 명으로 자리매김하게 합니다.</p><h2>레이스 지배력</h2><p>장거리 종목에서 요하우그는 놀라운 우위를 보여주었습니다:</p><ul><li>종종 30초 이상의 차이로 우승</li><li>여자 크로스컨트리에서 가장 강한 클라이머</li><li>어려운 코스에서의 압도적인 페이스</li><li>모든 조건에서 탁월한 기술</li></ul><p>집단에서 벗어나 가혹한 속도를 유지하는 그녀의 능력은 그녀가 선호하는 종목에서 거의 무적으로 만듭니다.</p><h2>훈련 철학</h2><p>요하우그는 믿을 수 없는 훈련량으로 유명합니다. 그녀는 거의 모든 스포츠의 다른 어떤 선수보다 연간 더 많은 시간을 훈련합니다. 이러한 준비에 대한 헌신이 그녀의 레이스 성과를 뒷받침하는 지구력 기반을 구축했습니다.</p><p>산에서의 그녀의 여름 훈련 캠프는 그 강도로 전설적입니다.</p><h2>트랙 밖에서</h2><p>눈 밖에서 요하우그는 성공한 사업가이자 패션 디자이너가 되었습니다. 그녀의 의류 브랜드는 그녀의 개인적인 스타일을 반영하며 노르웨이에서 인기를 끌고 있습니다.</p><p>그녀는 또한 선수들이 직면하는 정신 건강 문제에 대해 솔직하게 이야기하며 선수 복지의 옹호자가 되었습니다.</p><h2>유산</h2><p>그녀가 계속 경쟁하든 은퇴하든 요하우그의 유산은 확고합니다. 그녀는 젊은 스키어 세대에게 영감을 주었고 <a href=\"/cross-country-skiing-guide/\">크로스컨트리 스키</a>에서 가능한 것을 재정의했습니다.</p><p>그녀의 기록은 수십 년 동안 유지될 수 있습니다.</p>"
    }',
    'athlete-profile',
    'XC',
    '{
        "en": "Therese Johaug profile: Norwegian cross-country skiing legend with 14 World Championship golds. Career stats, training philosophy, and dominant racing record.",
        "de": "Therese Johaug Profil: Norwegische Langlauf-Legende mit 14 WM-Goldmedaillen. Karrierestatistiken, Trainingsphilosophie und dominante Rennbilanz.",
        "fr": "Profil de Therese Johaug : legende norvegienne du ski de fond avec 14 titres mondiaux. Stats de carriere, philosophie d''entrainement et domination en course.",
        "it": "Profilo di Therese Johaug: leggenda norvegese dello sci di fondo con 14 ori mondiali. Statistiche della carriera, filosofia di allenamento e dominio in gara.",
        "es": "Perfil de Therese Johaug: leyenda noruega del esqui de fondo con 14 oros mundiales. Estadisticas de carrera, filosofia de entrenamiento y dominio en carrera.",
        "pt": "Perfil de Therese Johaug: lenda norueguesa do esqui cross-country com 14 ouros mundiais. Estatisticas da carreira, filosofia de treino e dominio em corrida.",
        "nl": "Therese Johaug profiel: Noorse langlauflegende met 14 WK-gouden medailles. Carriere statistieken, trainingsfilosofie en dominant racerecord.",
        "ar": "ملف تيريز يوهوغ: أسطورة التزلج الريفي النرويجية مع 14 ذهبية عالمية. إحصائيات المسيرة وفلسفة التدريب وسجل السباقات المهيمن.",
        "ja": "テレーセ・ヨーハウグのプロフィール：14の世界選手権金メダルを持つノルウェーのクロスカントリースキーレジェンド。キャリア統計、トレーニング哲学、圧倒的なレース記録。",
        "zh": "特蕾丝·约豪格简介：拥有14枚世锦赛金牌的挪威越野滑雪传奇。职业生涯数据、训练理念及统治性比赛记录。",
        "ko": "테레세 요하우그 프로필: 14개의 세계선수권대회 금메달을 보유한 노르웨이 크로스컨트리 스키 전설. 커리어 통계, 훈련 철학, 압도적인 레이싱 기록."
    }',
    'published',
    NOW(),
    'generated'
);
